//! JavaScript backend: typed IR -> readable ES-module JavaScript (Node 18+).
//!
//! Value semantics strategy (lockstep.md §5.1), mirroring backend_py:
//! - non-inout composite parameters are defensively copied at function entry;
//! - aliasing reads (variables, fields, indexing, unwraps) are deep-copied at
//!   storing positions (assignment RHS, constructor args, container inserts,
//!   returns); enums and Option/Result share safely because nothing can
//!   mutate them in place — their payloads are copied on extraction instead;
//! - inout parameters are threaded through return values: every function
//!   returns `[ret?, ...inouts]` (bare value when a single component) and
//!   call sites reassign — `n = bump(n)` / `[y, n] = take(n)`;
//! - deep equality goes through `_rt.eq` (arrays have no built-in deep equal);
//! - `sudo int` is BigInt (`5n`); `sudo float` is IEEE number;
//! - match lowers to `if/else if` with `instanceof` so loop `break`/`continue`
//!   inside match arms target the enclosing loop with no switch capture.

use sudoc_ir::{
    BinaryOp, Builtin, IrExpr, IrExprKind, IrFunc, IrModule, IrPattern, IrStmt, Place, Ty,
    UnaryOp,
};

mod boundary;
pub use boundary::{api_file, emit_api};

/// The shared JavaScript runtime, written alongside every generated module.
pub const RUNTIME: &str = include_str!("runtime/_sudo_rt.mjs");
pub const RUNTIME_FILE: &str = "_sudo_rt.mjs";

/// File name of the internal implementation module.
pub fn impl_file(module: &str) -> String {
    format!("_{module}_impl.mjs")
}

/// Emit a JS module for the IR. When `with_tests` is set, `test` blocks
/// become `test_*` functions plus a direct-run runner that executes them.
pub fn emit(module: &IrModule, with_tests: bool) -> String {
    emit_with(module, std::slice::from_ref(module), with_tests)
}

/// Emit `module`, resolving cross-module callee signatures (inout-taking
/// functions in particular) against `all_modules` — the whole program,
/// not just `module` itself. `emit_program` calls this with the real
/// program; `emit` (single-module callers, back-compat) passes a
/// one-element slice.
fn emit_with(module: &IrModule, all_modules: &[IrModule], with_tests: bool) -> String {
    Emitter { m: module, all: all_modules, out: String::new() }.run(with_tests)
}

struct Emitter<'a> {
    m: &'a IrModule,
    /// Every module in the program, for cross-module callee lookup.
    all: &'a [IrModule],
    out: String,
}

impl Emitter<'_> {
    /// Resolve a callee's signature across the whole program: a bare name
    /// looks in the current module; a `module.func` qualified name looks up
    /// the named module in `self.all`. Mirrors the Haskell backend's
    /// `lookupFunc`/`splitQual` (backends/haskell/Emit.hs).
    fn resolve_func(&self, name: &str) -> Option<&IrFunc> {
        match name.split_once('.') {
            Some((modname, fname)) => self.all.iter().find(|m| m.name == modname)?.func(fname),
            None => self.m.func(name),
        }
    }

    fn run(mut self, with_tests: bool) -> String {
        self.line(
            0,
            &format!(
                "// Generated by sudoc from {}.sudo — do not edit; edit the sudo source.",
                self.m.name
            ),
        );
        self.line(0, "import * as _rt from \"./_sudo_rt.mjs\";");
        for dep in &self.m.imports {
            self.line(0, &format!("import * as {dep} from \"./_{dep}_impl.mjs\";"));
        }
        self.blank();

        for r in &self.m.records {
            self.line(0, &format!("export class {} {{", r.name));
            self.line(1, &format!("static _sudoKind = [\"r\", \"{}\"];", r.name));
            let fields: Vec<&str> = r.fields.iter().map(|(n, _)| n.as_str()).collect();
            let field_lits: Vec<String> = fields.iter().map(|f| format!("\"{f}\"")).collect();
            self.line(1, &format!("static _sudoFields = [{}];", field_lits.join(", ")));
            self.line(1, &format!("constructor({}) {{", fields.join(", ")));
            for f in &fields {
                self.line(2, &format!("this.{f} = {f};"));
            }
            self.line(1, "}");
            self.line(0, "}");
            self.blank();
        }
        for e in &self.m.enums {
            for v in &e.variants {
                let cls = format!("{}_{}", e.name, v.name);
                self.line(0, &format!("export class {cls} {{"));
                self.line(
                    1,
                    &format!("static _sudoKind = [\"e\", \"{}.{}\"];", e.name, v.name),
                );
                let fields: Vec<&str> = v.fields.iter().map(|(n, _)| n.as_str()).collect();
                let field_lits: Vec<String> = fields.iter().map(|f| format!("\"{f}\"")).collect();
                self.line(1, &format!("static _sudoFields = [{}];", field_lits.join(", ")));
                self.line(1, &format!("constructor({}) {{", fields.join(", ")));
                for f in &fields {
                    self.line(2, &format!("this.{f} = {f};"));
                }
                self.line(1, "}");
                self.line(0, "}");
                self.blank();
            }
        }
        for c in &self.m.consts {
            let value = self.expr(&c.value, 0);
            self.line(0, &format!("export const {} = {};", c.name, value));
        }
        if !self.m.consts.is_empty() {
            self.blank();
        }

        for f in &self.m.funcs {
            self.func(f);
            self.blank();
        }

        if with_tests {
            let names = sudoc_ir::names::test_fn_names(&self.m.tests);
            for (t, name) in self.m.tests.iter().zip(&names) {
                self.line(0, &format!("function {name}() {{"));
                if !t.body.is_empty() {
                    self.block(&t.body, 1, &[]);
                }
                self.line(0, "}");
                self.blank();
            }
            // Explicit test list: JS modules have no globals() equivalent.
            // Realpath both sides: argv[1] may be a non-realpath absolute path
            // (e.g. /var/... vs /private/var/... on macOS) while import.meta.url
            // is already realpath-resolved by the ESM loader.
            self.line(0, "import { fileURLToPath } from \"node:url\";");
            self.line(0, "import fs from \"node:fs\";");
            self.line(0, "import path from \"node:path\";");
            self.line(0, "const _sudo_main = (() => {");
            self.line(1, "try {");
            self.line(
                2,
                "return process.argv[1] && fs.realpathSync(path.resolve(process.argv[1])) === fileURLToPath(import.meta.url);",
            );
            self.line(1, "} catch {");
            self.line(2, "return false;");
            self.line(1, "}");
            self.line(0, "})();");
            self.line(0, "if (_sudo_main) {");
            let pairs: Vec<String> =
                names.iter().map(|n| format!("[\"{n}\", {n}]")).collect();
            self.line(
                1,
                &format!("process.exit(_rt.run_tests([{}]));", pairs.join(", ")),
            );
            self.line(0, "}");
        }
        self.out
    }

    fn func(&mut self, f: &IrFunc) {
        let params: Vec<&str> = f.params.iter().map(|p| p.name.as_str()).collect();
        self.line(
            0,
            &format!("export function {}({}) {{", f.name, params.join(", ")),
        );
        for p in &f.params {
            if !p.inout && needs_dup(&p.ty) {
                self.line(1, &format!("{0} = _rt.dup({0});", p.name));
            }
        }
        let inouts: Vec<String> =
            f.params.iter().filter(|p| p.inout).map(|p| p.name.clone()).collect();
        self.block(&f.body, 1, &inouts);
        if !definitely_returns(&f.body) && !inouts.is_empty() {
            self.line(1, &format!("return {};", ret_parts(&inouts)));
        }
        self.line(0, "}");
    }

    fn block(&mut self, stmts: &[IrStmt], depth: usize, inouts: &[String]) {
        for s in stmts {
            self.stmt(s, depth, inouts);
        }
    }

    fn stmt(&mut self, s: &IrStmt, depth: usize, inouts: &[String]) {
        match s {
            IrStmt::Assign { target, value, declares } => {
                if let Some(call) = self.as_inout_call(value) {
                    self.emit_inout_call(Some(target), call, depth, *declares);
                    return;
                }
                let v = self.store(value, depth);
                self.assign_to_place(target, &v, depth, *declares);
            }
            IrStmt::TupleAssign { targets, declares, value } => {
                let v = self.store(value, depth);
                for (t, d) in targets.iter().zip(declares.iter()) {
                    if *d {
                        self.line(depth, &format!("let {t};"));
                    }
                }
                self.line(depth, &format!("[{}] = {};", targets.join(", "), v));
            }
            IrStmt::Expr(e) => {
                if let Some(call) = self.as_inout_call(e) {
                    self.emit_inout_call(None, call, depth, false);
                    return;
                }
                let code = self.expr(e, depth);
                self.line(depth, &format!("{code};"));
            }
            IrStmt::If { arms, else_block } => {
                for (i, (cond, body)) in arms.iter().enumerate() {
                    let c = self.expr(cond, depth);
                    if i == 0 {
                        self.line(depth, &format!("if ({c}) {{"));
                    } else {
                        self.line(depth, &format!("}} else if ({c}) {{"));
                    }
                    self.block(body, depth + 1, inouts);
                }
                if let Some(body) = else_block {
                    self.line(depth, "} else {");
                    self.block(body, depth + 1, inouts);
                    self.line(depth, "}");
                } else if !arms.is_empty() {
                    self.line(depth, "}");
                }
            }
            IrStmt::While { cond, body } => {
                let c = self.expr(cond, depth);
                self.line(depth, &format!("while ({c}) {{"));
                self.block(body, depth + 1, inouts);
                self.line(depth, "}");
            }
            IrStmt::ForRange { var, from, to, down, body } => {
                // Bounds evaluated once. BigInt has no wraparound, so a plain
                // increment past i64 MAX terminates normally without trapping.
                let f = self.expr(from, depth);
                let t = self.expr(to, depth);
                let from_tmp = format!("_sudo_from_{var}");
                let to_tmp = format!("_sudo_to_{var}");
                self.line(depth, &format!("const {from_tmp} = {f};"));
                self.line(depth, &format!("const {to_tmp} = {t};"));
                if *down {
                    self.line(
                        depth,
                        &format!(
                            "for (let {var} = {from_tmp}; {var} >= {to_tmp}; {var} -= 1n) {{"
                        ),
                    );
                } else {
                    self.line(
                        depth,
                        &format!(
                            "for (let {var} = {from_tmp}; {var} <= {to_tmp}; {var} += 1n) {{"
                        ),
                    );
                }
                self.block(body, depth + 1, inouts);
                self.line(depth, "}");
            }
            IrStmt::ForIn { vars, iter, body } => {
                let it = self.expr(iter, depth);
                let iterable = match strip(&iter.ty) {
                    Ty::List(_) => format!("{it}.slice()"),
                    Ty::Set(_) => format!("{it}.items_list()"),
                    Ty::Map(..) => format!("{it}.pairs()"),
                    _ => it,
                };
                if vars.len() == 1 {
                    self.line(depth, &format!("for (const {} of {iterable}) {{", vars[0]));
                } else {
                    self.line(
                        depth,
                        &format!("for (const [{}] of {iterable}) {{", vars.join(", ")),
                    );
                }
                self.block(body, depth + 1, inouts);
                self.line(depth, "}");
            }
            IrStmt::Match { scrutinee, arms } => {
                // if/else chain (not switch) so break/continue target loops.
                let sc = self.expr(scrutinee, depth);
                self.line(depth, "{");
                self.line(depth + 1, &format!("const _sudo_sc = {sc};"));
                for (i, arm) in arms.iter().enumerate() {
                    let (cond, binders) = self.pattern_cond_and_binders("_sudo_sc", &arm.pattern);
                    if i == 0 {
                        self.line(depth + 1, &format!("if ({cond}) {{"));
                    } else {
                        self.line(depth + 1, &format!("}} else if ({cond}) {{"));
                    }
                    for (name, access, ty) in binders {
                        if let Some(ty) = ty {
                            if needs_dup(&ty) {
                                self.line(
                                    depth + 2,
                                    &format!("const {name} = _rt.dup({access});"),
                                );
                                continue;
                            }
                        }
                        self.line(depth + 2, &format!("const {name} = {access};"));
                    }
                    self.block(&arm.body, depth + 2, inouts);
                }
                if !arms.is_empty() {
                    self.line(depth + 1, "}");
                }
                self.line(depth, "}");
            }
            IrStmt::Return(v) => {
                let mut parts: Vec<String> = Vec::new();
                if let Some(v) = v {
                    parts.push(self.store(v, depth));
                }
                parts.extend(inouts.iter().cloned());
                if parts.is_empty() {
                    self.line(depth, "return;");
                } else {
                    self.line(depth, &format!("return {};", ret_parts(&parts)));
                }
            }
            IrStmt::Assert { cond, line } => {
                if let IrExprKind::Binary { op: BinaryOp::Eq, lhs, rhs } = &cond.kind {
                    let l = self.expr(lhs, depth);
                    let r = self.expr(rhs, depth);
                    self.line(depth, &format!("_rt.sudo_assert_eq({l}, {r}, {line});"));
                } else {
                    let c = self.expr(cond, depth);
                    self.line(depth, &format!("_rt.sudo_assert({c}, {line});"));
                }
            }
            IrStmt::Skip => {}
            IrStmt::Break => self.line(depth, "break;"),
            IrStmt::Continue => self.line(depth, "continue;"),
            IrStmt::ExpectTrap { kind, body, line } => {
                self.line(depth, "let _trapped = false;");
                self.line(depth, "try {");
                self.block(body, depth + 1, inouts);
                self.line(depth, "} catch (_t) {");
                self.line(depth + 1, "if (!(_t instanceof _rt.SudoTrap)) throw _t;");
                self.line(depth + 1, "_trapped = true;");
                self.line(depth + 1, &format!("if (_t.kind !== \"{kind}\") {{"));
                self.line(
                    depth + 2,
                    &format!(
                        "throw new _rt.SudoTrap(\"AssertFailed\", `line {line}: expected trap {kind}, got ${{_t.kind}}`);"
                    ),
                );
                self.line(depth + 1, "}");
                self.line(depth, "}");
                self.line(depth, "if (!_trapped) {");
                self.line(
                    depth + 1,
                    &format!(
                        "throw new _rt.SudoTrap(\"AssertFailed\", \"line {line}: expected trap {kind}, but nothing trapped\");"
                    ),
                );
                self.line(depth, "}");
            }
        }
    }

    /// Returns (condition expression, binders as (name, access_expr, optional field ty)).
    fn pattern_cond_and_binders(
        &self,
        scrut: &str,
        p: &IrPattern,
    ) -> (String, Vec<(String, String, Option<Ty>)>) {
        match p {
            IrPattern::Int(v) => (format!("{scrut} === {v}n"), Vec::new()),
            IrPattern::Bool(true) => (format!("{scrut} === true"), Vec::new()),
            IrPattern::Bool(false) => (format!("{scrut} === false"), Vec::new()),
            IrPattern::Wildcard => ("true".into(), Vec::new()),
            IrPattern::Variant { enum_name, variant, binders } => {
                let (cls, field_names) = match (enum_name.as_str(), variant.as_str()) {
                    ("Option", "Some") => ("_rt.Some".to_string(), vec!["value".to_string()]),
                    ("Option", "None") => ("_rt.NoneOpt".to_string(), Vec::new()),
                    ("Result", "Ok") => ("_rt.Ok".to_string(), vec!["value".to_string()]),
                    ("Result", "Err") => ("_rt.Err".to_string(), vec!["error".to_string()]),
                    _ => {
                        let cls = format!("{enum_name}_{variant}");
                        let fields = self
                            .m
                            .enum_(enum_name)
                            .and_then(|e| e.variants.iter().find(|v| v.name == *variant))
                            .map(|v| v.fields.iter().map(|(n, _)| n.clone()).collect())
                            .unwrap_or_default();
                        (cls, fields)
                    }
                };
                let cond = format!("{scrut} instanceof {cls}");
                let mut bound = Vec::new();
                for (i, b) in binders.iter().enumerate() {
                    let field = field_names.get(i).cloned().unwrap_or_else(|| format!("_{i}"));
                    let ty = self.variant_field_ty(enum_name, variant, i);
                    bound.push((b.clone(), format!("{scrut}.{field}"), ty));
                }
                (cond, bound)
            }
        }
    }

    fn as_inout_call<'e>(&self, e: &'e IrExpr) -> Option<(&'e str, &'e [IrExpr])> {
        if let IrExprKind::CallFunc { name, args } = &e.kind {
            let f = self.resolve_func(name)?;
            if f.params.iter().any(|p| p.inout) {
                return Some((name, args));
            }
        }
        None
    }

    fn emit_inout_call(
        &mut self,
        target: Option<&Place>,
        (name, args): (&str, &[IrExpr]),
        depth: usize,
        declares: bool,
    ) {
        let f = self.resolve_func(name).expect("callee exists").clone();
        let mut arg_code = Vec::new();
        let mut writebacks = Vec::new();
        for (a, p) in args.iter().zip(&f.params) {
            let code = self.expr(a, depth);
            if p.inout {
                writebacks.push(code.clone());
            }
            arg_code.push(code);
        }
        let call = format!("{name}({})", arg_code.join(", "));
        let mut targets: Vec<String> = Vec::new();
        let mut indirect: Option<&Place> = None;
        let mut ret_declares = false;
        if f.ret.is_some() {
            match target {
                Some(Place::Var(v)) => {
                    targets.push(v.clone());
                    ret_declares = declares;
                }
                Some(p) => {
                    targets.push("_sudo_r".into());
                    indirect = Some(p);
                }
                None => targets.push(String::new()),
            }
        }
        targets.extend(writebacks);
        let lhs = if targets.len() == 1 {
            targets[0].clone()
        } else {
            format!("[{}]", targets.join(", "))
        };
        if targets.len() == 1 && ret_declares {
            self.line(depth, &format!("let {lhs} = {call};"));
        } else if targets.len() == 1 && f.ret.is_some() && matches!(target, Some(Place::Var(_))) {
            // May need let for first assignment of ret-only+inout path handled above.
            if declares {
                self.line(depth, &format!("let {lhs} = {call};"));
            } else {
                self.line(depth, &format!("{lhs} = {call};"));
            }
        } else if targets.len() == 1 {
            self.line(depth, &format!("{lhs} = {call};"));
        } else {
            // Multi-value: declare ret var if needed, then destructure.
            if ret_declares {
                if let Some(Place::Var(v)) = target {
                    self.line(depth, &format!("let {v};"));
                }
            }
            self.line(depth, &format!("{lhs} = {call};"));
        }
        if let Some(p) = indirect {
            self.assign_to_place(p, "_sudo_r", depth, false);
        }
    }

    fn assign_to_place(&mut self, place: &Place, value: &str, depth: usize, declares: bool) {
        match place {
            Place::Var(n) => {
                if declares {
                    self.line(depth, &format!("let {n} = {value};"));
                } else {
                    self.line(depth, &format!("{n} = {value};"));
                }
            }
            Place::Index { base, base_ty, index } => {
                let b = self.place_expr(base, depth);
                let i = self.expr(index, depth);
                match strip(base_ty) {
                    Ty::Map(..) => self.line(depth, &format!("{b}.set({i}, {value});")),
                    _ => self.line(depth, &format!("_rt.put({b}, {i}, {value});")),
                }
            }
            Place::Field { base, name, .. } => {
                let b = self.place_expr(base, depth);
                self.line(depth, &format!("{b}.{name} = {value};"));
            }
        }
    }

    fn place_expr(&mut self, place: &Place, depth: usize) -> String {
        match place {
            Place::Var(n) => n.clone(),
            Place::Index { base, base_ty, index } => {
                let b = self.place_expr(base, depth);
                let i = self.expr(index, depth);
                match strip(base_ty) {
                    Ty::Map(..) => format!("{b}.get({i})"),
                    _ => format!("_rt.at({b}, {i})"),
                }
            }
            Place::Field { base, name, .. } => {
                let b = self.place_expr(base, depth);
                format!("{b}.{name}")
            }
        }
    }

    fn variant_field_ty(&self, enum_name: &str, variant: &str, i: usize) -> Option<Ty> {
        // Option/Result field types are not in the module enum table; payloads
        // are copied at extraction when needs_dup on the binder type — for
        // built-ins we don't know the payload ty from the enum def, so rely on
        // IrExpr types only at other copy points. Match binders for Option
        // payload: we look up nothing here for Option/Result.
        if enum_name == "Option" || enum_name == "Result" {
            return None;
        }
        let e = self.m.enum_(enum_name)?;
        let v = e.variants.iter().find(|v| v.name == variant)?;
        v.fields.get(i).map(|(_, t)| t.clone())
    }

    fn store(&mut self, e: &IrExpr, depth: usize) -> String {
        let code = self.expr(e, depth);
        if aliasing(&e.kind) && needs_dup(&e.ty) {
            format!("_rt.dup({code})")
        } else {
            code
        }
    }

    fn expr(&mut self, e: &IrExpr, depth: usize) -> String {
        self.expr_prec(e, 0, depth)
    }

    /// Emit with parentheses if this expression binds looser than `ctx`.
    ///
    /// JS precedence (low → high binding strength), NOT Python's:
    ///   1 = `||`, 2 = `&&`, 3 = `===`/`!==`, 4 = `<`/`<=`/`>`/`>=`,
    ///   5 = `+`/`-`, 6 = `*`/`/`/`%`, 7 = unary `!`/`-`, 9 = atom.
    /// Critical differences from Python: `!` binds tighter than every binary
    /// op (so `not (a == b)` needs `!(a === b)`), and equality is looser than
    /// relational (so `a < b === c < d` is `(a < b) === (c < d)` without
    /// forcing shared-tier parens the way Python comparisons do).
    fn expr_prec(&mut self, e: &IrExpr, ctx: u8, depth: usize) -> String {
        let (code, prec) = self.expr_raw(e, depth);
        if prec < ctx {
            format!("({code})")
        } else {
            code
        }
    }

    fn expr_raw(&mut self, e: &IrExpr, depth: usize) -> (String, u8) {
        let atom = 9u8;
        match &e.kind {
            IrExprKind::Int(v) => (format!("{v}n"), if *v < 0 { 7 } else { atom }),
            IrExprKind::Float(v) => {
                let s = js_float_lit(*v);
                (s, if *v < 0.0 { 7 } else { atom })
            }
            IrExprKind::Bool(v) => (if *v { "true" } else { "false" }.into(), atom),
            IrExprKind::Text(s) => (format!("_rt.txt({})", js_text_str(s)), atom),
            IrExprKind::Local(n) | IrExprKind::Const(n) | IrExprKind::FuncRef(n) => {
                (n.clone(), atom)
            }
            IrExprKind::List(xs) => {
                let items: Vec<String> = xs.iter().map(|x| self.store(x, depth)).collect();
                (format!("[{}]", items.join(", ")), atom)
            }
            IrExprKind::Tuple(xs) => {
                // Tuples are JS arrays (same representation as lists).
                let items: Vec<String> = xs.iter().map(|x| self.store(x, depth)).collect();
                (format!("[{}]", items.join(", ")), atom)
            }
            IrExprKind::CallFunc { name, args } => {
                let a: Vec<String> = args.iter().map(|x| self.expr(x, depth)).collect();
                (format!("{name}({})", a.join(", ")), atom)
            }
            IrExprKind::CallValue { callee, args } => {
                let c = self.expr_prec(callee, atom, depth);
                let a: Vec<String> = args.iter().map(|x| self.expr(x, depth)).collect();
                (format!("{c}({})", a.join(", ")), atom)
            }
            IrExprKind::NewRecord { name, args } => {
                let a: Vec<String> = args.iter().map(|x| self.store(x, depth)).collect();
                (format!("new {name}({})", a.join(", ")), atom)
            }
            IrExprKind::NewVariant { enum_name, variant, args } => {
                let a: Vec<String> = args.iter().map(|x| self.store(x, depth)).collect();
                let code = match (enum_name.as_str(), variant.as_str()) {
                    ("Option", "Some") => format!("new _rt.Some({})", a.join(", ")),
                    ("Option", "None") => "_rt.NONE".to_string(),
                    ("Result", "Ok") => format!("new _rt.Ok({})", a.join(", ")),
                    ("Result", "Err") => format!("new _rt.Err({})", a.join(", ")),
                    _ => format!("new {enum_name}_{variant}({})", a.join(", ")),
                };
                (code, atom)
            }
            IrExprKind::Builtin { builtin, args } => (self.builtin(*builtin, args, depth), atom),
            IrExprKind::MutBuiltin { builtin, recv, args, .. } => {
                (self.mut_builtin(*builtin, recv, args, depth), atom)
            }
            IrExprKind::GetField { recv, name } => {
                let r = self.expr_prec(recv, atom, depth);
                (format!("{r}.{name}"), atom)
            }
            IrExprKind::Index { recv, index } => {
                let r = self.expr_prec(recv, atom, depth);
                let i = self.expr(index, depth);
                match strip(&recv.ty) {
                    Ty::Map(..) => (format!("{r}.get({i})"), atom),
                    _ => (format!("_rt.at({r}, {i})"), atom),
                }
            }
            IrExprKind::Unary { op, operand } => match op {
                UnaryOp::Neg => match strip(&e.ty) {
                    Ty::Int => {
                        let x = self.expr(operand, depth);
                        (format!("_rt.neg({x})"), atom)
                    }
                    _ => {
                        // Unary `-` binds tighter than every binary; paren any binary operand.
                        let x = self.expr_prec(operand, 7, depth);
                        (format!("-{x}"), 7)
                    }
                },
                UnaryOp::Not => {
                    // JS `!` is unary-tier (unlike Python `not`, which is looser
                    // than comparisons). Force parens around any binary operand:
                    // `not (a == b)` → `!(a === b)`, never `!a === b`.
                    let x = self.expr_prec(operand, 7, depth);
                    (format!("!{x}"), 7)
                }
            },
            IrExprKind::Binary { op, lhs, rhs } => self.binary(*op, lhs, rhs, &e.ty, depth),
        }
    }

    fn binary(
        &mut self,
        op: BinaryOp,
        lhs: &IrExpr,
        rhs: &IrExpr,
        result_ty: &Ty,
        depth: usize,
    ) -> (String, u8) {
        let is_int = matches!(strip(&lhs.ty), Ty::Int);
        let is_float = matches!(strip(&lhs.ty), Ty::Float);
        match op {
            BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul => {
                let sym = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    _ => "*",
                };
                let prec = if sym == "*" { 6 } else { 5 };
                if is_int {
                    let l = self.expr_prec(lhs, prec, depth);
                    let r = self.expr_prec(rhs, prec + 1, depth);
                    (format!("_rt.chk({l} {sym} {r})"), 9)
                } else if is_float {
                    let l = self.expr_prec(lhs, prec, depth);
                    let r = self.expr_prec(rhs, prec + 1, depth);
                    (format!("{l} {sym} {r}"), prec)
                } else {
                    // List concatenation.
                    let l = self.expr_prec(lhs, 9, depth);
                    let r = self.expr_prec(rhs, 9, depth);
                    if needs_dup(result_ty) {
                        (format!("_rt.dup({l}.concat({r}))"), 9)
                    } else {
                        (format!("{l}.concat({r})"), 9)
                    }
                }
            }
            BinaryOp::Div => {
                let l = self.expr(lhs, depth);
                let r = self.expr(rhs, depth);
                if is_int {
                    (format!("_rt.div({l}, {r})"), 9)
                } else {
                    (format!("_rt.fdiv({l}, {r})"), 9)
                }
            }
            BinaryOp::Mod => {
                let l = self.expr(lhs, depth);
                let r = self.expr(rhs, depth);
                (format!("_rt.mod_i64({l}, {r})"), 9)
            }
            BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge => {
                let sym = match op {
                    BinaryOp::Lt => "<",
                    BinaryOp::Le => "<=",
                    BinaryOp::Gt => ">",
                    _ => ">=",
                };
                // Relational tier 4 (tighter than equality tier 3 in JS).
                let l = self.expr_prec(lhs, 4, depth);
                let r = self.expr_prec(rhs, 5, depth);
                (format!("{l} {sym} {r}"), 4)
            }
            BinaryOp::Eq | BinaryOp::Ne => {
                if scalar_eq(&lhs.ty) {
                    let sym = if op == BinaryOp::Eq { "===" } else { "!==" };
                    // Equality tier 3 — looser than relational, so
                    // `a < b === c < d` needs no extra parens on the relations.
                    let l = self.expr_prec(lhs, 3, depth);
                    let r = self.expr_prec(rhs, 4, depth);
                    (format!("{l} {sym} {r}"), 3)
                } else {
                    let l = self.expr(lhs, depth);
                    let r = self.expr(rhs, depth);
                    let call = format!("_rt.eq({l}, {r})");
                    if op == BinaryOp::Eq {
                        (call, 9)
                    } else {
                        // `!` is unary-tier 7 (same as UnaryOp::Not).
                        (format!("!{call}"), 7)
                    }
                }
            }
            BinaryOp::And => {
                let l = self.expr_prec(lhs, 2, depth);
                let r = self.expr_prec(rhs, 3, depth);
                (format!("{l} && {r}"), 2)
            }
            BinaryOp::Or => {
                let l = self.expr_prec(lhs, 1, depth);
                let r = self.expr_prec(rhs, 2, depth);
                (format!("{l} || {r}"), 1)
            }
        }
    }

    fn builtin(&mut self, b: Builtin, args: &[IrExpr], depth: usize) -> String {
        let a = |s: &mut Self, i: usize| s.expr(&args[i], depth);
        let a_atom = |s: &mut Self, i: usize| s.expr_prec(&args[i], 9, depth);
        match b {
            Builtin::AbsInt => format!("_rt.abs_i64({})", a(self, 0)),
            // Host builtins via globalThis: a sudo record named BigInt/Number/Math
            // (e.g. stdlib/bigint.sudo) would otherwise shadow the global and
            // turn `BigInt(xs.length)` into a class call without `new`.
            Builtin::AbsFloat => format!("globalThis.Math.abs({})", a(self, 0)),
            Builtin::MinInt => {
                let x = a(self, 0);
                let y = a(self, 1);
                format!("(({x}) < ({y}) ? ({x}) : ({y}))")
            }
            Builtin::MaxInt => {
                let x = a(self, 0);
                let y = a(self, 1);
                format!("(({x}) > ({y}) ? ({x}) : ({y}))")
            }
            Builtin::MinFloat => format!("_rt.fmin({}, {})", a(self, 0), a(self, 1)),
            Builtin::MaxFloat => format!("_rt.fmax({}, {})", a(self, 0), a(self, 1)),
            Builtin::FloatOfInt => format!("globalThis.Number({})", a(self, 0)),
            Builtin::IntOfFloat => format!("_rt.int_of({})", a(self, 0)),
            Builtin::Floor => format!("_rt.floor({})", a(self, 0)),
            Builtin::Ceil => format!("_rt.ceil({})", a(self, 0)),
            Builtin::Round => format!("_rt.round_half_away({})", a(self, 0)),
            Builtin::Sqrt => format!("_rt.sqrt({})", a(self, 0)),
            Builtin::Filled => {
                let n = a(self, 0);
                let v = self.expr(&args[1], depth);
                format!("_rt.filled({n}, {v})")
            }
            Builtin::NewMap => "new _rt.SudoMap()".into(),
            Builtin::NewSet => "new _rt.SudoSet()".into(),
            Builtin::ListLength => {
                format!("globalThis.BigInt({}.length)", a_atom(self, 0))
            }
            Builtin::MapSize | Builtin::SetSize => {
                format!("globalThis.BigInt({}.size)", a_atom(self, 0))
            }
            Builtin::MapGet => format!("{}.get_opt({})", a_atom(self, 0), a(self, 1)),
            Builtin::MapHas => format!("{}.has({})", a_atom(self, 0), a(self, 1)),
            Builtin::MapKeys => format!("{}.keys_list()", a_atom(self, 0)),
            Builtin::MapValues => format!("{}.values_list()", a_atom(self, 0)),
            Builtin::SetHas => format!("{}.has({})", a_atom(self, 0), a(self, 1)),
            Builtin::SetItems => format!("{}.items_list()", a_atom(self, 0)),
            Builtin::OptIsSome => format!("_rt.is_some({})", a(self, 0)),
            Builtin::OptIsNone => format!("_rt.is_none({})", a(self, 0)),
            Builtin::OptUnwrap | Builtin::ResUnwrap => format!("_rt.unwrap({})", a(self, 0)),
            Builtin::OptGetOr | Builtin::ResGetOr => {
                format!("_rt.get_or({}, {})", a(self, 0), a(self, 1))
            }
            Builtin::ResIsOk => format!("_rt.is_ok({})", a(self, 0)),
            Builtin::ResIsErr => format!("_rt.is_err({})", a(self, 0)),
            _ => unreachable!("mutating builtin in non-mut position: {b:?}"),
        }
    }

    fn mut_builtin(
        &mut self,
        b: Builtin,
        recv: &Place,
        args: &[IrExpr],
        depth: usize,
    ) -> String {
        let r = self.place_expr(recv, depth);
        match b {
            Builtin::ListAppend => {
                let v = self.store(&args[0], depth);
                format!("{r}.push({v})")
            }
            Builtin::ListPop => format!("_rt.pop({r})"),
            Builtin::ListInsert => {
                let i = self.expr(&args[0], depth);
                let v = self.store(&args[1], depth);
                format!("_rt.insert({r}, {i}, {v})")
            }
            Builtin::ListRemoveAt => {
                let i = self.expr(&args[0], depth);
                format!("_rt.remove_at({r}, {i})")
            }
            Builtin::ListSwap => {
                let i = self.expr(&args[0], depth);
                let j = self.expr(&args[1], depth);
                format!("_rt.swap({r}, {i}, {j})")
            }
            Builtin::ListSort => format!("_rt.sort({r})"),
            Builtin::MapDelete => {
                let k = self.expr(&args[0], depth);
                format!("{r}.delete({k})")
            }
            Builtin::SetAdd => {
                let v = self.expr(&args[0], depth);
                format!("{r}.add({v})")
            }
            Builtin::SetRemove => {
                let v = self.expr(&args[0], depth);
                format!("{r}.remove({v})")
            }
            _ => unreachable!("non-mutating builtin in mut position: {b:?}"),
        }
    }

    fn line(&mut self, depth: usize, s: &str) {
        for _ in 0..depth {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) {
        self.out.push('\n');
    }
}

// ---- helpers ----------------------------------------------------------------

fn aliasing(kind: &IrExprKind) -> bool {
    match kind {
        IrExprKind::Local(_)
        | IrExprKind::Const(_)
        | IrExprKind::GetField { .. }
        | IrExprKind::Index { .. } => true,
        IrExprKind::Builtin { builtin, .. } => matches!(
            builtin,
            Builtin::OptUnwrap | Builtin::OptGetOr | Builtin::ResUnwrap | Builtin::ResGetOr
        ),
        _ => false,
    }
}

fn needs_dup(ty: &Ty) -> bool {
    match ty {
        Ty::List(_) | Ty::Map(..) | Ty::Set(_) | Ty::Record(_) => true,
        Ty::Tuple(ts) => ts.iter().any(needs_dup),
        _ => false,
    }
}

fn scalar_eq(ty: &Ty) -> bool {
    matches!(strip(ty), Ty::Int | Ty::Bool | Ty::Float)
}

fn strip(ty: &Ty) -> &Ty {
    ty
}

fn ret_parts(parts: &[String]) -> String {
    if parts.len() == 1 {
        parts[0].clone()
    } else {
        format!("[{}]", parts.join(", "))
    }
}

fn definitely_returns(stmts: &[IrStmt]) -> bool {
    stmts.iter().any(|s| match s {
        IrStmt::Return(_) => true,
        IrStmt::If { arms, else_block } => {
            else_block.as_ref().is_some_and(|e| definitely_returns(e))
                && arms.iter().all(|(_, b)| definitely_returns(b))
        }
        IrStmt::Match { arms, .. } => arms.iter().all(|a| definitely_returns(&a.body)),
        _ => false,
    })
}

fn js_float_lit(v: f64) -> String {
    if v.is_nan() {
        return "NaN".into();
    }
    if v.is_infinite() {
        return if v.is_sign_positive() {
            "Infinity".into()
        } else {
            "-Infinity".into()
        };
    }
    // Preserve negative zero.
    if v == 0.0 && v.is_sign_negative() {
        return "-0.0".into();
    }
    let s = format!("{v:?}");
    // Ensure a decimal form for integral floats so they stay floats in JS.
    if !s.contains('.') && !s.contains('e') && !s.contains('E') {
        format!("{s}.0")
    } else {
        s
    }
}

/// Build a double-quoted JS string literal from Unicode scalar values.
fn js_text_str(scalars: &[i64]) -> String {
    let mut s = String::from("\"");
    for &c in scalars {
        match char::from_u32(c as u32) {
            Some('"') => s.push_str("\\\""),
            Some('\\') => s.push_str("\\\\"),
            Some('\n') => s.push_str("\\n"),
            Some('\t') => s.push_str("\\t"),
            Some('\r') => s.push_str("\\r"),
            Some(ch) if (' '..='~').contains(&ch) => s.push(ch),
            Some(ch) if (ch as u32) <= 0xFFFF => {
                s.push_str(&format!("\\u{:04x}", ch as u32));
            }
            Some(ch) => s.push_str(&format!("\\u{{{:x}}}", ch as u32)),
            None => s.push_str("\\ufffd"),
        }
    }
    s.push('"');
    s
}

/// The JavaScript backend, via the SDK contract.
pub struct JsBackend;

impl sudoc_sdk::Backend for JsBackend {
    fn name(&self) -> &'static str {
        "js"
    }

    fn emit_program(
        &self,
        modules: &[IrModule],
        with_tests: bool,
    ) -> Result<Vec<sudoc_sdk::GeneratedFile>, String> {
        let (entry, deps) = modules.split_last().expect("entry module");
        let mut out = Vec::new();
        for m in deps {
            out.push(sudoc_sdk::GeneratedFile {
                path: impl_file(&m.name),
                contents: emit_with(m, modules, false),
            });
            if let Some(api) = emit_api(m) {
                out.push(sudoc_sdk::GeneratedFile {
                    path: api_file(&m.name),
                    contents: api,
                });
            }
        }
        out.push(sudoc_sdk::GeneratedFile {
            path: impl_file(&entry.name),
            contents: emit_with(entry, modules, with_tests),
        });
        if let Some(api) = emit_api(entry) {
            out.push(sudoc_sdk::GeneratedFile {
                path: api_file(&entry.name),
                contents: api,
            });
        }
        Ok(out)
    }

    fn runtime_files(&self) -> Vec<sudoc_sdk::GeneratedFile> {
        vec![sudoc_sdk::GeneratedFile {
            path: RUNTIME_FILE.into(),
            contents: RUNTIME.into(),
        }]
    }

    fn test_recipe(&self, entry: &str) -> sudoc_sdk::TestRecipe {
        sudoc_sdk::TestRecipe {
            build: Vec::new(),
            run: vec!["node".into(), impl_file(entry)],
        }
    }
}
