//! C backend: typed IR -> readable C11 source.
//!
//! Strategy (lockstep.md §5.2):
//! - every sudo type maps to a concrete C type; generic instantiations
//!   (`List<int>`, `Option<(int, int)>`, …) are monomorphized into named structs
//!   with generated `_copy` / `_free` / `_eq` (and `_hash` for key types);
//! - value semantics by ownership: every local owns its value; assignment
//!   copies aliasing reads; scope exit frees; early `return` frees all live
//!   locals after materializing the return value;
//! - composite-valued subexpressions are materialized into named temporaries,
//!   freed at statement end unless moved into storage;
//! - `inout` is a plain pointer parameter — the native writeback;
//! - enum variant payload fields of record/enum/Option/Result/tuple kind are
//!   heap-boxed, which is also what makes recursive enums finite;
//! - traps set a global status and `longjmp` to the test-harness / boundary
//!   `setjmp`; v1 leaks allocations on trap (tracking arena is future work);
//! - integer arithmetic wraps via unsigned helpers — no `-fwrapv` needed.

mod boundary;
mod code_gen;
mod program;
mod types_gen;

pub use boundary::emit_header;
pub use program::{emit_program, merge};

use std::fmt::Write;

use sudoc_ir::{BinaryOp, IrExpr, IrExprKind, IrModule, UnaryOp};

/// Shared C runtime, written alongside generated modules.
pub const RUNTIME_H: &str = include_str!("runtime/sudo_rt.h");
pub const RUNTIME_C: &str = include_str!("runtime/sudo_rt.c");
pub const RUNTIME_H_FILE: &str = "sudo_rt.h";
pub const RUNTIME_C_FILE: &str = "sudo_rt.c";

/// Emit a self-contained C translation unit for the IR. With `with_tests`,
/// test blocks become functions plus a TAP-printing `main`.
pub fn emit(module: &IrModule, with_tests: bool) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "/* Generated by sudoc from {}.sudo — do not edit; edit the sudo source. */",
        module.name
    );
    let _ = writeln!(out, "#include \"sudo_rt.h\"");
    let _ = writeln!(out);

    // Types.
    let set = types_gen::collect(module);
    types_gen::emit_types(module, &set, &mut out);
    let _ = writeln!(out);

    // Constants (scalar; folded so they are C constant expressions).
    for c in &module.consts {
        let _ = writeln!(
            out,
            "static const {} {} = {};",
            types_gen::c_type(&c.ty),
            c.name,
            fold_const(&c.value, module)
        );
    }
    if !module.consts.is_empty() {
        let _ = writeln!(out);
    }

    // Function prototypes, then bodies. Exports with host wrappers become
    // static — the wrapper is the public symbol.
    let wrapped = boundary::wrapped_exports(module);
    for f in &module.funcs {
        let ret = f.ret.as_ref().map(types_gen::c_type).unwrap_or_else(|| "void".into());
        let linkage =
            if f.export && !wrapped.contains(&f.name) { "" } else { "SUDO_UNUSED static " };
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                if p.inout {
                    format!("{} *{}", types_gen::c_type(&p.ty), p.name)
                } else {
                    format!("{} {}", types_gen::c_type(&p.ty), p.name)
                }
            })
            .collect();
        let args = if params.is_empty() { "void".to_string() } else { params.join(", ") };
        let _ = writeln!(out, "{linkage}{ret} {}({args});", f.name);
    }
    let _ = writeln!(out);
    for f in &module.funcs {
        let mut em = code_gen::FnEmitter::new(module, &mut out);
        em.set_static_export(wrapped.contains(&f.name));
        em.emit_func(f);
    }
    boundary::emit_wrappers(module, &mut out);

    if with_tests {
        let names = sudoc_ir::names::test_fn_names(&module.tests);
        for (t, name) in module.tests.iter().zip(&names) {
            let mut em = code_gen::FnEmitter::new(module, &mut out);
            em.emit_test(t, name);
        }
        let _ = writeln!(out, "int main(void) {{");
        let _ = writeln!(out, "    struct {{ const char *name; void (*fn)(void); }} tests[] = {{");
        for name in &names {
            let _ = writeln!(out, "        {{\"{name}\", {name}}},");
        }
        let _ = writeln!(out, "    }};");
        let _ = writeln!(out, "    int count = (int)(sizeof(tests) / sizeof(tests[0]));");
        let _ = writeln!(out, "    volatile int failures = 0;");
        let _ = writeln!(out, "    for (volatile int i = 0; i < count; i++) {{");
        let _ = writeln!(out, "        sudo_det_reset();");
        let _ = writeln!(out, "        if (setjmp(sudo_trap_jmp) == 0) {{");
        let _ = writeln!(out, "            tests[i].fn();");
        let _ = writeln!(out, "            printf(\"ok %d - %s\\n\", i + 1, tests[i].name);");
        let _ = writeln!(out, "        }} else if (sudo_trap_detail[0]) {{");
        let _ = writeln!(out, "            failures++;");
        let _ = writeln!(
            out,
            "            printf(\"not ok %d - %s [%s: %s]\\n\", i + 1, tests[i].name, sudo_status_name(sudo_trap_status), sudo_trap_detail);"
        );
        let _ = writeln!(out, "        }} else {{");
        let _ = writeln!(out, "            failures++;");
        let _ = writeln!(
            out,
            "            printf(\"not ok %d - %s [%s]\\n\", i + 1, tests[i].name, sudo_status_name(sudo_trap_status));"
        );
        let _ = writeln!(out, "        }}");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "    printf(\"# %d/%d passed\\n\", count - failures, count);");
        let _ = writeln!(out, "    return failures ? 1 : 0;");
        let _ = writeln!(out, "}}");
    }
    out
}

/// Module constants are restricted to scalar constant expressions; fold them
/// in the compiler so the C initializer is a constant expression.
fn fold_const(e: &IrExpr, m: &IrModule) -> String {
    #[derive(Clone, Copy)]
    enum V {
        I(i64),
        F(f64),
        B(bool),
    }
    fn go(e: &IrExpr, m: &IrModule) -> V {
        match &e.kind {
            IrExprKind::Int(v) => V::I(*v),
            IrExprKind::Float(v) => V::F(*v),
            IrExprKind::Bool(v) => V::B(*v),
            IrExprKind::Const(n) => {
                let c = m.consts.iter().find(|c| c.name == *n).expect("const exists");
                go(&c.value, m)
            }
            IrExprKind::Unary { op: UnaryOp::Neg, operand } => match go(operand, m) {
                V::I(v) => V::I(v.wrapping_neg()),
                V::F(v) => V::F(-v),
                V::B(_) => unreachable!(),
            },
            IrExprKind::Binary { op, lhs, rhs } => {
                let (l, r) = (go(lhs, m), go(rhs, m));
                match (l, r) {
                    (V::I(a), V::I(b)) => V::I(match op {
                        BinaryOp::Add => a.wrapping_add(b),
                        BinaryOp::Sub => a.wrapping_sub(b),
                        BinaryOp::Mul => a.wrapping_mul(b),
                        // Floor division/modulo per spec §4.1 (not Euclidean).
                        BinaryOp::Div => {
                            let q = a.wrapping_div(b);
                            if a % b != 0 && (a < 0) != (b < 0) {
                                q - 1
                            } else {
                                q
                            }
                        }
                        BinaryOp::Mod => {
                            let r = a % b;
                            if r != 0 && (r < 0) != (b < 0) {
                                r + b
                            } else {
                                r
                            }
                        }
                        _ => unreachable!(),
                    }),
                    (V::F(a), V::F(b)) => V::F(match op {
                        BinaryOp::Add => a + b,
                        BinaryOp::Sub => a - b,
                        BinaryOp::Mul => a * b,
                        BinaryOp::Div => a / b,
                        _ => unreachable!(),
                    }),
                    _ => unreachable!(),
                }
            }
            _ => unreachable!("checker restricts const exprs"),
        }
    }
    match go(e, m) {
        V::I(v) if v == i64::MIN => "INT64_MIN".into(),
        V::I(v) => format!("{v}LL"),
        V::F(v) => format!("{v:?}"),
        V::B(v) => if v { "true" } else { "false" }.into(),
    }
}

/// The reference C backend, via the SDK contract.
pub struct CBackend;

impl sudoc_sdk::Backend for CBackend {
    fn name(&self) -> &'static str {
        "c"
    }

    fn emit_program(
        &self,
        modules: &[IrModule],
        with_tests: bool,
    ) -> Vec<sudoc_sdk::GeneratedFile> {
        let merged = merge(modules);
        let mut out = vec![sudoc_sdk::GeneratedFile {
            path: format!("{}.c", merged.name),
            contents: emit(&merged, with_tests),
        }];
        if let Some(h) = emit_header(&merged) {
            out.push(sudoc_sdk::GeneratedFile {
                path: format!("{}.h", merged.name),
                contents: h,
            });
        }
        out
    }

    fn runtime_files(&self) -> Vec<sudoc_sdk::GeneratedFile> {
        vec![
            sudoc_sdk::GeneratedFile { path: RUNTIME_H_FILE.into(), contents: RUNTIME_H.into() },
            sudoc_sdk::GeneratedFile { path: RUNTIME_C_FILE.into(), contents: RUNTIME_C.into() },
        ]
    }

    fn test_recipe(&self, entry: &str) -> sudoc_sdk::TestRecipe {
        sudoc_sdk::TestRecipe {
            build: vec![vec![
                "cc".into(),
                "-std=c11".into(),
                "-O1".into(),
                "-o".into(),
                "sudo_tests".into(),
                format!("{entry}.c"),
                RUNTIME_C_FILE.into(),
            ]],
            run: vec!["./sudo_tests".into()],
        }
    }
}
