"""Module extension: fetches pinned sudoc release binaries and exposes a
single platform-selected executable target, @sudo_toolchain//:sudoc.

v1 ships a hub-alias (repository_rule + config_setting + select), not full
toolchain_type/register_toolchains resolution — see README.md "toolchain
shipping shape" for why this is an acceptable v1 tradeoff.

Precedence: if any module in the dependency graph declares
`sudo.local_binary(path = ...)`, that local path wins unconditionally and
no release binaries are downloaded at all (see README.md "local dev
override" for the documented rationale and usage).

v1 limitation: if two modules in the graph declare
`sudo.toolchain(version = ...)` with different versions, the loop below
takes whichever tag `module_ctx.modules` visits last (order not guaranteed
stable across complex graphs) — acceptable for v1 since there's no BCR
entry yet and the only realistic consumers (rules_sudo's own self-reference,
and e2e/) agree on one version.

`sudo.toolchain` also accepts an optional `sha256s` string_dict keyed by
release asset TRIPLE (e.g. "aarch64-apple-darwin"), not platform_key. For
each platform, a triple named in `sha256s` wins over the
SUDO_TOOLCHAIN_VERSIONS pin for the resolved version; triples not named
still fall back to versions.bzl. This lets consumers pin a newer sudoc
release than versions.bzl knows about yet, without editing the ruleset.
"""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load(":versions.bzl", "PLATFORM_TRIPLES", "SUDO_TOOLCHAIN_VERSIONS")

_RELEASE_URL = "https://github.com/hacker6284/sudocode/releases/download/{version}/sudoc-{triple}"

def _hub_impl(rctx):
    if rctx.attr.local_path:
        rctx.symlink(rctx.attr.local_path, "sudoc_local")
        rctx.file("BUILD.bazel", '''# Generated by the rules_sudo "sudo" module extension.
# sudo.local_binary(path = ...) is active: this alias points at the local
# path unconditionally, bypassing the platform select below.
alias(
    name = "sudoc",
    actual = ":sudoc_local",
    visibility = ["//visibility:public"],
)
exports_files(["sudoc_local"])
''')
        return

    rctx.symlink(rctx.attr.macos_arm64, "sudoc_macos_arm64")
    rctx.symlink(rctx.attr.linux_x86_64, "sudoc_linux_x86_64")
    rctx.symlink(rctx.attr.linux_aarch64, "sudoc_linux_aarch64")
    rctx.file("BUILD.bazel", '''# Generated by the rules_sudo "sudo" module extension.
config_setting(
    name = "macos_arm64",
    constraint_values = ["@platforms//os:macos", "@platforms//cpu:arm64"],
)
config_setting(
    name = "linux_x86_64",
    constraint_values = ["@platforms//os:linux", "@platforms//cpu:x86_64"],
)
config_setting(
    name = "linux_aarch64",
    constraint_values = ["@platforms//os:linux", "@platforms//cpu:arm64"],
)
alias(
    name = "sudoc",
    actual = select({
        ":macos_arm64": ":sudoc_macos_arm64",
        ":linux_x86_64": ":sudoc_linux_x86_64",
        ":linux_aarch64": ":sudoc_linux_aarch64",
    }),
    visibility = ["//visibility:public"],
)
exports_files(["sudoc_macos_arm64", "sudoc_linux_x86_64", "sudoc_linux_aarch64"])
''')

_sudo_hub = repository_rule(
    implementation = _hub_impl,
    attrs = {
        "macos_arm64": attr.label(allow_single_file = True),
        "linux_x86_64": attr.label(allow_single_file = True),
        "linux_aarch64": attr.label(allow_single_file = True),
        "local_path": attr.string(),
    },
)

def _sudo_extension_impl(module_ctx):
    version = None
    local_path = None
    # triple -> sha256; last-write-wins across modules (same rule as version).
    # A later tag's keys overwrite earlier ones; keys not mentioned by a
    # later tag keep whatever an earlier tag set.
    sha256_overrides = {}

    # Last-write-wins across modules; see module docstring for v1 limitation.
    for mod in module_ctx.modules:
        for tag in mod.tags.toolchain:
            version = tag.version
            for triple, sha in tag.sha256s.items():
                sha256_overrides[triple] = sha
        for tag in mod.tags.local_binary:
            local_path = tag.path

    if local_path:
        _sudo_hub(name = "sudo_toolchain", local_path = local_path)
        return

    if version == None:
        version = "v0.1.0"

    # .get so an unknown version is valid when sha256s covers every platform.
    version_manifest = SUDO_TOOLCHAIN_VERSIONS.get(version, {})

    platform_repos = {}
    for platform_key, triple in PLATFORM_TRIPLES.items():
        sha256 = sha256_overrides.get(triple)
        if sha256 == None:
            sha256 = version_manifest.get(platform_key)
        if sha256 == None:
            fail(
                ("rules_sudo: no sha256 for platform {pk} (triple {tr}) " +
                 "at version {ver}. Either pin it in versions.bzl or pass " +
                 "sha256s on sudo.toolchain, e.g.:\n" +
                 "  sudo.toolchain(\n" +
                 "      version = \"{ver}\",\n" +
                 "      sha256s = {{\"{tr}\": \"<sha256>\"}},\n" +
                 "  )").format(
                    pk = platform_key,
                    tr = triple,
                    ver = version,
                ),
            )
        repo_name = "sudo_bin_" + platform_key
        http_file(
            name = repo_name,
            executable = True,
            sha256 = sha256,
            urls = [_RELEASE_URL.format(version = version, triple = triple)],
        )
        platform_repos[platform_key] = "@{}//file:downloaded".format(repo_name)

    _sudo_hub(
        name = "sudo_toolchain",
        macos_arm64 = platform_repos["macos_arm64"],
        linux_x86_64 = platform_repos["linux_x86_64"],
        linux_aarch64 = platform_repos["linux_aarch64"],
    )

# version: release tag (e.g. "v0.1.0").
# sha256s: optional map of release-asset TRIPLE -> sha256 hex. Override wins
# for any triple it names; other triples still fall back to versions.bzl for
# the resolved version. Keys must be triples (PLATFORM_TRIPLES values), not
# platform_key names like "macos_arm64".
_toolchain_tag = tag_class(attrs = {
    "version": attr.string(default = "v0.1.0"),
    "sha256s": attr.string_dict(default = {}),
})

_local_binary_tag = tag_class(attrs = {
    "path": attr.string(mandatory = True),
})

sudo = module_extension(
    implementation = _sudo_extension_impl,
    tag_classes = {
        "toolchain": _toolchain_tag,
        "local_binary": _local_binary_tag,
    },
)
