"""Module extension: fetches the pinned sudoc release toolchain (a MATCHED SET —
`sudoc` plus the harness tools `lockstep_diff` / `capture_run` / `emit_unpack`)
and exposes each as a platform-selected executable target under
`@sudo_toolchain//:<asset>`.

v1 ships a hub-alias (repository_rule + config_setting + select), not full
toolchain_type/register_toolchains resolution — see README.md "toolchain
shipping shape" for why this is an acceptable v1 tradeoff.

Precedence: if any module in the dependency graph declares
`sudo.local_binary(sudoc = ..., lockstep_diff = ..., ...)`, those local paths win
unconditionally and no release binaries are downloaded at all. This is the
pre-release dogfood mechanism: point the ruleset at freshly-built HEAD binaries
(exactly how sudocode overrides the macro attrs, and how infinite-craft-cli
validates against HEAD before a release — design §8 Phase 5 Task 8).

Phase 5 (rules_sudo 1.0.0): the hermetic decomposed `sudo_lockstep_test` needs
the whole matched set, so the extension fetches/symlinks every asset a release
publishes (not just `sudoc`) and the run-time handshake in the test launcher
rejects a mispaired toolchain. Pre-Task-8 releases publish only `sudoc`; the
other assets are fetched once versions.bzl pins their sha256s.

`sudo.toolchain` also accepts an optional `sha256s` string_dict keyed by release
asset TRIPLE (e.g. "aarch64-apple-darwin"), which pins the `sudoc` asset for the
resolved version even when versions.bzl doesn't know it yet. (Bare triples map to
`sudoc`; use "<asset>/<triple>" to pin another asset.)
"""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load(":versions.bzl", "PLATFORM_TRIPLES", "RELEASE_ASSETS", "SUDO_TOOLCHAIN_VERSIONS")

_RELEASE_URL = "https://github.com/hacker6284/sudocode/releases/download/{version}/{asset}-{triple}"

_CONFIG_SETTINGS = '''config_setting(
    name = "macos_arm64",
    constraint_values = ["@platforms//os:macos", "@platforms//cpu:arm64"],
)
config_setting(
    name = "linux_x86_64",
    constraint_values = ["@platforms//os:linux", "@platforms//cpu:x86_64"],
)
config_setting(
    name = "linux_aarch64",
    constraint_values = ["@platforms//os:linux", "@platforms//cpu:arm64"],
)
'''

def _hub_impl(rctx):
    # Local-override mode: symlink each provided binary, alias by asset name.
    if rctx.attr.local_binaries:
        lines = [
            '# Generated by the rules_sudo "sudo" module extension.',
            "# sudo.local_binary(...) is active: these aliases point at local",
            "# paths unconditionally, bypassing any release fetch.",
        ]
        exported = []
        for name, path in rctx.attr.local_binaries.items():
            link = name + "_local"
            rctx.symlink(path, link)
            exported.append(link)
            lines.append('alias(name = "%s", actual = ":%s", visibility = ["//visibility:public"])' % (name, link))
        lines.append("exports_files(%s)" % repr(exported))
        rctx.file("BUILD.bazel", "\n".join(lines) + "\n")
        return

    # Release mode: rctx.attr.binaries maps an http_file label -> "asset|platform".
    by_asset = {}
    for label, tag in rctx.attr.binaries.items():
        asset, platform = tag.split("|")
        link = "%s_%s" % (asset, platform)
        rctx.symlink(label, link)
        by_asset.setdefault(asset, {})[platform] = link

    lines = ['# Generated by the rules_sudo "sudo" module extension.', _CONFIG_SETTINGS]
    exported = []
    for asset, plats in by_asset.items():
        select_entries = "".join(
            ['        ":%s": ":%s",\n' % (p, link) for p, link in plats.items()],
        )
        lines.append('''alias(
    name = "{asset}",
    actual = select({{
{entries}    }}),
    visibility = ["//visibility:public"],
)'''.format(asset = asset, entries = select_entries))
        exported.extend(plats.values())
    lines.append("exports_files(%s)" % repr(exported))
    rctx.file("BUILD.bazel", "\n".join(lines) + "\n")

_sudo_hub = repository_rule(
    implementation = _hub_impl,
    attrs = {
        # Release mode: {http_file label: "asset|platform_key"}.
        "binaries": attr.label_keyed_string_dict(allow_files = True),
        # Local-override mode: {asset name: absolute path}.
        "local_binaries": attr.string_dict(),
    },
)

def _parse_sha_key(key):
    """A sha256s override key is "<asset>/<triple>", or a bare "<triple>"
    (back-compat) meaning the `sudoc` asset."""
    if "/" in key:
        asset, triple = key.split("/", 1)
        return asset, triple
    return "sudoc", key

def _sudo_extension_impl(module_ctx):
    version = None
    local_binaries = {}
    sha_overrides = {}  # (asset, triple) -> sha256

    # ROOT-MODULE-WINS: the consumer's tags take absolute precedence over any
    # dependency module's (including rules_sudo's own self-invocation). Non-root
    # tags only fill in what the root left unset.
    mods = sorted(module_ctx.modules, key = lambda m: 0 if m.is_root else 1)
    for mod in mods:
        for tag in mod.tags.toolchain:
            if version == None:
                version = tag.version
            for key, sha in tag.sha256s.items():
                asset, triple = _parse_sha_key(key)
                if (asset, triple) not in sha_overrides:
                    sha_overrides[(asset, triple)] = sha
        for tag in mod.tags.local_binary:
            for name, path in _local_binary_paths(tag).items():
                if name not in local_binaries:
                    local_binaries[name] = path

    if local_binaries:
        _sudo_hub(name = "sudo_toolchain", local_binaries = local_binaries)
        return

    if version == None:
        version = "v0.1.0"
    version_manifest = SUDO_TOOLCHAIN_VERSIONS.get(version, {})

    binaries = {}
    for asset in RELEASE_ASSETS:
        asset_manifest = version_manifest.get(asset, {})
        for platform_key, triple in PLATFORM_TRIPLES.items():
            sha256 = sha_overrides.get((asset, triple))
            if sha256 == None:
                sha256 = asset_manifest.get(platform_key)
            if sha256 == None:
                # `sudoc` is mandatory; the harness tools are optional until the
                # matched-pair release pins them (Task 8). A missing optional
                # asset is simply not exposed — referencing it then fails loudly.
                if asset == "sudoc":
                    fail(
                        ("rules_sudo: no sha256 for sudoc on platform {pk} " +
                         "(triple {tr}) at version {ver}. Pin it in versions.bzl " +
                         "or pass sha256s on sudo.toolchain, e.g.:\n" +
                         "  sudo.toolchain(version = \"{ver}\", sha256s = {{\"{tr}\": \"<sha256>\"}})").format(
                            pk = platform_key,
                            tr = triple,
                            ver = version,
                        ),
                    )
                continue
            repo_name = "sudo_bin_%s_%s" % (asset, platform_key)
            http_file(
                name = repo_name,
                executable = True,
                sha256 = sha256,
                urls = [_RELEASE_URL.format(version = version, asset = asset, triple = triple)],
            )
            binaries["@%s//file:downloaded" % repo_name] = "%s|%s" % (asset, platform_key)

    _sudo_hub(name = "sudo_toolchain", binaries = binaries)

def _local_binary_paths(tag):
    """The non-empty {asset: path} a local_binary tag declares."""
    out = {}
    if tag.sudoc:
        out["sudoc"] = tag.sudoc
    if tag.lockstep_diff:
        out["lockstep_diff"] = tag.lockstep_diff
    if tag.capture_run:
        out["capture_run"] = tag.capture_run
    if tag.emit_unpack:
        out["emit_unpack"] = tag.emit_unpack
    if tag.path:
        # Back-compat: the pre-1.0 single `path` attr meant sudoc.
        out.setdefault("sudoc", tag.path)
    return out

# version: release tag (e.g. "v0.1.0").
# sha256s: optional map of "<triple>" (→ sudoc) or "<asset>/<triple>" -> sha256
# hex. An override wins for the asset+triple it names; others fall back to
# versions.bzl for the resolved version.
_toolchain_tag = tag_class(attrs = {
    "version": attr.string(default = "v0.1.0"),
    "sha256s": attr.string_dict(default = {}),
})

# Local-override: point the ruleset at freshly-built HEAD binaries. Any subset
# may be set; `sudoc` alone is enough for the codegen-only rules, the hermetic
# lockstep needs the matched set. `path` is the retired pre-1.0 sudoc-only alias.
_local_binary_tag = tag_class(attrs = {
    "sudoc": attr.string(default = ""),
    "lockstep_diff": attr.string(default = ""),
    "capture_run": attr.string(default = ""),
    "emit_unpack": attr.string(default = ""),
    "path": attr.string(default = ""),
})

sudo = module_extension(
    implementation = _sudo_extension_impl,
    tag_classes = {
        "toolchain": _toolchain_tag,
        "local_binary": _local_binary_tag,
    },
)
