//! Python backend: typed IR -> readable Python 3.10+ source.
//!
//! Value semantics strategy (lockstep.md §5.1):
//! - non-inout composite parameters are defensively copied at function entry;
//! - aliasing reads (variables, fields, indexing, unwraps) are deep-copied at
//!   storing positions (assignment RHS, constructor args, container inserts,
//!   returns); enums and Option/Result share safely because nothing can
//!   mutate them in place — their payloads are copied on extraction instead;
//! - inout parameters are threaded through return values: every function
//!   returns `(ret?, *inouts)` and call sites reassign — `n = bump(n)`;
//! - deep equality goes through `_rt.eq` (Python's own list equality takes an
//!   identity shortcut that breaks IEEE NaN semantics).

use sudoc_ir::{
    BinaryOp, Builtin, IrExpr, IrExprKind, IrFunc, IrModule, IrPattern, IrStmt, Place, Ty,
    UnaryOp,
};

/// The shared Python runtime, written alongside every generated module.
pub const RUNTIME: &str = include_str!("runtime/_sudo_rt.py");
pub const RUNTIME_FILE: &str = "_sudo_rt.py";

/// File name of the internal implementation module.
pub fn impl_file(module: &str) -> String {
    format!("_{module}_impl.py")
}

/// File name of the host-facing API module (only emitted when exports exist).
pub fn api_file(module: &str) -> String {
    format!("{module}.py")
}

/// Emit a Python module for the IR. When `with_tests` is set, `test` blocks
/// become `test_*` functions plus a `__main__` runner that executes them.
pub fn emit(module: &IrModule, with_tests: bool) -> String {
    emit_with(module, std::slice::from_ref(module), with_tests)
}

/// Emit `module`, resolving cross-module callee signatures (inout-taking
/// functions in particular) against `all_modules` — the whole program,
/// not just `module` itself. `emit_program` calls this with the real
/// program; `emit` (single-module callers, back-compat) passes a
/// one-element slice.
fn emit_with(module: &IrModule, all_modules: &[IrModule], with_tests: bool) -> String {
    Emitter { m: module, all: all_modules, out: String::new() }.run(with_tests)
}

struct Emitter<'a> {
    m: &'a IrModule,
    /// Every module in the program, for cross-module callee lookup.
    all: &'a [IrModule],
    out: String,
}

impl Emitter<'_> {
    /// Resolve a callee's signature across the whole program: a bare name
    /// looks in the current module; a `module.func` qualified name looks up
    /// the named module in `self.all`. Mirrors the Haskell backend's
    /// `lookupFunc`/`splitQual` (backends/haskell/Emit.hs).
    fn resolve_func(&self, name: &str) -> Option<&IrFunc> {
        match name.split_once('.') {
            Some((modname, fname)) => self.all.iter().find(|m| m.name == modname)?.func(fname),
            None => self.m.func(name),
        }
    }

    fn run(mut self, with_tests: bool) -> String {
        self.line(0, &format!("# Generated by sudoc from {}.sudo — do not edit; edit the sudo source.", self.m.name));
        self.line(0, "from __future__ import annotations");
        if !self.m.records.is_empty() || !self.m.enums.is_empty() {
            self.line(0, "from dataclasses import dataclass");
        }
        self.line(0, "import _sudo_rt as _rt");
        for dep in &self.m.imports {
            self.line(0, &format!("import _{dep}_impl as {dep}"));
        }
        self.blank();

        for r in &self.m.records {
            self.line(0, "@dataclass");
            self.line(0, &format!("class {}:", r.name));
            self.line(1, &format!("_sudo_kind = (\"r\", \"{}\")", r.name));
            for (fname, fty) in &r.fields {
                self.line(1, &format!("{fname}: {}", py_ty(fty)));
            }
            self.blank();
        }
        for e in &self.m.enums {
            for v in &e.variants {
                self.line(0, "@dataclass");
                self.line(0, &format!("class {}_{}:", e.name, v.name));
                self.line(1, &format!("_sudo_kind = (\"e\", \"{}.{}\")", e.name, v.name));
                for (fname, fty) in &v.fields {
                    self.line(1, &format!("{fname}: {}", py_ty(fty)));
                }
                self.blank();
            }
            let union: Vec<String> =
                e.variants.iter().map(|v| format!("{}_{}", e.name, v.name)).collect();
            self.line(0, &format!("{} = {}", e.name, union.join(" | ")));
            self.blank();
        }
        for c in &self.m.consts {
            let value = self.expr(&c.value, 0);
            self.line(0, &format!("{} = {}", c.name, value));
        }
        if !self.m.consts.is_empty() {
            self.blank();
        }

        for f in &self.m.funcs {
            self.func(f);
            self.blank();
        }

        if with_tests {
            let names = sudoc_ir::names::test_fn_names(&self.m.tests);
            for (t, name) in self.m.tests.iter().zip(&names) {
                self.line(0, &format!("def {name}():"));
                if t.body.is_empty() {
                    self.line(1, "pass");
                } else {
                    self.block(&t.body, 1, &[]);
                }
                self.blank();
            }
            self.line(0, "if __name__ == \"__main__\":");
            self.line(1, "import sys");
            self.line(1, "sys.exit(_rt.run_tests(globals()))");
        }
        self.out
    }

    fn func(&mut self, f: &IrFunc) {
        let params: Vec<&str> = f.params.iter().map(|p| p.name.as_str()).collect();
        self.line(0, &format!("def {}({}):", f.name, params.join(", ")));
        for p in &f.params {
            if !p.inout && needs_dup(&p.ty) {
                self.line(1, &format!("{0} = _rt.dup({0})", p.name));
            }
        }
        let inouts: Vec<String> =
            f.params.iter().filter(|p| p.inout).map(|p| p.name.clone()).collect();
        if f.body.is_empty() && inouts.is_empty() {
            self.line(1, "pass");
            return;
        }
        self.block(&f.body, 1, &inouts);
        if !definitely_returns(&f.body) && !inouts.is_empty() {
            self.line(1, &format!("return {}", tuple_of(&inouts)));
        }
    }

    fn block(&mut self, stmts: &[IrStmt], depth: usize, inouts: &[String]) {
        for s in stmts {
            self.stmt(s, depth, inouts);
        }
    }

    fn stmt(&mut self, s: &IrStmt, depth: usize, inouts: &[String]) {
        match s {
            IrStmt::Assign { target, value, .. } => {
                if let Some(call) = self.as_inout_call(value) {
                    self.emit_inout_call(Some(target), call, depth);
                    return;
                }
                let v = self.store(value, depth);
                self.assign_to_place(target, &v, depth);
            }
            IrStmt::TupleAssign { targets, value, .. } => {
                let v = self.store(value, depth);
                self.line(depth, &format!("{} = {}", targets.join(", "), v));
            }
            IrStmt::Expr(e) => {
                if let Some(call) = self.as_inout_call(e) {
                    self.emit_inout_call(None, call, depth);
                    return;
                }
                let code = self.expr(e, depth);
                self.line(depth, &code);
            }
            IrStmt::If { arms, else_block } => {
                for (i, (cond, body)) in arms.iter().enumerate() {
                    let kw = if i == 0 { "if" } else { "elif" };
                    let c = self.expr(cond, depth);
                    self.line(depth, &format!("{kw} {c}:"));
                    self.block_or_pass(body, depth + 1, inouts);
                }
                if let Some(body) = else_block {
                    self.line(depth, "else:");
                    self.block_or_pass(body, depth + 1, inouts);
                }
            }
            IrStmt::While { cond, body } => {
                let c = self.expr(cond, depth);
                self.line(depth, &format!("while {c}:"));
                self.block_or_pass(body, depth + 1, inouts);
            }
            IrStmt::ForRange { var, from, to, down, body } => {
                let f = self.expr(from, depth);
                let t = self.expr_prec(to, 6, depth);
                let range = if *down {
                    format!("range({f}, {t} - 1, -1)")
                } else {
                    format!("range({f}, {t} + 1)")
                };
                self.line(depth, &format!("for {var} in {range}:"));
                self.block_or_pass(body, depth + 1, inouts);
            }
            IrStmt::ForIn { vars, iter, body } => {
                let it = self.expr(iter, depth);
                let iterable = match strip(&iter.ty) {
                    Ty::List(_) => format!("list({it})"),
                    Ty::Set(_) => format!("{it}.items_list()"),
                    Ty::Map(..) => format!("{it}.pairs()"),
                    _ => it,
                };
                self.line(depth, &format!("for {} in {iterable}:", vars.join(", ")));
                self.block_or_pass(body, depth + 1, inouts);
            }
            IrStmt::Match { scrutinee, arms } => {
                let sc = self.expr(scrutinee, depth);
                self.line(depth, &format!("match {sc}:"));
                for arm in arms {
                    let pat = self.pattern(&arm.pattern);
                    self.line(depth + 1, &format!("case {pat}:"));
                    // Copy composite binders: they alias the matched payload.
                    let mut emitted = 0;
                    if let IrPattern::Variant { enum_name, variant, binders } = &arm.pattern {
                        for (i, b) in binders.iter().enumerate() {
                            if let Some(ty) = self.variant_field_ty(enum_name, variant, i) {
                                if needs_dup(&ty) {
                                    self.line(depth + 2, &format!("{b} = _rt.dup({b})"));
                                    emitted += 1;
                                }
                            }
                        }
                    }
                    if arm.body.is_empty() && emitted == 0 {
                        self.line(depth + 2, "pass");
                    } else {
                        self.block(&arm.body, depth + 2, inouts);
                    }
                }
            }
            IrStmt::Return(v) => {
                let mut parts: Vec<String> = Vec::new();
                if let Some(v) = v {
                    parts.push(self.store(v, depth));
                }
                parts.extend(inouts.iter().cloned());
                if parts.is_empty() {
                    self.line(depth, "return");
                } else {
                    self.line(depth, &format!("return {}", parts.join(", ")));
                }
            }
            IrStmt::Assert { cond, line } => {
                // Equality asserts serialize their operands on failure
                // (harness diagnostics, lockstep.md §3).
                if let IrExprKind::Binary { op: BinaryOp::Eq, lhs, rhs } = &cond.kind {
                    let l = self.expr(lhs, depth);
                    let r = self.expr(rhs, depth);
                    self.line(depth, &format!("_rt.sudo_assert_eq({l}, {r}, {line})"));
                } else {
                    let c = self.expr(cond, depth);
                    self.line(depth, &format!("_rt.sudo_assert({c}, {line})"));
                }
            }
            IrStmt::Skip => self.line(depth, "pass"),
            IrStmt::Break => self.line(depth, "break"),
            IrStmt::Continue => self.line(depth, "continue"),
            IrStmt::ExpectTrap { kind, body, line } => {
                self.line(depth, "_trapped = False");
                self.line(depth, "try:");
                if body.is_empty() {
                    self.line(depth + 1, "pass");
                } else {
                    self.block(body, depth + 1, inouts);
                }
                self.line(depth, "except _rt.SudoTrap as _t:");
                self.line(depth + 1, "_trapped = True");
                self.line(depth + 1, &format!("if _t.kind != \"{kind}\":"));
                self.line(
                    depth + 2,
                    &format!("raise _rt.SudoTrap(\"AssertFailed\", f\"line {line}: expected trap {kind}, got {{_t.kind}}\")"),
                );
                self.line(depth, "if not _trapped:");
                self.line(
                    depth + 1,
                    &format!("raise _rt.SudoTrap(\"AssertFailed\", \"line {line}: expected trap {kind}, but nothing trapped\")"),
                );
            }
        }
    }

    fn block_or_pass(&mut self, stmts: &[IrStmt], depth: usize, inouts: &[String]) {
        if stmts.is_empty() {
            self.line(depth, "pass");
        } else {
            self.block(stmts, depth, inouts);
        }
    }

    /// A CallFunc whose callee has inout params (checker guarantees such
    /// calls only appear as statements or sole RHS).
    fn as_inout_call<'e>(&self, e: &'e IrExpr) -> Option<(&'e str, &'e [IrExpr])> {
        if let IrExprKind::CallFunc { name, args } = &e.kind {
            let f = self.resolve_func(name)?;
            if f.params.iter().any(|p| p.inout) {
                return Some((name, args));
            }
        }
        None
    }

    fn emit_inout_call(&mut self, target: Option<&Place>, (name, args): (&str, &[IrExpr]), depth: usize) {
        let f = self.resolve_func(name).expect("callee exists").clone();
        let mut arg_code = Vec::new();
        let mut writebacks = Vec::new();
        for (a, p) in args.iter().zip(&f.params) {
            let code = self.expr(a, depth);
            if p.inout {
                writebacks.push(code.clone());
            }
            arg_code.push(code);
        }
        let call = format!("{name}({})", arg_code.join(", "));
        let mut targets: Vec<String> = Vec::new();
        let mut indirect: Option<&Place> = None;
        if f.ret.is_some() {
            match target {
                Some(Place::Var(v)) => targets.push(v.clone()),
                Some(p) => {
                    targets.push("_sudo_r".into());
                    indirect = Some(p);
                }
                None => targets.push("_".into()),
            }
        }
        targets.extend(writebacks);
        self.line(depth, &format!("{} = {call}", targets.join(", ")));
        if let Some(p) = indirect {
            self.assign_to_place(p, "_sudo_r", depth);
        }
    }

    fn assign_to_place(&mut self, place: &Place, value: &str, depth: usize) {
        match place {
            Place::Var(n) => self.line(depth, &format!("{n} = {value}")),
            Place::Index { base, base_ty, index } => {
                let b = self.place_expr(base, depth);
                let i = self.expr(index, depth);
                match strip(base_ty) {
                    Ty::Map(..) => self.line(depth, &format!("{b}[{i}] = {value}")),
                    _ => self.line(depth, &format!("_rt.put({b}, {i}, {value})")),
                }
            }
            Place::Field { base, name, .. } => {
                let b = self.place_expr(base, depth);
                self.line(depth, &format!("{b}.{name} = {value}"));
            }
        }
    }

    /// A place used as an expression (receiver of a mutating method).
    fn place_expr(&mut self, place: &Place, depth: usize) -> String {
        match place {
            Place::Var(n) => n.clone(),
            Place::Index { base, base_ty, index } => {
                let b = self.place_expr(base, depth);
                let i = self.expr(index, depth);
                match strip(base_ty) {
                    Ty::Map(..) => format!("{b}[{i}]"),
                    _ => format!("_rt.at({b}, {i})"),
                }
            }
            Place::Field { base, name, .. } => {
                let b = self.place_expr(base, depth);
                format!("{b}.{name}")
            }
        }
    }

    fn variant_field_ty(&self, enum_name: &str, variant: &str, i: usize) -> Option<Ty> {
        let e = self.m.enum_(enum_name)?;
        let v = e.variants.iter().find(|v| v.name == variant)?;
        v.fields.get(i).map(|(_, t)| t.clone())
    }

    fn pattern(&self, p: &IrPattern) -> String {
        match p {
            IrPattern::Int(v) => format!("{v}"),
            IrPattern::Bool(v) => if *v { "True" } else { "False" }.to_string(),
            IrPattern::Wildcard => "_".into(),
            IrPattern::Variant { enum_name, variant, binders } => {
                let cls = match (enum_name.as_str(), variant.as_str()) {
                    ("Option", "Some") => "_rt.Some".to_string(),
                    ("Option", "None") => "_rt.NoneOpt".to_string(),
                    ("Result", "Ok") => "_rt.Ok".to_string(),
                    ("Result", "Err") => "_rt.Err".to_string(),
                    _ => format!("{enum_name}_{variant}"),
                };
                format!("{cls}({})", binders.join(", "))
            }
        }
    }

    /// Emit an expression for a *storing* position: aliasing reads of
    /// composite values are deep-copied.
    fn store(&mut self, e: &IrExpr, depth: usize) -> String {
        let code = self.expr(e, depth);
        if aliasing(&e.kind) && needs_dup(&e.ty) {
            format!("_rt.dup({code})")
        } else {
            code
        }
    }

    fn expr(&mut self, e: &IrExpr, depth: usize) -> String {
        self.expr_prec(e, 0, depth)
    }

    /// Emit with parentheses if this expression binds looser than `ctx`
    /// (Python precedence: or=1 and=2 not=3 cmp=4 add=5 mul=6 unary=7 atom=9).
    fn expr_prec(&mut self, e: &IrExpr, ctx: u8, depth: usize) -> String {
        let (code, prec) = self.expr_raw(e, depth);
        if prec < ctx {
            format!("({code})")
        } else {
            code
        }
    }

    fn expr_raw(&mut self, e: &IrExpr, depth: usize) -> (String, u8) {
        let atom = 9u8;
        match &e.kind {
            IrExprKind::Int(v) => (format!("{v}"), if *v < 0 { 7 } else { atom }),
            IrExprKind::Float(v) => {
                let s = format!("{v:?}");
                (s, if *v < 0.0 { 7 } else { atom })
            }
            IrExprKind::Bool(v) => (if *v { "True" } else { "False" }.into(), atom),
            IrExprKind::Text(s) => (format!("_rt.text({})", py_str(s)), atom),
            IrExprKind::Local(n) | IrExprKind::Const(n) | IrExprKind::FuncRef(n) => {
                (n.clone(), atom)
            }
            IrExprKind::List(xs) => {
                let items: Vec<String> = xs.iter().map(|x| self.store(x, depth)).collect();
                (format!("[{}]", items.join(", ")), atom)
            }
            IrExprKind::Tuple(xs) => {
                let items: Vec<String> = xs.iter().map(|x| self.store(x, depth)).collect();
                (format!("({})", items.join(", ")), atom)
            }
            IrExprKind::CallFunc { name, args } => {
                // Inout-passing calls never reach here nested (checker rule);
                // they are handled at statement level.
                let a: Vec<String> = args.iter().map(|x| self.expr(x, depth)).collect();
                (format!("{name}({})", a.join(", ")), atom)
            }
            IrExprKind::CallValue { callee, args } => {
                let c = self.expr_prec(callee, atom, depth);
                let a: Vec<String> = args.iter().map(|x| self.expr(x, depth)).collect();
                (format!("{c}({})", a.join(", ")), atom)
            }
            IrExprKind::NewRecord { name, args } => {
                let a: Vec<String> = args.iter().map(|x| self.store(x, depth)).collect();
                (format!("{name}({})", a.join(", ")), atom)
            }
            IrExprKind::NewVariant { enum_name, variant, args } => {
                let a: Vec<String> = args.iter().map(|x| self.store(x, depth)).collect();
                let code = match (enum_name.as_str(), variant.as_str()) {
                    ("Option", "Some") => format!("_rt.Some({})", a.join(", ")),
                    ("Option", "None") => "_rt.NONE".to_string(),
                    ("Result", "Ok") => format!("_rt.Ok({})", a.join(", ")),
                    ("Result", "Err") => format!("_rt.Err({})", a.join(", ")),
                    _ => format!("{enum_name}_{variant}({})", a.join(", ")),
                };
                (code, atom)
            }
            IrExprKind::Builtin { builtin, args } => (self.builtin(*builtin, args, depth), atom),
            IrExprKind::MutBuiltin { builtin, recv, args, .. } => {
                (self.mut_builtin(*builtin, recv, args, depth), atom)
            }
            IrExprKind::GetField { recv, name } => {
                let r = self.expr_prec(recv, atom, depth);
                (format!("{r}.{name}"), atom)
            }
            IrExprKind::Index { recv, index } => {
                let r = self.expr_prec(recv, atom, depth);
                let i = self.expr(index, depth);
                match strip(&recv.ty) {
                    Ty::Map(..) => (format!("{r}[{i}]"), atom),
                    _ => (format!("_rt.at({r}, {i})"), atom),
                }
            }
            IrExprKind::Unary { op, operand } => match op {
                UnaryOp::Neg => match strip(&e.ty) {
                    Ty::Int => {
                        let x = self.expr(operand, depth);
                        (format!("_rt.neg({x})"), atom)
                    }
                    _ => {
                        let x = self.expr_prec(operand, 7, depth);
                        (format!("-{x}"), 7)
                    }
                },
                UnaryOp::Not => {
                    let x = self.expr_prec(operand, 3, depth);
                    (format!("not {x}"), 3)
                }
            },
            IrExprKind::Binary { op, lhs, rhs } => self.binary(*op, lhs, rhs, &e.ty, depth),
        }
    }

    fn binary(
        &mut self,
        op: BinaryOp,
        lhs: &IrExpr,
        rhs: &IrExpr,
        result_ty: &Ty,
        depth: usize,
    ) -> (String, u8) {
        let is_int = matches!(strip(&lhs.ty), Ty::Int);
        let is_float = matches!(strip(&lhs.ty), Ty::Float);
        match op {
            BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul => {
                let sym = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    _ => "*",
                };
                let prec = if sym == "*" { 6 } else { 5 };
                if is_int {
                    let l = self.expr_prec(lhs, prec, depth);
                    let r = self.expr_prec(rhs, prec + 1, depth);
                    (format!("_rt.chk({l} {sym} {r})"), 9)
                } else if is_float {
                    let l = self.expr_prec(lhs, prec, depth);
                    let r = self.expr_prec(rhs, prec + 1, depth);
                    (format!("{l} {sym} {r}"), prec)
                } else {
                    // List concatenation.
                    let l = self.expr_prec(lhs, 5, depth);
                    let r = self.expr_prec(rhs, 6, depth);
                    if needs_dup(result_ty) {
                        (format!("_rt.dup({l} + {r})"), 9)
                    } else {
                        (format!("{l} + {r}"), 5)
                    }
                }
            }
            BinaryOp::Div => {
                let l = self.expr(lhs, depth);
                let r = self.expr(rhs, depth);
                if is_int {
                    (format!("_rt.div({l}, {r})"), 9)
                } else {
                    (format!("_rt.fdiv({l}, {r})"), 9)
                }
            }
            BinaryOp::Mod => {
                let l = self.expr(lhs, depth);
                let r = self.expr(rhs, depth);
                (format!("_rt.mod_i64({l}, {r})"), 9)
            }
            BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge => {
                let sym = match op {
                    BinaryOp::Lt => "<",
                    BinaryOp::Le => "<=",
                    BinaryOp::Gt => ">",
                    _ => ">=",
                };
                // Comparisons chain in Python; force both children tighter.
                let l = self.expr_prec(lhs, 5, depth);
                let r = self.expr_prec(rhs, 5, depth);
                (format!("{l} {sym} {r}"), 4)
            }
            BinaryOp::Eq | BinaryOp::Ne => {
                if scalar_eq(&lhs.ty) {
                    let sym = if op == BinaryOp::Eq { "==" } else { "!=" };
                    let l = self.expr_prec(lhs, 5, depth);
                    let r = self.expr_prec(rhs, 5, depth);
                    (format!("{l} {sym} {r}"), 4)
                } else {
                    let l = self.expr(lhs, depth);
                    let r = self.expr(rhs, depth);
                    let call = format!("_rt.eq({l}, {r})");
                    if op == BinaryOp::Eq {
                        (call, 9)
                    } else {
                        (format!("not {call}"), 3)
                    }
                }
            }
            BinaryOp::And => {
                let l = self.expr_prec(lhs, 2, depth);
                let r = self.expr_prec(rhs, 3, depth);
                (format!("{l} and {r}"), 2)
            }
            BinaryOp::Or => {
                let l = self.expr_prec(lhs, 1, depth);
                let r = self.expr_prec(rhs, 2, depth);
                (format!("{l} or {r}"), 1)
            }
        }
    }

    fn builtin(&mut self, b: Builtin, args: &[IrExpr], depth: usize) -> String {
        let a = |s: &mut Self, i: usize| s.expr(&args[i], depth);
        let a_atom = |s: &mut Self, i: usize| s.expr_prec(&args[i], 9, depth);
        match b {
            Builtin::AbsInt => format!("_rt.abs_i64({})", a(self, 0)),
            Builtin::AbsFloat => format!("abs({})", a(self, 0)),
            Builtin::MinInt => format!("min({}, {})", a(self, 0), a(self, 1)),
            Builtin::MaxInt => format!("max({}, {})", a(self, 0), a(self, 1)),
            Builtin::MinFloat => format!("_rt.fmin({}, {})", a(self, 0), a(self, 1)),
            Builtin::MaxFloat => format!("_rt.fmax({}, {})", a(self, 0), a(self, 1)),
            Builtin::FloatOfInt => format!("float({})", a(self, 0)),
            Builtin::IntOfFloat => format!("_rt.int_of({})", a(self, 0)),
            Builtin::Floor => format!("_rt.floor({})", a(self, 0)),
            Builtin::Ceil => format!("_rt.ceil({})", a(self, 0)),
            Builtin::Round => format!("_rt.round_half_away({})", a(self, 0)),
            Builtin::Sqrt => format!("_rt.sqrt({})", a(self, 0)),
            Builtin::Filled => {
                let n = a(self, 0);
                let v = self.expr(&args[1], depth);
                format!("_rt.filled({n}, {v})")
            }
            Builtin::NewMap => "_rt.SudoMap()".into(),
            Builtin::NewSet => "_rt.SudoSet()".into(),
            Builtin::ListLength | Builtin::MapSize | Builtin::SetSize => {
                format!("len({})", a(self, 0))
            }
            Builtin::MapGet => format!("{}.get_opt({})", a_atom(self, 0), a(self, 1)),
            Builtin::MapHas => format!("{} in {}", a_atom(self, 1), a_atom(self, 0)),
            Builtin::MapKeys => format!("{}.keys_list()", a_atom(self, 0)),
            Builtin::MapValues => format!("{}.values_list()", a_atom(self, 0)),
            Builtin::SetHas => format!("{} in {}", a_atom(self, 1), a_atom(self, 0)),
            Builtin::SetItems => format!("{}.items_list()", a_atom(self, 0)),
            Builtin::OptIsSome => format!("_rt.is_some({})", a(self, 0)),
            Builtin::OptIsNone => format!("_rt.is_none({})", a(self, 0)),
            Builtin::OptUnwrap | Builtin::ResUnwrap => format!("_rt.unwrap({})", a(self, 0)),
            Builtin::OptGetOr | Builtin::ResGetOr => {
                format!("_rt.get_or({}, {})", a(self, 0), a(self, 1))
            }
            Builtin::ResIsOk => format!("_rt.is_ok({})", a(self, 0)),
            Builtin::ResIsErr => format!("_rt.is_err({})", a(self, 0)),
            // Mutating builtins never appear here.
            _ => unreachable!("mutating builtin in non-mut position: {b:?}"),
        }
    }

    fn mut_builtin(
        &mut self,
        b: Builtin,
        recv: &Place,
        args: &[IrExpr],
        depth: usize,
    ) -> String {
        let r = self.place_expr(recv, depth);
        match b {
            Builtin::ListAppend => {
                let v = self.store(&args[0], depth);
                format!("{r}.append({v})")
            }
            Builtin::ListPop => format!("_rt.pop({r})"),
            Builtin::ListInsert => {
                let i = self.expr(&args[0], depth);
                let v = self.store(&args[1], depth);
                format!("_rt.insert({r}, {i}, {v})")
            }
            Builtin::ListRemoveAt => {
                let i = self.expr(&args[0], depth);
                format!("_rt.remove_at({r}, {i})")
            }
            Builtin::ListSwap => {
                let i = self.expr(&args[0], depth);
                let j = self.expr(&args[1], depth);
                format!("_rt.swap({r}, {i}, {j})")
            }
            Builtin::ListSort => format!("_rt.sort({r})"),
            Builtin::MapDelete => {
                let k = self.expr(&args[0], depth);
                format!("{r}.delete({k})")
            }
            Builtin::SetAdd => {
                let v = self.expr(&args[0], depth);
                format!("{r}.add({v})")
            }
            Builtin::SetRemove => {
                let v = self.expr(&args[0], depth);
                format!("{r}.remove({v})")
            }
            _ => unreachable!("non-mutating builtin in mut position: {b:?}"),
        }
    }

    fn line(&mut self, depth: usize, s: &str) {
        for _ in 0..depth {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) {
        self.out.push('\n');
    }
}

// ---- helpers ----------------------------------------------------------------

/// Does an expression of this kind alias existing storage (so a storing
/// position must copy it)?
fn aliasing(kind: &IrExprKind) -> bool {
    match kind {
        IrExprKind::Local(_)
        | IrExprKind::Const(_)
        | IrExprKind::GetField { .. }
        | IrExprKind::Index { .. } => true,
        IrExprKind::Builtin { builtin, .. } => matches!(
            builtin,
            Builtin::OptUnwrap | Builtin::OptGetOr | Builtin::ResUnwrap | Builtin::ResGetOr
        ),
        _ => false,
    }
}

/// Types whose Python representation can be mutated in place and therefore
/// must be copied at aliasing boundaries. Enums and Option/Result share
/// safely: they have no in-place mutation path (payload copies happen at
/// extraction — match binders and unwraps).
fn needs_dup(ty: &Ty) -> bool {
    match ty {
        Ty::List(_) | Ty::Map(..) | Ty::Set(_) | Ty::Record(_) => true,
        Ty::Tuple(ts) => ts.iter().any(needs_dup),
        _ => false,
    }
}

fn scalar_eq(ty: &Ty) -> bool {
    matches!(strip(ty), Ty::Int | Ty::Bool | Ty::Float)
}

fn strip(ty: &Ty) -> &Ty {
    ty
}

fn tuple_of(names: &[String]) -> String {
    names.join(", ")
}

fn definitely_returns(stmts: &[IrStmt]) -> bool {
    stmts.iter().any(|s| match s {
        IrStmt::Return(_) => true,
        IrStmt::If { arms, else_block } => {
            else_block.as_ref().is_some_and(|e| definitely_returns(e))
                && arms.iter().all(|(_, b)| definitely_returns(b))
        }
        IrStmt::Match { arms, .. } => arms.iter().all(|a| definitely_returns(&a.body)),
        _ => false,
    })
}

fn py_ty(ty: &Ty) -> String {
    match ty {
        Ty::Int => "int".into(),
        Ty::Float => "float".into(),
        Ty::Bool => "bool".into(),
        Ty::List(_) => "list".into(),
        Ty::Map(..) => "_rt.SudoMap".into(),
        Ty::Set(_) => "_rt.SudoSet".into(),
        Ty::Tuple(_) => "tuple".into(),
        Ty::Record(n) | Ty::Enum(n) => n.clone(),
        _ => "object".into(),
    }
}

fn py_str(scalars: &[i64]) -> String {
    let mut s = String::from("\"");
    for &c in scalars {
        match char::from_u32(c as u32) {
            Some('"') => s.push_str("\\\""),
            Some('\\') => s.push_str("\\\\"),
            Some('\n') => s.push_str("\\n"),
            Some('\t') => s.push_str("\\t"),
            Some('\r') => s.push_str("\\r"),
            Some(ch) if (' '..='~').contains(&ch) => s.push(ch),
            Some(ch) if (ch as u32) <= 0xFFFF => {
                s.push_str(&format!("\\u{:04x}", ch as u32))
            }
            Some(ch) => s.push_str(&format!("\\U{:08x}", ch as u32)),
            None => s.push_str("\\ufffd"),
        }
    }
    s.push('"');
    s
}


/// Host-facing wrapper module (lockstep.md §5.1): converts host values in
/// (with validation), internal values out (Option collapse, Result raising,
/// text as str), and writes inout results back into the host's own objects.
/// Returns None when the module has no exports.
pub fn emit_api(m: &IrModule) -> Option<String> {
    let exports: Vec<&IrFunc> = m.funcs.iter().filter(|f| f.export).collect();
    if exports.is_empty() {
        return None;
    }
    use sudoc_ir::BoundaryTy as Te;
    let mut out = String::new();
    let w = &mut out;
    let push = |w: &mut String, s: &str| {
        w.push_str(s);
        w.push('\n');
    };
    push(w, &format!("\"\"\"Host-facing API for {}.sudo — generated by sudoc. Traps raise", m.name));
    push(w, "_rt.SudoTrap; Err results raise SudoError; invalid inputs raise ValueError.\"\"\"");
    push(w, &format!("import _{}_impl as _impl", m.name));
    push(w, "import _sudo_rt as _rt");
    push(w, "from _sudo_rt import SudoError, SudoTrap");
    push(w, "");

    for f in &exports {
        let params: Vec<&str> = f.params.iter().map(|p| p.name.as_str()).collect();
        push(w, &format!("def {}({}):", f.name, params.join(", ")));
        // Convert inputs. Inout params convert into a shadow variable so the
        // host's object survives for writeback.
        for p in &f.params {
            let src = p.name.clone();
            let target = if p.inout { format!("_{}", p.name) } else { p.name.clone() };
            match conv_in(&p.boundary, &src) {
                Some(code) => push(w, &format!("    {target} = {code}")),
                None if p.inout => push(w, &format!("    {target} = {src}")),
                None => {}
            }
        }
        // Call the implementation; unpack the writeback protocol.
        let args: Vec<String> = f
            .params
            .iter()
            .map(|p| if p.inout { format!("_{}", p.name) } else { p.name.clone() })
            .collect();
        let mut targets: Vec<String> = Vec::new();
        if f.ret.is_some() {
            targets.push("_r".into());
        }
        for p in f.params.iter().filter(|p| p.inout) {
            targets.push(format!("_new_{}", p.name));
        }
        let call = format!("_impl.{}({})", f.name, args.join(", "));
        if targets.is_empty() {
            push(w, &format!("    {call}"));
        } else {
            push(w, &format!("    {} = {call}", targets.join(", ")));
        }
        // Write inout results back into the host's objects, in place.
        for p in f.params.iter().filter(|p| p.inout) {
            let new = format!("_new_{}", p.name);
            match &p.boundary {
                Te::List(t) => {
                    let elem = conv_out(t, "_v").unwrap_or_else(|| "_v".into());
                    push(w, &format!(
                        "    _rt.writeback_list({}, {new}, lambda _v: {elem})",
                        p.name
                    ));
                }
                Te::Map(k, v) => {
                    let kc = conv_out(k, "_k").unwrap_or_else(|| "_k".into());
                    let vc = conv_out(v, "_v").unwrap_or_else(|| "_v".into());
                    push(w, &format!(
                        "    _rt.writeback_map({}, {new}, lambda _k: {kc}, lambda _v: {vc})",
                        p.name
                    ));
                }
                Te::Set(t) => {
                    let elem = conv_out(t, "_v").unwrap_or_else(|| "_v".into());
                    push(w, &format!(
                        "    _rt.writeback_set({}, {new}, lambda _v: {elem})",
                        p.name
                    ));
                }
                Te::Named(_) => {
                    // Record: copy fields back into the host's instance.
                    if let Ty::Record(rname) = &p.ty {
                        if let Some(r) = m.record(rname) {
                            for (fname, _) in &r.fields {
                                push(w, &format!("    {}.{fname} = {new}.{fname}", p.name));
                            }
                        }
                    }
                }
                _ => {}
            }
        }
        match (&f.ret, &f.ret_boundary) {
            (Some(_), Some(rb)) => match conv_out(rb, "_r") {
                Some(code) => push(w, &format!("    return {code}")),
                None => push(w, "    return _r"),
            },
            (Some(_), None) => push(w, "    return _r"),
            _ => {}
        }
        push(w, "");
    }
    Some(out)
}

/// Host -> internal conversion expression, or None for passthrough.
fn conv_in(te: &sudoc_ir::BoundaryTy, var: &str) -> Option<String> {
    use sudoc_ir::BoundaryTy as Te;
    match te {
        Te::Int => Some(format!("_rt.host_int({var})")),
        Te::Float => Some(format!("_rt.host_float({var})")),
        Te::Bool => Some(format!("_rt.host_bool({var})")),
        Te::Text => Some(format!("_rt.host_text({var})")),
        Te::List(t) => {
            let inner = conv_in(t, "_v");
            match inner {
                Some(code) => Some(format!("[{code} for _v in _rt.host_list({var})]")),
                None => Some(format!("_rt.host_list({var})")),
            }
        }
        Te::Map(k, v) => {
            let kc = conv_in(k, "_k").unwrap_or_else(|| "_k".into());
            let vc = conv_in(v, "_v").unwrap_or_else(|| "_v".into());
            Some(format!("_rt.host_map({var}, lambda _k: {kc}, lambda _v: {vc})"))
        }
        Te::Set(t) => {
            let c = conv_in(t, "_v").unwrap_or_else(|| "_v".into());
            Some(format!("_rt.host_set({var}, lambda _v: {c})"))
        }
        Te::Option_(t) => {
            let c = conv_in(t, var).unwrap_or_else(|| var.to_string());
            Some(format!("(_rt.NONE if {var} is None else _rt.Some({c}))"))
        }
        Te::Tuple(ts) => {
            let n = ts.len();
            let parts: Vec<String> = ts
                .iter()
                .enumerate()
                .map(|(i, t)| {
                    conv_in(t, &format!("_t[{i}]")).unwrap_or_else(|| format!("_t[{i}]"))
                })
                .collect();
            Some(format!(
                "(lambda _t: ({},))(_rt.host_tuple({var}, {n}))",
                parts.join(", ")
            ))
        }
        _ => None, // records, enums, Result params: passthrough
    }
}

/// Internal -> host conversion expression, or None for passthrough.
fn conv_out(te: &sudoc_ir::BoundaryTy, var: &str) -> Option<String> {
    use sudoc_ir::BoundaryTy as Te;
    match te {
        Te::Text => Some(format!("_rt.text_str({var})")),
        Te::Option_(t) => {
            let c = conv_out(t, "_v").unwrap_or_else(|| "_v".into());
            Some(format!("_rt.out_option({var}, lambda _v: {c})"))
        }
        Te::Result_(t, e) => {
            let okc = conv_out(t, "_v").unwrap_or_else(|| "_v".into());
            let ec = conv_out(e, "_e").unwrap_or_else(|| "_e".into());
            Some(format!(
                "_rt.out_result({var}, lambda _v: {okc}, lambda _e: {ec})"
            ))
        }
        Te::Map(k, v) => {
            let kc = conv_out(k, "_k").unwrap_or_else(|| "_k".into());
            let vc = conv_out(v, "_v").unwrap_or_else(|| "_v".into());
            Some(format!("_rt.out_map({var}, lambda _k: {kc}, lambda _v: {vc})"))
        }
        Te::Set(t) => {
            let c = conv_out(t, "_v").unwrap_or_else(|| "_v".into());
            Some(format!("_rt.out_set({var}, lambda _v: {c})"))
        }
        Te::List(t) => {
            conv_out(t, "_v").map(|code| format!("[{code} for _v in {var}]"))
        }
        Te::Tuple(ts) => {
            let parts: Vec<Option<String>> =
                ts.iter().enumerate().map(|(i, t)| conv_out(t, &format!("{var}[{i}]"))).collect();
            if parts.iter().all(Option::is_none) {
                return None;
            }
            let items: Vec<String> = parts
                .into_iter()
                .enumerate()
                .map(|(i, c)| c.unwrap_or_else(|| format!("{var}[{i}]")))
                .collect();
            Some(format!("({},)", items.join(", ")))
        }
        _ => None,
    }
}

/// The reference Python backend, via the SDK contract.
pub struct PythonBackend;

impl sudoc_sdk::Backend for PythonBackend {
    fn name(&self) -> &'static str {
        "py"
    }

    fn emit_program(
        &self,
        modules: &[IrModule],
        with_tests: bool,
    ) -> Result<Vec<sudoc_sdk::GeneratedFile>, String> {
        let (entry, deps) = modules.split_last().expect("entry module");
        let mut out = Vec::new();
        for m in deps {
            out.push(sudoc_sdk::GeneratedFile {
                path: impl_file(&m.name),
                contents: emit_with(m, modules, false),
            });
            if let Some(api) = emit_api(m) {
                out.push(sudoc_sdk::GeneratedFile { path: api_file(&m.name), contents: api });
            }
        }
        out.push(sudoc_sdk::GeneratedFile {
            path: impl_file(&entry.name),
            contents: emit_with(entry, modules, with_tests),
        });
        if let Some(api) = emit_api(entry) {
            out.push(sudoc_sdk::GeneratedFile { path: api_file(&entry.name), contents: api });
        }
        Ok(out)
    }

    fn runtime_files(&self) -> Vec<sudoc_sdk::GeneratedFile> {
        vec![sudoc_sdk::GeneratedFile { path: RUNTIME_FILE.into(), contents: RUNTIME.into() }]
    }

    fn test_recipe(&self, entry: &str) -> sudoc_sdk::TestRecipe {
        sudoc_sdk::TestRecipe {
            build: Vec::new(),
            run: vec!["python3".into(), impl_file(entry)],
        }
    }
}
