//! Statement/expression emitter: typed IR → readable Swift 6.
//!
//! Value semantics, deep equality, and COW containers are native — no
//! dup/free/eq helpers. Every sudo function is `throws`; Int64 arithmetic
//! routes through checked runtime helpers; floats use bare IEEE operators.

use sudoc_ir::{
    BinaryOp, Builtin, IrExpr, IrExprKind, IrFunc, IrModule, IrPattern, IrStmt, Place, Ty,
    UnaryOp,
};

use crate::types_gen::{
    collect_tuples, conformances, mangle, swift_ident, swift_type, variant_case,
};

pub(crate) fn emit(module: &IrModule, with_tests: bool) -> String {
    Emitter {
        m: module,
        out: String::new(),
        loop_labels: Vec::new(),
        next_label: 0,
        next_tmp: 0,
    }
    .run(with_tests)
}

struct Emitter<'a> {
    m: &'a IrModule,
    out: String,
    /// Innermost loop label is last; break/continue always target it.
    loop_labels: Vec<String>,
    next_label: usize,
    next_tmp: usize,
}

impl Emitter<'_> {
    fn run(mut self, with_tests: bool) -> String {
        self.line(
            0,
            &format!(
                "// Generated by sudoc from {}.sudo — do not edit; edit the sudo source.",
                self.m.name
            ),
        );
        self.line(0, "import Foundation");
        self.blank();

        // Tuple structs (shared by shape across the whole merged program).
        let tuples = collect_tuples(self.m);
        for (name, elems) in &tuples {
            let ty = Ty::Tuple(elems.clone());
            let conf = conformances(&ty, self.m);
            self.line(0, &format!("struct {name}{conf} {{"));
            for (i, e) in elems.iter().enumerate() {
                self.line(1, &format!("var f{i}: {}", swift_type(e)));
            }
            let params: Vec<String> = elems
                .iter()
                .enumerate()
                .map(|(i, e)| format!("_ f{i}: {}", swift_type(e)))
                .collect();
            self.line(1, &format!("init({}) {{", params.join(", ")));
            for i in 0..elems.len() {
                self.line(2, &format!("self.f{i} = f{i}"));
            }
            self.line(1, "}");
            self.line(0, "}");
            self.blank();
        }

        // Records.
        for r in &self.m.records {
            let ty = Ty::Record(r.name.clone());
            let conf = conformances(&ty, self.m);
            let name = swift_ident(&r.name);
            self.line(0, &format!("struct {name}{conf} {{"));
            for (fname, fty) in &r.fields {
                self.line(
                    1,
                    &format!("var {}: {}", swift_ident(fname), swift_type(fty)),
                );
            }
            let params: Vec<String> = r
                .fields
                .iter()
                .map(|(n, t)| format!("_ {}: {}", swift_ident(n), swift_type(t)))
                .collect();
            self.line(1, &format!("init({}) {{", params.join(", ")));
            for (n, _) in &r.fields {
                let id = swift_ident(n);
                self.line(2, &format!("self.{id} = {id}"));
            }
            self.line(1, "}");
            self.line(0, "}");
            self.blank();
        }

        // Enums — every payload-bearing case is `indirect` (recursion via Option/enum).
        for e in &self.m.enums {
            let ty = Ty::Enum(e.name.clone());
            let conf = conformances(&ty, self.m);
            let name = swift_ident(&e.name);
            self.line(0, &format!("enum {name}{conf} {{"));
            for v in &e.variants {
                let case = swift_ident(&variant_case(&v.name));
                if v.fields.is_empty() {
                    self.line(1, &format!("case {case}"));
                } else {
                    let types: Vec<String> = v.fields.iter().map(|(_, t)| swift_type(t)).collect();
                    self.line(1, &format!("indirect case {case}({})", types.join(", ")));
                }
            }
            self.line(0, "}");
            self.blank();
        }

        // Module constants (scalar folded expressions only).
        for c in &self.m.consts {
            let value = self.expr(&c.value);
            self.line(
                0,
                &format!(
                    "let {}: {} = {}",
                    swift_ident(&c.name),
                    swift_type(&c.ty),
                    value
                ),
            );
        }
        if !self.m.consts.is_empty() {
            self.blank();
        }

        for f in &self.m.funcs {
            self.func(f);
            self.blank();
        }

        if with_tests {
            let names = sudoc_ir::names::test_fn_names(&self.m.tests);
            for (t, name) in self.m.tests.iter().zip(&names) {
                self.line(0, &format!("func {name}() throws {{"));
                if !t.body.is_empty() {
                    self.block(&t.body, 1);
                }
                self.line(0, "}");
                self.blank();
            }
            self.line(0, "@main");
            self.line(0, "struct SudoTestRunner {");
            self.line(1, "static func main() {");
            self.line(2, "let tests: [(String, () throws -> Void)] = [");
            for name in &names {
                self.line(3, &format!("(\"{name}\", {name}),"));
            }
            self.line(2, "]");
            self.line(2, "exit(runTests(tests))");
            self.line(1, "}");
            self.line(0, "}");
        }
        self.out
    }

    fn func(&mut self, f: &IrFunc) {
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                let id = swift_ident(&p.name);
                let ty = swift_type(&p.ty);
                if p.inout {
                    format!("_ {id}: inout {ty}")
                } else {
                    format!("_ {id}: {ty}")
                }
            })
            .collect();
        let ret = match &f.ret {
            Some(t) => format!(" -> {}", swift_type(t)),
            None => String::new(),
        };
        let discard = if f.ret.is_some() {
            "@discardableResult "
        } else {
            ""
        };
        self.line(
            0,
            &format!(
                "{discard}func {}({}) throws{ret} {{",
                swift_ident(&f.name),
                params.join(", ")
            ),
        );
        // Swift parameters are immutable (`let`); sudo params are reassignable
        // locals (e.g. gcd's `a, b = b, a mod b`). Shadow a non-inout param
        // with a `var` copy only when the body actually mutates it — COW keeps
        // the copy cheap until mutation. Unconditionally shadowing breaks
        // non-escaping closure params (Ty::Func) and adds needless warnings.
        for p in &f.params {
            if !p.inout && mutates_local(self.m, &f.body, &p.name) {
                let id = swift_ident(&p.name);
                self.line(
                    1,
                    &format!("var {id}: {} = {id}", swift_type(&p.ty)),
                );
            }
        }
        self.block(&f.body, 1);
        self.line(0, "}");
    }

    fn block(&mut self, stmts: &[IrStmt], depth: usize) {
        for s in stmts {
            self.stmt(s, depth);
        }
    }

    fn stmt(&mut self, s: &IrStmt, depth: usize) {
        match s {
            IrStmt::Assign { target, value, declares } => {
                let v = self.try_expr(value);
                self.assign_to_place(target, &v, depth, *declares, &value.ty);
            }
            IrStmt::TupleAssign { targets, declares, value } => {
                let v = self.try_expr(value);
                let tmp = self.fresh("T");
                let tty = swift_type(&value.ty);
                self.line(depth, &format!("let {tmp}: {tty} = {v}"));
                let elems = match &value.ty {
                    Ty::Tuple(ts) => ts.clone(),
                    _ => vec![],
                };
                for (i, (t, d)) in targets.iter().zip(declares.iter()).enumerate() {
                    let id = swift_ident(t);
                    let field = format!("{tmp}.f{i}");
                    if *d {
                        let ty = elems
                            .get(i)
                            .map(swift_type)
                            .unwrap_or_else(|| "Int64".into());
                        self.line(depth, &format!("var {id}: {ty} = {field}"));
                    } else {
                        self.line(depth, &format!("{id} = {field}"));
                    }
                }
            }
            IrStmt::Expr(e) => {
                let code = self.try_expr(e);
                self.line(depth, &code);
            }
            IrStmt::If { arms, else_block } => {
                for (i, (cond, body)) in arms.iter().enumerate() {
                    let c = self.try_expr(cond);
                    if i == 0 {
                        self.line(depth, &format!("if {c} {{"));
                    } else {
                        self.line(depth, &format!("}} else if {c} {{"));
                    }
                    self.block(body, depth + 1);
                }
                if let Some(body) = else_block {
                    self.line(depth, "} else {");
                    self.block(body, depth + 1);
                    self.line(depth, "}");
                } else if !arms.is_empty() {
                    self.line(depth, "}");
                }
            }
            IrStmt::While { cond, body } => {
                let label = self.push_loop();
                let c = self.try_expr(cond);
                self.line(depth, &format!("{label}: while {c} {{"));
                self.block(body, depth + 1);
                self.line(depth, "}");
                self.pop_loop();
            }
            IrStmt::ForRange { var, from, to, down, body } => {
                let lo = self.try_expr(from);
                let hi = self.try_expr(to);
                let lo_t = self.fresh("Lo");
                let hi_t = self.fresh("Hi");
                self.line(depth, &format!("let {lo_t}: Int64 = {lo}"));
                self.line(depth, &format!("let {hi_t}: Int64 = {hi}"));
                let label = self.push_loop();
                let id = swift_ident(var);
                let down_lit = if *down { "true" } else { "false" };
                self.line(
                    depth,
                    &format!("{label}: for {id} in sudoRange({lo_t}, {hi_t}, down: {down_lit}) {{"),
                );
                self.block(body, depth + 1);
                self.line(depth, "}");
                self.pop_loop();
            }
            IrStmt::ForIn { vars, iter, body } => {
                let it = self.try_expr(iter);
                let snap = self.fresh("Iter");
                let ity = swift_type(&iter.ty);
                self.line(depth, &format!("let {snap}: {ity} = {it}"));
                let label = self.push_loop();
                match &iter.ty {
                    Ty::Map(..) => {
                        let k = swift_ident(&vars[0]);
                        let v = swift_ident(&vars[1]);
                        self.line(depth, &format!("{label}: for ({k}, {v}) in {snap} {{"));
                    }
                    _ => {
                        let x = swift_ident(&vars[0]);
                        self.line(depth, &format!("{label}: for {x} in {snap} {{"));
                    }
                }
                self.block(body, depth + 1);
                self.line(depth, "}");
                self.pop_loop();
            }
            IrStmt::Match { scrutinee, arms } => {
                let sc = self.try_expr(scrutinee);
                let sc_tmp = self.fresh("Sc");
                let sty = swift_type(&scrutinee.ty);
                self.line(depth, &format!("let {sc_tmp}: {sty} = {sc}"));
                self.line(depth, &format!("switch {sc_tmp} {{"));
                for arm in arms {
                    let pat = self.pattern(&arm.pattern, &scrutinee.ty);
                    self.line(depth + 1, &format!("case {pat}:"));
                    let before = self.out.len();
                    self.block(&arm.body, depth + 2);
                    if self.out.len() == before {
                        self.line(depth + 2, "break");
                    }
                }
                self.line(depth, "}");
            }
            IrStmt::Return(None) => self.line(depth, "return"),
            IrStmt::Return(Some(e)) => {
                let v = self.try_expr(e);
                self.line(depth, &format!("return {v}"));
            }
            IrStmt::Assert { cond, line } => {
                if let IrExprKind::Binary { op: BinaryOp::Eq, lhs, rhs } = &cond.kind {
                    let l = self.try_expr(lhs);
                    let r = self.try_expr(rhs);
                    let lt = self.fresh("L");
                    let rt = self.fresh("R");
                    self.line(depth, &format!("let {lt}: {} = {l}", swift_type(&lhs.ty)));
                    self.line(depth, &format!("let {rt}: {} = {r}", swift_type(&rhs.ty)));
                    self.line(depth, &format!("try sudoAssertEq({lt}, {rt}, {line})"));
                } else {
                    let c = self.try_expr(cond);
                    self.line(depth, &format!("try sudoAssert({c}, {line})"));
                }
            }
            IrStmt::Skip => {}
            IrStmt::Break => {
                let label = self.loop_labels.last().expect("break inside loop");
                self.line(depth, &format!("break {label}"));
            }
            IrStmt::Continue => {
                let label = self.loop_labels.last().expect("continue inside loop");
                self.line(depth, &format!("continue {label}"));
            }
            IrStmt::ExpectTrap { kind, body, line } => {
                let flag = self.fresh("Trapped");
                self.line(depth, &format!("var {flag}: Bool = false"));
                self.line(depth, "do {");
                self.block(body, depth + 1);
                self.line(depth, "} catch let t as SudoTrap {");
                self.line(depth + 1, &format!("{flag} = true"));
                self.line(depth + 1, &format!("if t.kind != \"{kind}\" {{"));
                self.line(
                    depth + 2,
                    &format!(
                        "throw SudoTrap(kind: \"AssertFailed\", detail: \"line {line}: expected trap {kind}, got \\(t.kind)\")"
                    ),
                );
                self.line(depth + 1, "}");
                self.line(depth, "}");
                self.line(depth, &format!("if !{flag} {{"));
                self.line(
                    depth + 1,
                    &format!(
                        "throw SudoTrap(kind: \"AssertFailed\", detail: \"line {line}: expected trap {kind}, but nothing trapped\")"
                    ),
                );
                self.line(depth, "}");
            }
        }
    }

    fn pattern(&self, p: &IrPattern, scrut_ty: &Ty) -> String {
        match p {
            IrPattern::Int(v) => int_lit(*v),
            IrPattern::Bool(true) => "true".into(),
            IrPattern::Bool(false) => "false".into(),
            IrPattern::Wildcard => "_".into(),
            IrPattern::Variant { enum_name, variant, binders } => {
                let case = match (enum_name.as_str(), variant.as_str()) {
                    ("Option", "Some") => "some".to_string(),
                    ("Option", "None") => "none".to_string(),
                    ("Result", "Ok") => "ok".to_string(),
                    ("Result", "Err") => "err".to_string(),
                    _ => variant_case(variant),
                };
                let case = swift_ident(&case);
                let _ = scrut_ty;
                if binders.is_empty() {
                    format!(".{case}")
                } else {
                    let binds: Vec<String> =
                        binders.iter().map(|b| format!("let {}", swift_ident(b))).collect();
                    format!(".{case}({})", binds.join(", "))
                }
            }
        }
    }

    fn assign_to_place(
        &mut self,
        place: &Place,
        value: &str,
        depth: usize,
        declares: bool,
        value_ty: &Ty,
    ) {
        match place {
            Place::Var(n) => {
                let id = swift_ident(n);
                if declares {
                    self.line(
                        depth,
                        &format!("var {id}: {} = {value}", swift_type(value_ty)),
                    );
                } else {
                    self.line(depth, &format!("{id} = {value}"));
                }
            }
            Place::Index { base, base_ty, index } => {
                let b = self.place_expr(base);
                let i = self.try_expr(index);
                match base_ty {
                    Ty::Map(..) => {
                        // Native insert-or-overwrite; evaluate value first (already done).
                        self.line(depth, &format!("{b}[{i}] = {value}"));
                    }
                    _ => {
                        self.line(depth, &format!("try listSet(&{b}, {i}, {value})"));
                    }
                }
            }
            Place::Field { base, name, .. } => {
                let b = self.place_expr(base);
                self.line(depth, &format!("{b}.{} = {value}", swift_ident(name)));
            }
        }
    }

    fn place_expr(&mut self, place: &Place) -> String {
        match place {
            Place::Var(n) => swift_ident(n),
            Place::Index { base, base_ty, index } => {
                let b = self.place_expr(base);
                let i = self.try_expr(index);
                match base_ty {
                    Ty::Map(..) => format!("(try mapAt({b}, {i}))"),
                    _ => format!("(try listAt({b}, {i}))"),
                }
            }
            Place::Field { base, name, .. } => {
                let b = self.place_expr(base);
                format!("{b}.{}", swift_ident(name))
            }
        }
    }

    /// Expression at statement position: prefix `try` when any subexpr throws.
    fn try_expr(&mut self, e: &IrExpr) -> String {
        let code = self.expr(e);
        if might_throw(e) {
            format!("try {code}")
        } else {
            code
        }
    }

    fn expr(&mut self, e: &IrExpr) -> String {
        self.expr_prec(e, 0)
    }

    /// Parenthesize if this expression binds looser than `ctx`.
    ///
    /// Swift precedence (low → high), from the language guide precedence groups:
    ///   1 = `||` (LogicalDisjunction), 2 = `&&` (LogicalConjunction),
    ///   3 = comparison (`== != < <= > >=`, ComparisonPrecedence — one tier),
    ///   4 = `+`/`-` (Addition), 5 = `*`/`/`/`%` (Multiplication),
    ///   6 = unary `!`/`-` (prefix), 9 = atom / call / subscript.
    /// Critical: `!` is prefix-unary (tighter than every binary), so
    /// `not (a == b)` must become `!(a == b)`, never `!a == b`.
    fn expr_prec(&mut self, e: &IrExpr, ctx: u8) -> String {
        let (code, prec) = self.expr_raw(e);
        if prec < ctx {
            format!("({code})")
        } else {
            code
        }
    }

    fn expr_raw(&mut self, e: &IrExpr) -> (String, u8) {
        let atom = 9u8;
        match &e.kind {
            IrExprKind::Int(v) => {
                let s = int_lit(*v);
                (s, if *v < 0 { 6 } else { atom })
            }
            IrExprKind::Float(v) => {
                let s = float_lit(*v);
                (s, if *v < 0.0 { 6 } else { atom })
            }
            IrExprKind::Bool(v) => (if *v { "true" } else { "false" }.into(), atom),
            IrExprKind::Text(s) => {
                let items: Vec<String> = s.iter().map(|c| format!("Int64({c})")).collect();
                (format!("[{}]", items.join(", ")), atom)
            }
            IrExprKind::Local(n) | IrExprKind::Const(n) | IrExprKind::FuncRef(n) => {
                (swift_ident(n), atom)
            }
            IrExprKind::List(xs) => {
                let items: Vec<String> = xs.iter().map(|x| self.expr(x)).collect();
                (format!("[{}]", items.join(", ")), atom)
            }
            IrExprKind::Tuple(xs) => {
                let name = mangle(&e.ty);
                let items: Vec<String> = xs.iter().map(|x| self.expr(x)).collect();
                (format!("{name}({})", items.join(", ")), atom)
            }
            IrExprKind::CallFunc { name, args } => {
                let a = self.emit_call_args(name, args);
                (format!("{}({a})", swift_ident(name)), atom)
            }
            IrExprKind::CallValue { callee, args } => {
                let c = self.expr_prec(callee, atom);
                let a: Vec<String> = args.iter().map(|x| self.expr(x)).collect();
                (format!("{c}({})", a.join(", ")), atom)
            }
            IrExprKind::NewRecord { name, args } => {
                let a: Vec<String> = args.iter().map(|x| self.expr(x)).collect();
                (format!("{}({})", swift_ident(name), a.join(", ")), atom)
            }
            IrExprKind::NewVariant { enum_name, variant, args } => {
                let a: Vec<String> = args.iter().map(|x| self.expr(x)).collect();
                let code = match (enum_name.as_str(), variant.as_str()) {
                    ("Option", "Some") => {
                        let inner = match &e.ty {
                            Ty::Option_(t) => swift_type(t),
                            _ => "Int64".into(),
                        };
                        format!("SudoOption<{inner}>.some({})", a.join(", "))
                    }
                    ("Option", "None") => {
                        let inner = match &e.ty {
                            Ty::Option_(t) => swift_type(t),
                            _ => "Int64".into(),
                        };
                        format!("SudoOption<{inner}>.none")
                    }
                    ("Result", "Ok") => {
                        let (t, er) = match &e.ty {
                            Ty::Result_(t, er) => (swift_type(t), swift_type(er)),
                            _ => ("Int64".into(), "Int64".into()),
                        };
                        format!("SudoResult<{t}, {er}>.ok({})", a.join(", "))
                    }
                    ("Result", "Err") => {
                        let (t, er) = match &e.ty {
                            Ty::Result_(t, er) => (swift_type(t), swift_type(er)),
                            _ => ("Int64".into(), "Int64".into()),
                        };
                        format!("SudoResult<{t}, {er}>.err({})", a.join(", "))
                    }
                    _ => {
                        let case = swift_ident(&variant_case(variant));
                        let en = swift_ident(enum_name);
                        if a.is_empty() {
                            format!("{en}.{case}")
                        } else {
                            format!("{en}.{case}({})", a.join(", "))
                        }
                    }
                };
                (code, atom)
            }
            IrExprKind::Builtin { builtin, args } => (self.builtin(*builtin, args, &e.ty), atom),
            IrExprKind::MutBuiltin { builtin, recv, recv_ty, args } => {
                (self.mut_builtin(*builtin, recv, recv_ty, args), atom)
            }
            IrExprKind::GetField { recv, name } => {
                let r = self.expr_prec(recv, atom);
                (format!("{r}.{}", swift_ident(name)), atom)
            }
            IrExprKind::Index { recv, index } => {
                let r = self.expr(recv);
                let i = self.expr(index);
                match &recv.ty {
                    Ty::Map(..) => (format!("mapAt({r}, {i})"), atom),
                    _ => (format!("listAt({r}, {i})"), atom),
                }
            }
            IrExprKind::Unary { op, operand } => match op {
                UnaryOp::Neg => match &e.ty {
                    Ty::Int => {
                        let x = self.expr(operand);
                        (format!("chkNeg({x})"), atom)
                    }
                    _ => {
                        let x = self.expr_prec(operand, 6);
                        (format!("-{x}"), 6)
                    }
                },
                UnaryOp::Not => {
                    let x = self.expr_prec(operand, 6);
                    (format!("!{x}"), 6)
                }
            },
            IrExprKind::Binary { op, lhs, rhs } => self.binary(*op, lhs, rhs, &e.ty),
        }
    }

    fn emit_call_args(&mut self, name: &str, args: &[IrExpr]) -> String {
        if let Some(f) = self.m.func(name) {
            let mut parts = Vec::new();
            for (a, p) in args.iter().zip(&f.params) {
                if p.inout {
                    parts.push(format!("&{}", self.inout_lvalue(a)));
                } else {
                    parts.push(self.expr(a));
                }
            }
            if parts.len() < args.len() {
                for a in &args[parts.len()..] {
                    parts.push(self.expr(a));
                }
            }
            return parts.join(", ");
        }
        args.iter().map(|a| self.expr(a)).collect::<Vec<_>>().join(", ")
    }

    fn inout_lvalue(&mut self, e: &IrExpr) -> String {
        match &e.kind {
            IrExprKind::Local(n) => swift_ident(n),
            IrExprKind::GetField { recv, name } => {
                let r = self.inout_lvalue(recv);
                format!("{r}.{}", swift_ident(name))
            }
            _ => self.expr(e),
        }
    }

    fn binary(
        &mut self,
        op: BinaryOp,
        lhs: &IrExpr,
        rhs: &IrExpr,
        result_ty: &Ty,
    ) -> (String, u8) {
        let is_int = matches!(&lhs.ty, Ty::Int);
        let is_float = matches!(&lhs.ty, Ty::Float);
        match op {
            BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul => {
                if is_int {
                    let l = self.expr(lhs);
                    let r = self.expr(rhs);
                    let f = match op {
                        BinaryOp::Add => "chkAdd",
                        BinaryOp::Sub => "chkSub",
                        _ => "chkMul",
                    };
                    (format!("{f}({l}, {r})"), 9)
                } else if is_float {
                    let sym = match op {
                        BinaryOp::Add => "+",
                        BinaryOp::Sub => "-",
                        _ => "*",
                    };
                    let prec = if sym == "*" { 5 } else { 4 };
                    let l = self.expr_prec(lhs, prec);
                    let r = self.expr_prec(rhs, prec + 1);
                    (format!("{l} {sym} {r}"), prec)
                } else {
                    // List concatenation.
                    let l = self.expr_prec(lhs, 4);
                    let r = self.expr_prec(rhs, 5);
                    let _ = result_ty;
                    (format!("{l} + {r}"), 4)
                }
            }
            BinaryOp::Div => {
                if is_int {
                    let l = self.expr(lhs);
                    let r = self.expr(rhs);
                    (format!("floorDiv({l}, {r})"), 9)
                } else {
                    // Float / is bare IEEE (0/0=NaN, never traps).
                    let l = self.expr_prec(lhs, 5);
                    let r = self.expr_prec(rhs, 6);
                    (format!("{l} / {r}"), 5)
                }
            }
            BinaryOp::Mod => {
                let l = self.expr(lhs);
                let r = self.expr(rhs);
                (format!("floorMod({l}, {r})"), 9)
            }
            BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge | BinaryOp::Eq
            | BinaryOp::Ne => {
                let sym = match op {
                    BinaryOp::Lt => "<",
                    BinaryOp::Le => "<=",
                    BinaryOp::Gt => ">",
                    BinaryOp::Ge => ">=",
                    BinaryOp::Eq => "==",
                    BinaryOp::Ne => "!=",
                    _ => unreachable!(),
                };
                // Single ComparisonPrecedence tier in Swift.
                let l = self.expr_prec(lhs, 3);
                let r = self.expr_prec(rhs, 4);
                (format!("{l} {sym} {r}"), 3)
            }
            BinaryOp::And => {
                let l = self.expr_prec(lhs, 2);
                let r = self.expr_prec(rhs, 3);
                (format!("{l} && {r}"), 2)
            }
            BinaryOp::Or => {
                let l = self.expr_prec(lhs, 1);
                let r = self.expr_prec(rhs, 2);
                (format!("{l} || {r}"), 1)
            }
        }
    }

    fn builtin(&mut self, b: Builtin, args: &[IrExpr], ret_ty: &Ty) -> String {
        let a = |s: &mut Self, i: usize| s.expr(&args[i]);
        match b {
            Builtin::AbsInt => format!("chkAbs({})", a(self, 0)),
            Builtin::AbsFloat => format!("abs({})", a(self, 0)),
            Builtin::MinInt => format!("minInt({}, {})", a(self, 0), a(self, 1)),
            Builtin::MaxInt => format!("maxInt({}, {})", a(self, 0), a(self, 1)),
            Builtin::MinFloat => format!("sudoFmin({}, {})", a(self, 0), a(self, 1)),
            Builtin::MaxFloat => format!("sudoFmax({}, {})", a(self, 0), a(self, 1)),
            Builtin::FloatOfInt => format!("Double({})", a(self, 0)),
            Builtin::IntOfFloat => format!("intOfFloat({})", a(self, 0)),
            Builtin::Floor => format!("sudoFloor({})", a(self, 0)),
            Builtin::Ceil => format!("sudoCeil({})", a(self, 0)),
            Builtin::Round => format!("sudoRound({})", a(self, 0)),
            Builtin::Sqrt => format!("sudoSqrt({})", a(self, 0)),
            Builtin::Filled => format!("filled({}, {})", a(self, 0), a(self, 1)),
            Builtin::NewMap => {
                // Typed empty dictionary — never bare `[:]`.
                format!(
                    "Dictionary<{}, {}>()",
                    map_key_type(ret_ty),
                    map_val_type(ret_ty)
                )
            }
            Builtin::NewSet => format!("Set<{}>()", set_elem_type(ret_ty)),
            Builtin::ListLength => format!("Int64({}.count)", self.expr_prec(&args[0], 9)),
            Builtin::MapSize | Builtin::SetSize => {
                format!("Int64({}.count)", self.expr_prec(&args[0], 9))
            }
            Builtin::MapGet => format!("mapGetOpt({}, {})", a(self, 0), a(self, 1)),
            Builtin::MapHas => format!("({}[{}] != nil)", self.expr_prec(&args[0], 9), a(self, 1)),
            Builtin::MapKeys => format!("Array({}.keys)", self.expr_prec(&args[0], 9)),
            Builtin::MapValues => format!("Array({}.values)", self.expr_prec(&args[0], 9)),
            Builtin::SetHas => format!("{}.contains({})", self.expr_prec(&args[0], 9), a(self, 1)),
            Builtin::SetItems => format!("Array({})", a(self, 0)),
            Builtin::OptIsSome => format!("optIsSome({})", a(self, 0)),
            Builtin::OptIsNone => format!("optIsNone({})", a(self, 0)),
            Builtin::OptUnwrap => format!("optUnwrap({})", a(self, 0)),
            Builtin::OptGetOr => format!("optGetOr({}, {})", a(self, 0), a(self, 1)),
            Builtin::ResIsOk => format!("resIsOk({})", a(self, 0)),
            Builtin::ResIsErr => format!("resIsErr({})", a(self, 0)),
            Builtin::ResUnwrap => format!("resUnwrap({})", a(self, 0)),
            Builtin::ResGetOr => format!("resGetOr({}, {})", a(self, 0), a(self, 1)),
            _ => unreachable!("mutating builtin in non-mut position: {b:?}"),
        }
    }

    fn mut_builtin(
        &mut self,
        b: Builtin,
        recv: &Place,
        recv_ty: &Ty,
        args: &[IrExpr],
    ) -> String {
        let r = self.place_expr(recv);
        match b {
            Builtin::ListAppend => {
                let v = self.expr(&args[0]);
                format!("{r}.append({v})")
            }
            Builtin::ListPop => format!("listPop(&{r})"),
            Builtin::ListInsert => {
                let i = self.expr(&args[0]);
                let v = self.expr(&args[1]);
                format!("listInsert(&{r}, {i}, {v})")
            }
            Builtin::ListRemoveAt => {
                let i = self.expr(&args[0]);
                format!("listRemoveAt(&{r}, {i})")
            }
            Builtin::ListSwap => {
                let i = self.expr(&args[0]);
                let j = self.expr(&args[1]);
                format!("listSwap(&{r}, {i}, {j})")
            }
            Builtin::ListSort => match recv_ty {
                Ty::List(e) if matches!(e.as_ref(), Ty::Float) => {
                    format!("listSortFloat(&{r})")
                }
                _ => format!("listSortInt(&{r})"),
            },
            Builtin::MapDelete => {
                let k = self.expr(&args[0]);
                format!("({r}.removeValue(forKey: {k}) != nil)")
            }
            Builtin::SetAdd => {
                let v = self.expr(&args[0]);
                format!("{r}.insert({v}).inserted")
            }
            Builtin::SetRemove => {
                let v = self.expr(&args[0]);
                format!("({r}.remove({v}) != nil)")
            }
            _ => unreachable!("non-mutating builtin in mut position: {b:?}"),
        }
    }

    fn push_loop(&mut self) -> String {
        let label = format!("_l{}", self.next_label);
        self.next_label += 1;
        self.loop_labels.push(label.clone());
        label
    }

    fn pop_loop(&mut self) {
        self.loop_labels.pop();
    }

    fn fresh(&mut self, tag: &str) -> String {
        let n = self.next_tmp;
        self.next_tmp += 1;
        format!("_sudo{tag}{n}")
    }

    fn line(&mut self, depth: usize, s: &str) {
        for _ in 0..depth {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) {
        self.out.push('\n');
    }
}

// ---- helpers ----------------------------------------------------------------

fn int_lit(v: i64) -> String {
    if v == i64::MIN {
        "Int64.min".into()
    } else {
        format!("Int64({v})")
    }
}

fn float_lit(v: f64) -> String {
    if v.is_nan() {
        return "Double.nan".into();
    }
    if v.is_infinite() {
        return if v.is_sign_positive() {
            "Double.infinity".into()
        } else {
            "-Double.infinity".into()
        };
    }
    if v == 0.0 && v.is_sign_negative() {
        return "-0.0".into();
    }
    let s = format!("{v:?}");
    if !s.contains('.') && !s.contains('e') && !s.contains('E') {
        format!("{s}.0")
    } else {
        s
    }
}

fn map_key_type(ty: &Ty) -> String {
    match ty {
        Ty::Map(k, _) => swift_type(k),
        _ => "Int64".into(),
    }
}

fn map_val_type(ty: &Ty) -> String {
    match ty {
        Ty::Map(_, v) => swift_type(v),
        _ => "Int64".into(),
    }
}

fn set_elem_type(ty: &Ty) -> String {
    match ty {
        Ty::Set(e) => swift_type(e),
        _ => "Int64".into(),
    }
}

/// Innermost `Place::Var` name at the bottom of a field/index chain.
fn place_root(p: &Place) -> &str {
    match p {
        Place::Var(n) => n,
        Place::Field { base, .. } | Place::Index { base, .. } => place_root(base),
    }
}

/// True when `name` must be a Swift `var` inside `stmts` — reassigned, field/
/// index mutated through it, MutBuiltin receiver, or forwarded as `inout`.
fn mutates_local(m: &IrModule, stmts: &[IrStmt], name: &str) -> bool {
    fn place_nested(m: &IrModule, p: &Place, name: &str) -> bool {
        match p {
            Place::Var(_) => false,
            Place::Field { base, .. } => place_nested(m, base, name),
            Place::Index { base, index, .. } => {
                place_nested(m, base, name) || expr_mutates(m, index, name)
            }
        }
    }
    fn expr_mutates(m: &IrModule, e: &IrExpr, name: &str) -> bool {
        match &e.kind {
            IrExprKind::List(xs)
            | IrExprKind::Tuple(xs)
            | IrExprKind::NewRecord { args: xs, .. }
            | IrExprKind::NewVariant { args: xs, .. }
            | IrExprKind::Builtin { args: xs, .. } => xs.iter().any(|x| expr_mutates(m, x, name)),
            IrExprKind::CallFunc { name: fname, args } => {
                if let Some(f) = m.func(fname) {
                    for (a, p) in args.iter().zip(&f.params) {
                        if p.inout && matches!(&a.kind, IrExprKind::Local(n) if n == name) {
                            return true;
                        }
                        if expr_mutates(m, a, name) {
                            return true;
                        }
                    }
                    args.iter()
                        .skip(f.params.len())
                        .any(|a| expr_mutates(m, a, name))
                } else {
                    args.iter().any(|a| expr_mutates(m, a, name))
                }
            }
            IrExprKind::CallValue { callee, args } => {
                expr_mutates(m, callee, name) || args.iter().any(|a| expr_mutates(m, a, name))
            }
            IrExprKind::MutBuiltin { recv, args, .. } => {
                place_root(recv) == name
                    || place_nested(m, recv, name)
                    || args.iter().any(|a| expr_mutates(m, a, name))
            }
            IrExprKind::GetField { recv, .. } => expr_mutates(m, recv, name),
            IrExprKind::Index { recv, index } => {
                expr_mutates(m, recv, name) || expr_mutates(m, index, name)
            }
            IrExprKind::Unary { operand, .. } => expr_mutates(m, operand, name),
            IrExprKind::Binary { lhs, rhs, .. } => {
                expr_mutates(m, lhs, name) || expr_mutates(m, rhs, name)
            }
            _ => false,
        }
    }
    stmts.iter().any(|s| match s {
        IrStmt::Assign {
            target,
            value,
            declares,
        } => {
            (!*declares && place_root(target) == name)
                || place_nested(m, target, name)
                || expr_mutates(m, value, name)
        }
        IrStmt::TupleAssign { targets, value, .. } => {
            targets.iter().any(|t| t == name) || expr_mutates(m, value, name)
        }
        IrStmt::Expr(e) => expr_mutates(m, e, name),
        IrStmt::If { arms, else_block } => {
            arms.iter()
                .any(|(c, b)| expr_mutates(m, c, name) || mutates_local(m, b, name))
                || else_block
                    .as_ref()
                    .is_some_and(|b| mutates_local(m, b, name))
        }
        IrStmt::While { cond, body } => {
            expr_mutates(m, cond, name) || mutates_local(m, body, name)
        }
        IrStmt::ForRange { from, to, body, .. } => {
            expr_mutates(m, from, name)
                || expr_mutates(m, to, name)
                || mutates_local(m, body, name)
        }
        IrStmt::ForIn { iter, body, .. } => {
            expr_mutates(m, iter, name) || mutates_local(m, body, name)
        }
        IrStmt::Match { scrutinee, arms } => {
            expr_mutates(m, scrutinee, name)
                || arms.iter().any(|a| mutates_local(m, &a.body, name))
        }
        IrStmt::Return(Some(e)) => expr_mutates(m, e, name),
        IrStmt::Assert { cond, .. } => expr_mutates(m, cond, name),
        IrStmt::ExpectTrap { body, .. } => mutates_local(m, body, name),
        IrStmt::Return(None) | IrStmt::Skip | IrStmt::Break | IrStmt::Continue => false,
    })
}

/// Conservative: true if evaluating `e` may throw a SudoTrap.
fn might_throw(e: &IrExpr) -> bool {
    match &e.kind {
        IrExprKind::CallFunc { args, .. } | IrExprKind::NewRecord { args, .. } | IrExprKind::NewVariant { args, .. } => {
            // Every sudo function throws.
            if matches!(&e.kind, IrExprKind::CallFunc { .. }) {
                return true;
            }
            args.iter().any(might_throw)
        }
        IrExprKind::CallValue { .. } => true,
        IrExprKind::Index { .. } => true,
        IrExprKind::Unary { op: UnaryOp::Neg, operand } => {
            matches!(&e.ty, Ty::Int) || might_throw(operand)
        }
        IrExprKind::Unary { operand, .. } => might_throw(operand),
        IrExprKind::Binary { op, lhs, rhs } => {
            let op_throws = matches!(&lhs.ty, Ty::Int)
                && matches!(
                    op,
                    BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul | BinaryOp::Div | BinaryOp::Mod
                );
            op_throws || might_throw(lhs) || might_throw(rhs)
        }
        IrExprKind::Builtin { builtin, args } => {
            let b_throws = matches!(
                builtin,
                Builtin::AbsInt
                    | Builtin::IntOfFloat
                    | Builtin::Filled
                    | Builtin::OptUnwrap
                    | Builtin::ResUnwrap
            );
            b_throws || args.iter().any(might_throw)
        }
        IrExprKind::MutBuiltin { builtin, args, .. } => {
            let b_throws = matches!(
                builtin,
                Builtin::ListPop
                    | Builtin::ListInsert
                    | Builtin::ListRemoveAt
                    | Builtin::ListSwap
            );
            b_throws || args.iter().any(might_throw)
        }
        IrExprKind::List(xs) | IrExprKind::Tuple(xs) => xs.iter().any(might_throw),
        IrExprKind::GetField { recv, .. } => might_throw(recv),
        _ => false,
    }
}

