"""Implementation of rules_sudo public rules. Load via //:defs.bzl only."""

load("@bazel_skylib//lib:paths.bzl", "paths")
load("@rules_python//python:defs.bzl", "PyInfo")

SudoInfo = provider(
    doc = "Transitive .sudo source files for a sudo_library target graph.",
    fields = {
        "transitive_srcs": "depset of File — this target's .sudo srcs plus every sudo_library dep's srcs, transitively",
    },
)

_SUDOC_ATTR = {
    "_sudoc": attr.label(
        default = Label("@sudo_toolchain//:sudoc"),
        executable = True,
        cfg = "exec",
        allow_single_file = True,
    ),
}

def _sudo_library_impl(ctx):
    direct = ctx.files.srcs
    transitive = [dep[SudoInfo].transitive_srcs for dep in ctx.attr.deps]
    all_srcs = depset(direct = direct, transitive = transitive)
    return [
        DefaultInfo(files = all_srcs),
        SudoInfo(transitive_srcs = all_srcs),
    ]

sudo_library = rule(
    implementation = _sudo_library_impl,
    doc = "A graph of .sudo sources (and their file-import deps).",
    attrs = {
        "srcs": attr.label_list(
            allow_files = [".sudo"],
            mandatory = True,
            doc = "This target's .sudo source files.",
        ),
        "deps": attr.label_list(
            providers = [SudoInfo],
            doc = "Other sudo_library targets whose sources this package imports (file imports only; std.* is embedded).",
        ),
    },
)

def _entry_module_name(entry):
    """Basename of entry with a trailing .sudo stripped, e.g. greet.sudo → greet."""
    base = entry.split("/")[-1]
    if base.endswith(".sudo"):
        return base[:-len(".sudo")]
    return base

def _sudo_build_library(ctx, target_lang, package_init = False):
    """Stage transitive .sudo srcs, run sudoc build, return the tree artifact.

    package_init (py only): also write __init__.py into the output tree in the
    same action so the directory is importable as a Python package.
    """
    sudoc = ctx.executable._sudoc
    all_srcs = ctx.attr.lib[SudoInfo].transitive_srcs
    out_dir = ctx.actions.declare_directory(ctx.label.name)
    entry = ctx.attr.entry
    stage = "_sudo_stage_{}".format(ctx.label.name)

    # Build a shell snippet that copies every transitive src by basename into
    # a flat staging dir (sudoc resolves file imports relative to the
    # importing file's directory — see spec/language.md §9).
    # Use a single run_shell; tree artifact output is never enumerated.
    copy_lines = []
    src_paths = []
    for f in all_srcs.to_list():
        src_paths.append(f.path)
        copy_lines.append(
            'cp "{src}" "{stage}/$(basename "{src}")"'.format(
                src = f.path,
                stage = stage,
            ),
        )

    entry_mod = _entry_module_name(entry)
    init_block = ""
    if package_init:
        # Exact shim content (entry module name substituted). Written in the
        # same action as sudoc build so out_dir remains a single output.
        init_block = """
cat > "{out}/__init__.py" << 'PYEOF'
\"\"\"Generated by rules_sudo — DO NOT EDIT BY HAND.

sudoc's generated Python modules import each other via bare top-level
module names, which only resolve when this directory is on sys.path.
This shim adds it before importing the host-facing entry module.
\"\"\"
import os
import sys

_here = os.path.dirname(__file__)
if _here not in sys.path:
    sys.path.insert(0, _here)

from . import {mod}  # noqa: E402,F401
PYEOF
""".format(out = out_dir.path, mod = entry_mod)

    command = """
set -euo pipefail
mkdir -p "{stage}"
{copies}
"{sudoc}" build --target {lang} -o "{out}" "{stage}/{entry}"
{init}
""".format(
        stage = stage,
        copies = "\n".join(copy_lines),
        sudoc = sudoc.path,
        lang = target_lang,
        out = out_dir.path,
        entry = entry.split("/")[-1],
        init = init_block,
    )

    ctx.actions.run_shell(
        inputs = all_srcs,
        outputs = [out_dir],
        tools = [sudoc],
        command = command,
        mnemonic = "SudoBuild",
        progress_message = "Building sudo %{{label}} (--target {})".format(target_lang),
    )
    return out_dir

def _sudo_py_library_impl(ctx):
    out_dir = _sudo_build_library(
        ctx,
        target_lang = "py",
        package_init = ctx.attr.package_init,
    )

    # Validated against rules_python 1.7.0 / Bazel 9.0.1: PyInfo.imports
    # entries are joined onto the runfiles root, which is one level above
    # the workspace/repo directory (e.g. _main/) that sources live under.
    # paths.dirname(out_dir.short_path) alone is NOT enough.
    import_root = paths.join(ctx.workspace_name, paths.dirname(out_dir.short_path))
    py_info = PyInfo(
        transitive_sources = depset([out_dir]),
        imports = depset([import_root]),
    )
    return [
        DefaultInfo(
            files = depset([out_dir]),
            runfiles = ctx.runfiles(files = [out_dir]),
        ),
        py_info,
    ]

sudo_py_library = rule(
    implementation = _sudo_py_library_impl,
    doc = "Compile a sudo_library graph to a generated Python package (tree artifact).",
    attrs = dict(_SUDOC_ATTR, **{
        "lib": attr.label(
            providers = [SudoInfo],
            mandatory = True,
            doc = "sudo_library whose transitive sources to compile.",
        ),
        "entry": attr.string(
            mandatory = True,
            doc = "Basename of the entry .sudo file within lib (e.g. \"greet.sudo\").",
        ),
        "package_init": attr.bool(
            default = True,
            doc = "If True, write an __init__.py shim into the output tree.",
        ),
    }),
)

def _sudo_js_library_impl(ctx):
    out_dir = _sudo_build_library(ctx, target_lang = "js", package_init = False)
    return [
        DefaultInfo(
            files = depset([out_dir]),
            runfiles = ctx.runfiles(files = [out_dir]),
        ),
    ]

sudo_js_library = rule(
    implementation = _sudo_js_library_impl,
    doc = "Compile a sudo_library graph to a generated JS module tree (tree artifact).",
    attrs = dict(_SUDOC_ATTR, **{
        "lib": attr.label(
            providers = [SudoInfo],
            mandatory = True,
            doc = "sudo_library whose transitive sources to compile.",
        ),
        "entry": attr.string(
            mandatory = True,
            doc = "Basename of the entry .sudo file within lib (e.g. \"greet.sudo\").",
        ),
    }),
)

def _rf_path(f):
    """Map File.short_path to a path under $TEST_SRCDIR / the runfiles root.

    Main-repo files use short_path like "sudo/greet.sudo" and live under
    $RUNFILES/$TEST_WORKSPACE/. External files use short_path like
    "../sudo_toolchain/sudoc_…" and live under $RUNFILES/sudo_toolchain/…
    (the leading "../" is not part of the runfiles layout).
    """
    sp = f.short_path
    if sp.startswith("../"):
        return ("external", sp[3:])
    return ("workspace", sp)

def _sudo_lockstep_test_impl(ctx):
    """Write a launcher that stages srcs at test runtime and execs sudoc test."""
    sudoc = ctx.executable._sudoc
    all_srcs = ctx.attr.lib[SudoInfo].transitive_srcs
    src_list = all_srcs.to_list()
    entry = ctx.attr.entry.split("/")[-1]
    target_flags = " ".join(["--target {}".format(t) for t in ctx.attr.targets])

    # tags=["local"] + env_inherit PATH (set by the public macro) so host
    # python3/node that sudoc test shells out to resolve.
    sudoc_kind, sudoc_rf = _rf_path(sudoc)

    # Bash launcher: resolve runfiles via TEST_SRCDIR (or $0.runfiles), stage
    # by basename, exec sudoc test so its exit code is the test result.
    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by sudo_lockstep_test — do not edit.",
        'if [[ -n "${TEST_SRCDIR:-}" ]]; then',
        '  RUNFILES="${TEST_SRCDIR}"',
        "elif [[ -d \"$(dirname \"$0\").runfiles\" ]]; then",
        '  RUNFILES="$(cd "$(dirname "$0").runfiles" && pwd)"',
        "elif [[ -d \"$(dirname \"$0\")/../\" ]]; then",
        # Some local layouts put the executable next to a runfiles dir named
        # after the workspace; fall back to walking up from $0.
        '  RUNFILES="$(cd "$(dirname "$0")" && pwd)"',
        "else",
        '  echo "sudo_lockstep_test: cannot locate runfiles" >&2',
        "  exit 1",
        "fi",
        'WS="${TEST_WORKSPACE:-_main}"',
        'rf() {',
        '  # $1 = workspace|external, $2 = path under that root',
        '  local kind="$1" rel="$2"',
        '  if [[ "$kind" == "external" ]]; then',
        '    echo "${RUNFILES}/${rel}"',
        "  else",
        '    if [[ -e "${RUNFILES}/${WS}/${rel}" ]]; then',
        '      echo "${RUNFILES}/${WS}/${rel}"',
        '    elif [[ -e "${RUNFILES}/${rel}" ]]; then',
        '      echo "${RUNFILES}/${rel}"',
        "    else",
        '      echo "${RUNFILES}/${WS}/${rel}"',
        "    fi",
        "  fi",
        "}",
        'SUDOC_BIN="$(rf "' + sudoc_kind + '" "' + sudoc_rf + '")"',
        'if [[ ! -x "$SUDOC_BIN" ]]; then',
        '  echo "sudo_lockstep_test: sudoc not executable at $SUDOC_BIN" >&2',
        "  exit 1",
        "fi",
        'STAGE="$(mktemp -d "${TEST_TMPDIR:-/tmp}/sudo_lockstep.XXXXXX")"',
        'trap \'rm -rf "$STAGE"\' EXIT',
    ]
    for f in src_list:
        kind, rel = _rf_path(f)
        base = f.basename
        lines.append(
            'cp "$(rf "' + kind + '" "' + rel + '")" "${STAGE}/' + base + '"',
        )
    lines.append(
        'exec "$SUDOC_BIN" test ' + target_flags + ' "${STAGE}/' + entry + '"',
    )

    ctx.actions.write(
        output = launcher,
        content = "\n".join(lines) + "\n",
        is_executable = True,
    )

    runfiles = ctx.runfiles(files = src_list + [sudoc, launcher])
    runfiles = runfiles.merge(ctx.attr._sudoc[DefaultInfo].default_runfiles)

    return [
        DefaultInfo(
            executable = launcher,
            runfiles = runfiles,
        ),
        RunEnvironmentInfo(
            inherited_environment = ctx.attr.env_inherit,
        ),
    ]

_sudo_lockstep_raw_test = rule(
    implementation = _sudo_lockstep_test_impl,
    test = True,
    doc = "Run sudoc test over a staged sudo_library graph (host interpreters; local).",
    attrs = dict(_SUDOC_ATTR, **{
        "lib": attr.label(
            providers = [SudoInfo],
            mandatory = True,
        ),
        "entry": attr.string(mandatory = True),
        "targets": attr.string_list(default = ["py", "js"]),
        "env_inherit": attr.string_list(default = []),
    }),
)

def sudo_lockstep_test(name, lib, entry, targets = ["py", "js"], **kwargs):
    """Macro wrapping the lockstep test rule.

    Always injects tags=["local"] and env_inherit=["PATH"] so sudoc test can
    find host python3/node. env_inherit is a common test attribute on Bazel
    test rules (same pattern as native.sh_test / py_test) but is not settable
    as a rule() attr default in a portable way for custom test rules on all
    Bazel versions — the macro is the reliable pattern (mirrors
    infinite-craft-cli's parity tests). Callers may pass additional tags via
    kwargs; "local" is always included.
    """
    tags = list(kwargs.pop("tags", []))
    if "local" not in tags:
        tags.append("local")
    env_inherit = list(kwargs.pop("env_inherit", []))
    if "PATH" not in env_inherit:
        env_inherit.append("PATH")
    _sudo_lockstep_raw_test(
        name = name,
        lib = lib,
        entry = entry,
        targets = targets,
        tags = tags,
        env_inherit = env_inherit,
        **kwargs
    )
