//! Rust backend: typed IR → readable Rust 2021 (single `rustc` invocation).
//!
//! Value semantics (Rust-specific): clone at every owning consumption of an
//! aliasing composite read — assignment RHS, constructor args, container
//! inserts, returns, and non-inout call arguments. Params are owned `T`;
//! inout params are `&mut T` (native writeback, no return-tuple threading).
//! Enums are included in `needs_dup` (departure from JS) because Rust moves
//! enum locals; cloning is the safe portable rule without last-use analysis.

use std::collections::HashSet;

use sudoc_ir::{
    BinaryOp, Builtin, IrExpr, IrExprKind, IrFunc, IrModule, IrPattern, IrStmt, Place, Ty,
    UnaryOp,
};

/// The shared Rust runtime, written alongside every generated module.
pub const RUNTIME: &str = include_str!("runtime/sudo_rt.rs");
pub const RUNTIME_FILE: &str = "sudo_rt.rs";

/// File name of a generated module (`{name}.rs`).
pub fn module_file(module: &str) -> String {
    format!("{module}.rs")
}

/// Emit a Rust module for the IR. When `with_tests` is set (entry only),
/// `test` blocks become `test_*` functions plus a `main` that runs them.
pub fn emit(module: &IrModule, with_tests: bool, is_entry: bool) -> String {
    Emitter {
        m: module,
        out: String::new(),
        inout_params: HashSet::new(),
        is_entry,
    }
    .run(with_tests)
}

struct Emitter<'a> {
    m: &'a IrModule,
    out: String,
    inout_params: HashSet<String>,
    is_entry: bool,
}

impl Emitter<'_> {
    fn run(mut self, with_tests: bool) -> String {
        if self.is_entry {
            self.line(
                0,
                "#![allow(unused, dead_code, non_snake_case, non_camel_case_types, unused_mut, unused_assignments, unused_variables, clippy::all)]",
            );
        }
        self.line(
            0,
            &format!(
                "// Generated by sudoc from {}.sudo — do not edit; edit the sudo source.",
                self.m.name
            ),
        );
        if self.is_entry {
            self.line(0, "mod sudo_rt;");
        }
        for dep in &self.m.imports {
            self.line(0, &format!("#[path = \"{dep}.rs\"]"));
            self.line(0, &format!("mod {dep};"));
        }
        self.blank();

        for r in &self.m.records {
            self.emit_record(r);
            self.blank();
        }
        for e in &self.m.enums {
            self.emit_enum(e);
            self.blank();
        }
        for c in &self.m.consts {
            let ty = ty_str(&c.ty);
            let value = self.expr(&c.value);
            self.line(0, &format!("pub(crate) const {}: {ty} = {value};", c.name));
        }
        if !self.m.consts.is_empty() {
            self.blank();
        }

        for f in &self.m.funcs {
            self.func(f);
            self.blank();
        }

        if with_tests {
            let names = sudoc_ir::names::test_fn_names(&self.m.tests);
            for (t, name) in self.m.tests.iter().zip(&names) {
                self.inout_params.clear();
                self.line(0, &format!("fn {name}() {{"));
                if !t.body.is_empty() {
                    self.block(&t.body, 1);
                }
                self.line(0, "}");
                self.blank();
            }
            self.line(0, "fn main() {");
            let pairs: Vec<String> = names.iter().map(|n| format!("(\"{n}\", {n})")).collect();
            self.line(
                1,
                &format!(
                    "let code = crate::sudo_rt::run_tests(&[{}]);",
                    pairs.join(", ")
                ),
            );
            self.line(1, "std::process::exit(code);");
            self.line(0, "}");
        }
        self.out
    }

    fn emit_record(&mut self, r: &sudoc_ir::IrRecord) {
        let hashable = type_is_hashable(&Ty::Record(r.name.clone()), self.m, &mut Vec::new());
        let derives = if hashable {
            "Clone, PartialEq, Eq, Hash"
        } else {
            "Clone, PartialEq"
        };
        self.line(0, &format!("#[derive({derives})]"));
        self.line(0, &format!("pub(crate) struct {} {{", r.name));
        for (fname, fty) in &r.fields {
            self.line(1, &format!("pub(crate) {fname}: {},", ty_str(fty)));
        }
        self.line(0, "}");
        // SudoCanon for assert diagnostics.
        self.line(0, &format!("impl crate::sudo_rt::SudoCanon for {} {{", r.name));
        self.line(1, "fn canon(&self) -> String {");
        let field_canons: Vec<String> = r
            .fields
            .iter()
            .map(|(f, _)| format!("crate::sudo_rt::canon(&self.{f})"))
            .collect();
        if field_canons.is_empty() {
            self.line(
                2,
                &format!("\"{{\\\"r\\\": \\\"{}\\\"}}\".to_string()", r.name),
            );
        } else {
            // Concat — no nested format! (brace-escaping across codegen levels is fragile).
            let prefix = format!("{{\"r\": \"{}\", \"v\": [", r.name);
            self.line(
                2,
                &format!(
                    "[\"{}\".to_string(), [{}].join(\", \"), \"]}}\".to_string()].concat()",
                    escape_rust_string(&prefix),
                    field_canons.join(", ")
                ),
            );
        }
        self.line(1, "}");
        self.line(0, "}");
    }

    fn emit_enum(&mut self, e: &sudoc_ir::IrEnum) {
        let hashable = type_is_hashable(&Ty::Enum(e.name.clone()), self.m, &mut Vec::new());
        let derives = if hashable {
            "Clone, PartialEq, Eq, Hash"
        } else {
            "Clone, PartialEq"
        };
        self.line(0, &format!("#[derive({derives})]"));
        self.line(0, &format!("pub(crate) enum {} {{", e.name));
        for v in &e.variants {
            if v.fields.is_empty() {
                self.line(1, &format!("{},", v.name));
            } else {
                let fields: Vec<String> = v
                    .fields
                    .iter()
                    .map(|(n, t)| {
                        let ts = if boxed_in_payload(t) {
                            format!("Box<{}>", ty_str(t))
                        } else {
                            ty_str(t)
                        };
                        format!("{n}: {ts}")
                    })
                    .collect();
                self.line(1, &format!("{} {{ {} }},", v.name, fields.join(", ")));
            }
        }
        self.line(0, "}");
        // SudoCanon
        self.line(0, &format!("impl crate::sudo_rt::SudoCanon for {} {{", e.name));
        self.line(1, "fn canon(&self) -> String {");
        self.line(2, "match self {");
        for v in &e.variants {
            if v.fields.is_empty() {
                self.line(
                    3,
                    &format!(
                        "Self::{} => \"{{\\\"e\\\": \\\"{}.{}\\\"}}\".to_string(),",
                        v.name, e.name, v.name
                    ),
                );
            } else {
                let binders: Vec<String> = v.fields.iter().map(|(n, _)| n.clone()).collect();
                let pattern = binders.join(", ");
                let canons: Vec<String> = v
                    .fields
                    .iter()
                    .map(|(n, t)| {
                        if boxed_in_payload(t) {
                            format!("crate::sudo_rt::canon({n}.as_ref())")
                        } else {
                            format!("crate::sudo_rt::canon({n})")
                        }
                    })
                    .collect();
                // Concat — no nested format! (same as record canon).
                let prefix = format!("{{\"e\": \"{}.{}\", \"v\": [", e.name, v.name);
                self.line(
                    3,
                    &format!(
                        "Self::{} {{ {} }} => [\"{}\".to_string(), [{}].join(\", \"), \"]}}\".to_string()].concat(),",
                        v.name,
                        pattern,
                        escape_rust_string(&prefix),
                        canons.join(", ")
                    ),
                );
            }
        }
        self.line(2, "}");
        self.line(1, "}");
        self.line(0, "}");
    }

    fn func(&mut self, f: &IrFunc) {
        self.inout_params = f
            .params
            .iter()
            .filter(|p| p.inout)
            .map(|p| p.name.clone())
            .collect();

        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                if p.inout {
                    format!("{}: &mut {}", p.name, ty_str(&p.ty))
                } else {
                    // mut so local reassignment / method mutation of owned copy works
                    format!("mut {}: {}", p.name, ty_str(&p.ty))
                }
            })
            .collect();
        let ret = match &f.ret {
            Some(t) => format!(" -> {}", ty_str(t)),
            None => String::new(),
        };
        self.line(
            0,
            &format!("pub(crate) fn {}({}){ret} {{", f.name, params.join(", ")),
        );
        self.block(&f.body, 1);
        self.line(0, "}");
    }

    fn block(&mut self, stmts: &[IrStmt], depth: usize) {
        for s in stmts {
            self.stmt(s, depth);
        }
    }

    fn stmt(&mut self, s: &IrStmt, depth: usize) {
        match s {
            IrStmt::Assign {
                target,
                value,
                declares,
            } => {
                let v = self.store(value);
                self.assign_to_place(target, &v, depth, *declares, &value.ty);
            }
            IrStmt::TupleAssign {
                targets,
                declares,
                value,
            } => {
                let v = self.store(value);
                let all_declare = declares.iter().all(|d| *d);
                let any_declare = declares.iter().any(|d| *d);
                if all_declare {
                    let muts: Vec<String> =
                        targets.iter().map(|t| format!("mut {t}")).collect();
                    self.line(depth, &format!("let ({}) = {v};", muts.join(", ")));
                } else if !any_declare {
                    // Reassign existing vars via temporary.
                    let tmps: Vec<String> = (0..targets.len())
                        .map(|i| format!("_sudo_t{i}"))
                        .collect();
                    self.line(depth, &format!("let ({}) = {v};", tmps.join(", ")));
                    for (t, tmp) in targets.iter().zip(&tmps) {
                        if self.inout_params.contains(t) {
                            self.line(depth, &format!("*{t} = {tmp};"));
                        } else {
                            self.line(depth, &format!("{t} = {tmp};"));
                        }
                    }
                } else {
                    let tmps: Vec<String> = (0..targets.len())
                        .map(|i| format!("_sudo_t{i}"))
                        .collect();
                    self.line(depth, &format!("let ({}) = {v};", tmps.join(", ")));
                    for ((t, d), tmp) in targets.iter().zip(declares.iter()).zip(&tmps) {
                        if *d {
                            self.line(depth, &format!("let mut {t} = {tmp};"));
                        } else if self.inout_params.contains(t) {
                            self.line(depth, &format!("*{t} = {tmp};"));
                        } else {
                            self.line(depth, &format!("{t} = {tmp};"));
                        }
                    }
                }
            }
            IrStmt::Expr(e) => {
                let code = self.expr(e);
                self.line(depth, &format!("{code};"));
            }
            IrStmt::If { arms, else_block } => {
                for (i, (cond, body)) in arms.iter().enumerate() {
                    let c = self.expr(cond);
                    if i == 0 {
                        self.line(depth, &format!("if {c} {{"));
                    } else {
                        self.line(depth, &format!("}} else if {c} {{"));
                    }
                    self.block(body, depth + 1);
                }
                if let Some(body) = else_block {
                    self.line(depth, "} else {");
                    self.block(body, depth + 1);
                    self.line(depth, "}");
                } else if !arms.is_empty() {
                    self.line(depth, "}");
                }
            }
            IrStmt::While { cond, body } => {
                let c = self.expr(cond);
                self.line(depth, &format!("while {c} {{"));
                self.block(body, depth + 1);
                self.line(depth, "}");
            }
            IrStmt::ForRange {
                var,
                from,
                to,
                down,
                body,
            } => {
                let f = self.expr(from);
                let t = self.expr(to);
                let from_tmp = format!("_sudo_from_{var}");
                let to_tmp = format!("_sudo_to_{var}");
                self.line(depth, &format!("let {from_tmp}: i64 = {f};"));
                self.line(depth, &format!("let {to_tmp}: i64 = {t};"));
                if *down {
                    self.line(
                        depth,
                        &format!(
                            "for _sudo_i128 in (({to_tmp} as i128)..=({from_tmp} as i128)).rev() {{"
                        ),
                    );
                } else {
                    self.line(
                        depth,
                        &format!(
                            "for _sudo_i128 in ({from_tmp} as i128)..=({to_tmp} as i128) {{"
                        ),
                    );
                }
                self.line(depth + 1, &format!("let mut {var}: i64 = _sudo_i128 as i64;"));
                self.block(body, depth + 1);
                self.line(depth, "}");
            }
            IrStmt::ForIn { vars, iter, body } => {
                let it = self.expr(iter);
                match strip(&iter.ty) {
                    Ty::List(_) | Ty::Set(_) => {
                        self.line(
                            depth,
                            &format!("for mut {} in ({it}).clone().into_iter() {{", vars[0]),
                        );
                    }
                    Ty::Map(..) if vars.len() >= 2 => {
                        self.line(
                            depth,
                            &format!(
                                "for (mut {}, mut {}) in ({it}).clone().into_iter() {{",
                                vars[0], vars[1]
                            ),
                        );
                    }
                    Ty::Map(..) => {
                        self.line(
                            depth,
                            &format!("for mut {} in ({it}).clone().into_iter() {{", vars[0]),
                        );
                    }
                    _ => {
                        self.line(
                            depth,
                            &format!("for mut {} in ({it}).clone().into_iter() {{", vars[0]),
                        );
                    }
                }
                self.block(body, depth + 1);
                self.line(depth, "}");
            }
            IrStmt::Match { scrutinee, arms } => {
                let sc = self.store(scrutinee);
                self.line(depth, &format!("let _sudo_sc = {sc};"));
                self.line(depth, "match _sudo_sc {");
                for arm in arms {
                    let (pat, unboxes) = self.pattern_and_unboxes(&arm.pattern);
                    self.line(depth + 1, &format!("{pat} => {{"));
                    for u in unboxes {
                        self.line(depth + 2, &u);
                    }
                    self.block(&arm.body, depth + 2);
                    self.line(depth + 1, "}");
                }
                self.line(depth, "}");
            }
            IrStmt::Return(v) => {
                if let Some(v) = v {
                    let code = self.store(v);
                    self.line(depth, &format!("return {code};"));
                } else {
                    self.line(depth, "return;");
                }
            }
            IrStmt::Assert { cond, line } => {
                if let IrExprKind::Binary {
                    op: BinaryOp::Eq,
                    lhs,
                    rhs,
                } = &cond.kind
                {
                    let l = self.expr(lhs);
                    let r = self.expr(rhs);
                    self.line(
                        depth,
                        &format!(
                            "crate::sudo_rt::sudo_assert_eq(&({l}), &({r}), {line});"
                        ),
                    );
                } else {
                    let c = self.expr(cond);
                    self.line(
                        depth,
                        &format!("crate::sudo_rt::sudo_assert({c}, {line});"),
                    );
                }
            }
            IrStmt::Skip => {}
            IrStmt::Break => self.line(depth, "break;"),
            IrStmt::Continue => self.line(depth, "continue;"),
            IrStmt::ExpectTrap { kind, body, line } => {
                self.line(
                    depth,
                    "let _sudo_trap_result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {",
                );
                self.block(body, depth + 1);
                self.line(depth, "}));");
                self.line(depth, "match _sudo_trap_result {");
                self.line(depth + 1, "Ok(()) => {");
                self.line(
                    depth + 2,
                    &format!(
                        "crate::sudo_rt::expect_trap_failed({line}, \"{kind}\", None);"
                    ),
                );
                self.line(depth + 1, "}");
                self.line(depth + 1, "Err(_sudo_payload) => {");
                self.line(
                    depth + 2,
                    "let _sudo_got = crate::sudo_rt::trap_kind_of(_sudo_payload.as_ref());",
                );
                self.line(
                    depth + 2,
                    &format!("if _sudo_got != Some(\"{kind}\") {{"),
                );
                self.line(
                    depth + 3,
                    &format!(
                        "crate::sudo_rt::expect_trap_failed({line}, \"{kind}\", _sudo_got);"
                    ),
                );
                self.line(depth + 2, "}");
                self.line(depth + 1, "}");
                self.line(depth, "}");
            }
        }
    }

    /// Returns (match pattern, unbox statements for boxed payload binders).
    fn pattern_and_unboxes(&self, p: &IrPattern) -> (String, Vec<String>) {
        match p {
            IrPattern::Int(v) => (format!("{v}"), Vec::new()),
            IrPattern::Bool(true) => ("true".into(), Vec::new()),
            IrPattern::Bool(false) => ("false".into(), Vec::new()),
            IrPattern::Wildcard => ("_".into(), Vec::new()),
            IrPattern::Variant {
                enum_name,
                variant,
                binders,
            } => match (enum_name.as_str(), variant.as_str()) {
                ("Option", "Some") => {
                    let b = binders.first().map(|s| s.as_str()).unwrap_or("_");
                    (format!("Some({b})"), Vec::new())
                }
                ("Option", "None") => ("None".into(), Vec::new()),
                ("Result", "Ok") => {
                    let b = binders.first().map(|s| s.as_str()).unwrap_or("_");
                    (format!("Ok({b})"), Vec::new())
                }
                ("Result", "Err") => {
                    let b = binders.first().map(|s| s.as_str()).unwrap_or("_");
                    (format!("Err({b})"), Vec::new())
                }
                _ => {
                    let fields = self
                        .m
                        .enum_(enum_name)
                        .and_then(|e| e.variants.iter().find(|v| v.name == *variant))
                        .map(|v| v.fields.clone())
                        .unwrap_or_default();
                    if fields.is_empty() {
                        (
                            format!("{enum_name}::{variant}"),
                            Vec::new(),
                        )
                    } else {
                        let mut pats = Vec::new();
                        let mut unboxes = Vec::new();
                        for (i, (fname, fty)) in fields.iter().enumerate() {
                            let binder = binders
                                .get(i)
                                .map(|s| s.as_str())
                                .unwrap_or("_");
                            if binder == "_" {
                                pats.push(format!("{fname}: _"));
                            } else if boxed_in_payload(fty) {
                                // Bind Box, then unbox into binder name.
                                let tmp = format!("_sudo_box_{binder}");
                                pats.push(format!("{fname}: {tmp}"));
                                unboxes.push(format!("let {binder} = *{tmp};"));
                            } else {
                                pats.push(format!("{fname}: {binder}"));
                            }
                        }
                        (
                            format!("{enum_name}::{variant} {{ {} }}", pats.join(", ")),
                            unboxes,
                        )
                    }
                }
            },
        }
    }

    fn assign_to_place(
        &mut self,
        place: &Place,
        value: &str,
        depth: usize,
        declares: bool,
        value_ty: &Ty,
    ) {
        match place {
            Place::Var(n) => {
                if declares {
                    // Always annotate so empty vec![] / HashMap::new() infer.
                    self.line(
                        depth,
                        &format!("let mut {n}: {} = {value};", ty_str(value_ty)),
                    );
                } else if self.inout_params.contains(n) {
                    self.line(depth, &format!("*{n} = {value};"));
                } else {
                    self.line(depth, &format!("{n} = {value};"));
                }
            }
            Place::Index {
                base,
                base_ty,
                index,
            } => {
                // Materialize non-base operands first, then take &mut last.
                // Free-function &mut args do not get Rust two-phase borrows
                // (e.g. put(&mut a, i, at(&a, j)) is E0502).
                match strip(base_ty) {
                    Ty::Map(..) => {
                        let k = self.store(index);
                        self.line(depth, &format!("let _sudo_k = {k};"));
                        self.line(depth, &format!("let _sudo_v = {value};"));
                        let b = self.place_path(base);
                        self.line(depth, &format!("{b}.insert(_sudo_k, _sudo_v);"));
                    }
                    _ => {
                        let i = self.expr(index);
                        self.line(depth, &format!("let _sudo_idx = {i};"));
                        self.line(depth, &format!("let _sudo_val = {value};"));
                        let br = self.as_mut_ref(base);
                        self.line(
                            depth,
                            &format!("crate::sudo_rt::put({br}, _sudo_idx, _sudo_val);"),
                        );
                    }
                }
            }
            Place::Field { base, name, .. } => {
                let b = self.place_path(base);
                self.line(depth, &format!("{b}.{name} = {value};"));
            }
        }
    }

    /// Path usable as `path.field` / `path.push` (auto-deref for &mut params).
    fn place_path(&mut self, place: &Place) -> String {
        match place {
            Place::Var(n) => n.clone(),
            Place::Field { base, name, .. } => {
                format!("{}.{name}", self.place_path(base))
            }
            Place::Index {
                base,
                base_ty,
                index,
            } => {
                let br = self.as_mut_ref(base);
                let i = self.expr(index);
                match strip(base_ty) {
                    Ty::Map(..) => {
                        format!("(*crate::sudo_rt::map_get_mut({br}, &({i})))")
                    }
                    _ => format!("(*crate::sudo_rt::at_mut({br}, {i}))"),
                }
            }
        }
    }

    /// Expression of type `&mut T` for the place.
    fn as_mut_ref(&mut self, place: &Place) -> String {
        match place {
            Place::Var(n) if self.inout_params.contains(n) => n.clone(),
            Place::Var(n) => format!("&mut {n}"),
            Place::Field { base, name, .. } => {
                // &mut base.field — works when base is local or &mut param path.
                match base.as_ref() {
                    Place::Var(n) if self.inout_params.contains(n) => {
                        format!("&mut {n}.{name}")
                    }
                    Place::Var(n) => format!("&mut {n}.{name}"),
                    _ => format!("&mut {}.{}", self.place_path(base), name),
                }
            }
            Place::Index {
                base,
                base_ty,
                index,
            } => {
                let br = self.as_mut_ref(base);
                let i = self.expr(index);
                match strip(base_ty) {
                    Ty::Map(..) => format!("crate::sudo_rt::map_get_mut({br}, &({i}))"),
                    _ => format!("crate::sudo_rt::at_mut({br}, {i})"),
                }
            }
        }
    }

    /// Mutable place path for an inout call argument expression.
    fn mut_arg_path(&mut self, e: &IrExpr) -> String {
        match &e.kind {
            IrExprKind::Local(n) => {
                if self.inout_params.contains(n) {
                    n.clone()
                } else {
                    format!("&mut {n}")
                }
            }
            IrExprKind::GetField { recv, name } => {
                // Build place-like path
                match &recv.kind {
                    IrExprKind::Local(n) if self.inout_params.contains(n) => {
                        format!("&mut {n}.{name}")
                    }
                    IrExprKind::Local(n) => format!("&mut {n}.{name}"),
                    IrExprKind::GetField { .. } => {
                        let base = self.mut_arg_path(recv);
                        // base is &mut T; field: need &mut (*base).field or restructure
                        // If base starts with &mut, strip and extend path.
                        if let Some(rest) = base.strip_prefix("&mut ") {
                            format!("&mut {rest}.{name}")
                        } else {
                            // already &mut from inout param name
                            format!("&mut {base}.{name}")
                        }
                    }
                    _ => {
                        let r = self.expr(recv);
                        format!("&mut {r}.{name}")
                    }
                }
            }
            _ => {
                // Fallback: shouldn't happen (checker guarantees place).
                let c = self.expr(e);
                format!("&mut {c}")
            }
        }
    }

    fn store(&mut self, e: &IrExpr) -> String {
        let code = self.expr(e);
        if aliasing(&e.kind) && needs_dup(&e.ty) {
            // Inout locals already produce (*n) which can clone.
            format!("({code}).clone()")
        } else {
            code
        }
    }

    fn expr(&mut self, e: &IrExpr) -> String {
        self.expr_prec(e, 0)
    }

    /// Emit with parentheses if this expression binds looser than `ctx`.
    ///
    /// Rust precedence (low → high), relevant subset:
    ///   1 = `||`, 2 = `&&`, 3 = comparisons (all six, non-associative),
    ///   4 = `+`/`-`, 5 = `*`/`/`/`%`, 6 = unary `!`/`-`, 9 = atom.
    fn expr_prec(&mut self, e: &IrExpr, ctx: u8) -> String {
        let (code, prec) = self.expr_raw(e);
        if prec < ctx {
            format!("({code})")
        } else {
            code
        }
    }

    fn expr_raw(&mut self, e: &IrExpr) -> (String, u8) {
        let atom = 9u8;
        match &e.kind {
            IrExprKind::Int(v) => {
                if *v == i64::MIN {
                    ("i64::MIN".into(), atom)
                } else if *v < 0 {
                    (format!("{v}i64"), 6)
                } else {
                    (format!("{v}i64"), atom)
                }
            }
            IrExprKind::Float(v) => {
                let s = rust_float_lit(*v);
                let prec = if s.starts_with('-') { 6 } else { atom };
                (s, prec)
            }
            IrExprKind::Bool(v) => (if *v { "true" } else { "false" }.into(), atom),
            IrExprKind::Text(s) => {
                let items: Vec<String> = s.iter().map(|c| format!("{c}i64")).collect();
                (
                    format!("crate::sudo_rt::text(&[{}])", items.join(", ")),
                    atom,
                )
            }
            IrExprKind::Local(n) => {
                if self.inout_params.contains(n) {
                    // *n for values; works for scalars and as auto-deref base for methods.
                    (format!("(*{n})"), atom)
                } else {
                    (n.clone(), atom)
                }
            }
            IrExprKind::Const(n) | IrExprKind::FuncRef(n) => (qual_name(n), atom),
            IrExprKind::List(xs) => {
                let items: Vec<String> = xs.iter().map(|x| self.store(x)).collect();
                (format!("vec![{}]", items.join(", ")), atom)
            }
            IrExprKind::Tuple(xs) => {
                let items: Vec<String> = xs.iter().map(|x| self.store(x)).collect();
                if items.len() == 1 {
                    (format!("({},)", items[0]), atom)
                } else {
                    (format!("({})", items.join(", ")), atom)
                }
            }
            IrExprKind::CallFunc { name, args } => {
                let fname = qual_name(name);
                if let Some(f) = self.m.func(name) {
                    let has_inout = f.params.iter().any(|p| p.inout);
                    if has_inout {
                        // Materialize non-inout args first; take &mut last (E0502).
                        let mut preamble = String::new();
                        let mut call_args: Vec<String> = Vec::new();
                        for (i, (arg, p)) in args.iter().zip(&f.params).enumerate() {
                            if p.inout {
                                call_args.push(String::new()); // filled after
                            } else {
                                let tmp = format!("_sudo_ca{i}");
                                let v = self.store(arg);
                                preamble.push_str(&format!("let {tmp} = {v}; "));
                                call_args.push(tmp);
                            }
                        }
                        for (i, (arg, p)) in args.iter().zip(&f.params).enumerate() {
                            if p.inout {
                                call_args[i] = self.mut_arg_path(arg);
                            }
                        }
                        (
                            format!(
                                "{{ {preamble}{fname}({}) }}",
                                call_args.join(", ")
                            ),
                            atom,
                        )
                    } else {
                        let a: Vec<String> = args.iter().map(|x| self.store(x)).collect();
                        (format!("{fname}({})", a.join(", ")), atom)
                    }
                } else {
                    let a: Vec<String> = args.iter().map(|x| self.store(x)).collect();
                    (format!("{fname}({})", a.join(", ")), atom)
                }
            }
            IrExprKind::CallValue { callee, args } => {
                let c = self.expr_prec(callee, atom);
                let a: Vec<String> = args.iter().map(|x| self.store(x)).collect();
                (format!("{c}({})", a.join(", ")), atom)
            }
            IrExprKind::NewRecord { name, args } => {
                let fields = self
                    .m
                    .record(name)
                    .map(|r| r.fields.clone())
                    .unwrap_or_default();
                let parts: Vec<String> = fields
                    .iter()
                    .zip(args.iter())
                    .map(|((fname, _), arg)| format!("{fname}: {}", self.store(arg)))
                    .collect();
                (format!("{name} {{ {} }}", parts.join(", ")), atom)
            }
            IrExprKind::NewVariant {
                enum_name,
                variant,
                args,
            } => {
                let code = match (enum_name.as_str(), variant.as_str()) {
                    ("Option", "Some") => {
                        format!("Some({})", self.store(&args[0]))
                    }
                    ("Option", "None") => "None".into(),
                    ("Result", "Ok") => format!("Ok({})", self.store(&args[0])),
                    ("Result", "Err") => format!("Err({})", self.store(&args[0])),
                    _ => {
                        let fields = self
                            .m
                            .enum_(enum_name)
                            .and_then(|e| e.variants.iter().find(|v| v.name == *variant))
                            .map(|v| v.fields.clone())
                            .unwrap_or_default();
                        if fields.is_empty() {
                            format!("{enum_name}::{variant}")
                        } else {
                            let parts: Vec<String> = fields
                                .iter()
                                .zip(args.iter())
                                .map(|((fname, fty), arg)| {
                                    let v = self.store(arg);
                                    if boxed_in_payload(fty) {
                                        format!("{fname}: Box::new({v})")
                                    } else {
                                        format!("{fname}: {v}")
                                    }
                                })
                                .collect();
                            format!("{enum_name}::{variant} {{ {} }}", parts.join(", "))
                        }
                    }
                };
                (code, atom)
            }
            IrExprKind::Builtin { builtin, args } => (self.builtin(*builtin, args), atom),
            IrExprKind::MutBuiltin {
                builtin,
                recv,
                recv_ty,
                args,
            } => (
                self.mut_builtin_ty(*builtin, recv, recv_ty, args),
                atom,
            ),
            IrExprKind::GetField { recv, name } => {
                let r = self.expr_prec(recv, atom);
                (format!("{r}.{name}"), atom)
            }
            IrExprKind::Index { recv, index } => {
                let r = self.expr_prec(recv, atom);
                let i = self.expr(index);
                match strip(&recv.ty) {
                    Ty::Map(..) => (
                        format!("crate::sudo_rt::map_get(&({r}), &({i}))"),
                        atom,
                    ),
                    _ => (format!("crate::sudo_rt::at(&({r}), {i})"), atom),
                }
            }
            IrExprKind::Unary { op, operand } => match op {
                UnaryOp::Neg => match strip(&e.ty) {
                    Ty::Int => {
                        let x = self.expr(operand);
                        (format!("crate::sudo_rt::neg({x})"), atom)
                    }
                    _ => {
                        let x = self.expr_prec(operand, 6);
                        (format!("-{x}"), 6)
                    }
                },
                UnaryOp::Not => {
                    let x = self.expr_prec(operand, 6);
                    (format!("!{x}"), 6)
                }
            },
            IrExprKind::Binary { op, lhs, rhs } => self.binary(*op, lhs, rhs, &e.ty),
        }
    }

    fn binary(
        &mut self,
        op: BinaryOp,
        lhs: &IrExpr,
        rhs: &IrExpr,
        result_ty: &Ty,
    ) -> (String, u8) {
        let is_int = matches!(strip(&lhs.ty), Ty::Int);
        let is_float = matches!(strip(&lhs.ty), Ty::Float);
        match op {
            BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul => {
                if is_int {
                    let l = self.expr(lhs);
                    let r = self.expr(rhs);
                    let f = match op {
                        BinaryOp::Add => "chk_add",
                        BinaryOp::Sub => "chk_sub",
                        _ => "chk_mul",
                    };
                    (format!("crate::sudo_rt::{f}({l}, {r})"), 9)
                } else if is_float {
                    let prec = if matches!(op, BinaryOp::Mul) { 5 } else { 4 };
                    let sym = match op {
                        BinaryOp::Add => "+",
                        BinaryOp::Sub => "-",
                        _ => "*",
                    };
                    let l = self.expr_prec(lhs, prec);
                    let r = self.expr_prec(rhs, prec + 1);
                    (format!("{l} {sym} {r}"), prec)
                } else {
                    // List concatenation.
                    let l = self.expr(lhs);
                    let r = self.expr(rhs);
                    let _ = result_ty;
                    (
                        format!("crate::sudo_rt::list_concat(&({l}), &({r}))"),
                        9,
                    )
                }
            }
            BinaryOp::Div => {
                let l = self.expr(lhs);
                let r = self.expr(rhs);
                if is_int {
                    (format!("crate::sudo_rt::div({l}, {r})"), 9)
                } else {
                    (format!("crate::sudo_rt::fdiv({l}, {r})"), 9)
                }
            }
            BinaryOp::Mod => {
                let l = self.expr(lhs);
                let r = self.expr(rhs);
                (format!("crate::sudo_rt::mod_i64({l}, {r})"), 9)
            }
            BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge => {
                let sym = match op {
                    BinaryOp::Lt => "<",
                    BinaryOp::Le => "<=",
                    BinaryOp::Gt => ">",
                    _ => ">=",
                };
                // Comparisons are non-associative in Rust; force child prec > 3.
                let l = self.expr_prec(lhs, 4);
                let r = self.expr_prec(rhs, 4);
                (format!("{l} {sym} {r}"), 3)
            }
            BinaryOp::Eq | BinaryOp::Ne => {
                let sym = if op == BinaryOp::Eq { "==" } else { "!=" };
                let l = self.expr_prec(lhs, 4);
                let r = self.expr_prec(rhs, 4);
                (format!("{l} {sym} {r}"), 3)
            }
            BinaryOp::And => {
                let l = self.expr_prec(lhs, 2);
                let r = self.expr_prec(rhs, 3);
                (format!("{l} && {r}"), 2)
            }
            BinaryOp::Or => {
                let l = self.expr_prec(lhs, 1);
                let r = self.expr_prec(rhs, 2);
                (format!("{l} || {r}"), 1)
            }
        }
    }

    fn builtin(&mut self, b: Builtin, args: &[IrExpr]) -> String {
        let a = |s: &mut Self, i: usize| s.expr(&args[i]);
        match b {
            Builtin::AbsInt => format!("crate::sudo_rt::abs_i64({})", a(self, 0)),
            Builtin::AbsFloat => format!("({}).abs()", a(self, 0)),
            Builtin::MinInt => {
                format!("std::cmp::min({}, {})", a(self, 0), a(self, 1))
            }
            Builtin::MaxInt => {
                format!("std::cmp::max({}, {})", a(self, 0), a(self, 1))
            }
            Builtin::MinFloat => {
                format!("crate::sudo_rt::fmin({}, {})", a(self, 0), a(self, 1))
            }
            Builtin::MaxFloat => {
                format!("crate::sudo_rt::fmax({}, {})", a(self, 0), a(self, 1))
            }
            Builtin::FloatOfInt => format!("({} as f64)", a(self, 0)),
            Builtin::IntOfFloat => format!("crate::sudo_rt::int_of({})", a(self, 0)),
            Builtin::Floor => format!("crate::sudo_rt::floor({})", a(self, 0)),
            Builtin::Ceil => format!("crate::sudo_rt::ceil({})", a(self, 0)),
            Builtin::Round => format!("crate::sudo_rt::round_half_away({})", a(self, 0)),
            Builtin::Sqrt => format!("crate::sudo_rt::sqrt({})", a(self, 0)),
            Builtin::Filled => {
                let n = a(self, 0);
                let v = self.expr(&args[1]);
                format!("crate::sudo_rt::filled({n}, &({v}))")
            }
            Builtin::NewMap => "std::collections::HashMap::new()".into(),
            Builtin::NewSet => "std::collections::HashSet::new()".into(),
            Builtin::ListLength => format!("({}.len() as i64)", a(self, 0)),
            Builtin::MapSize | Builtin::SetSize => {
                format!("({}.len() as i64)", a(self, 0))
            }
            Builtin::MapGet => {
                format!("{}.get(&({})).cloned()", a(self, 0), a(self, 1))
            }
            Builtin::MapHas => format!("{}.contains_key(&({}))", a(self, 0), a(self, 1)),
            Builtin::MapKeys => {
                format!("{}.keys().cloned().collect::<Vec<_>>()", a(self, 0))
            }
            Builtin::MapValues => {
                format!("{}.values().cloned().collect::<Vec<_>>()", a(self, 0))
            }
            Builtin::SetHas => format!("{}.contains(&({}))", a(self, 0), a(self, 1)),
            Builtin::SetItems => {
                format!("{}.iter().cloned().collect::<Vec<_>>()", a(self, 0))
            }
            Builtin::OptIsSome => format!("{}.is_some()", a(self, 0)),
            Builtin::OptIsNone => format!("{}.is_none()", a(self, 0)),
            Builtin::OptUnwrap => format!("crate::sudo_rt::unwrap_opt({})", a(self, 0)),
            Builtin::ResUnwrap => format!("crate::sudo_rt::unwrap_res({})", a(self, 0)),
            Builtin::OptGetOr => {
                format!(
                    "{}.unwrap_or_else(|| {})",
                    a(self, 0),
                    self.store(&args[1])
                )
            }
            Builtin::ResGetOr => {
                // Result::unwrap_or_else takes FnOnce(E) -> T
                format!(
                    "{}.unwrap_or_else(|_| {})",
                    a(self, 0),
                    self.store(&args[1])
                )
            }
            Builtin::ResIsOk => format!("{}.is_ok()", a(self, 0)),
            Builtin::ResIsErr => format!("{}.is_err()", a(self, 0)),
            _ => unreachable!("mutating builtin in non-mut position: {b:?}"),
        }
    }

    fn mut_builtin(&mut self, b: Builtin, recv: &Place, args: &[IrExpr]) -> String {
        // Always materialize non-receiver args into temps before taking &mut
        // on the receiver. Free-function calls (put/at/insert/…) do not get
        // method two-phase borrows — simultaneous &mut + & is E0502.
        match b {
            Builtin::ListAppend => {
                let v = self.store(&args[0]);
                let r = self.place_path(recv);
                format!("{{ let _sudo_v = {v}; {r}.push(_sudo_v) }}")
            }
            Builtin::ListPop => {
                let br = self.as_mut_ref(recv);
                format!("crate::sudo_rt::pop({br})")
            }
            Builtin::ListInsert => {
                let i = self.expr(&args[0]);
                let v = self.store(&args[1]);
                let br = self.as_mut_ref(recv);
                format!(
                    "{{ let _sudo_i = {i}; let _sudo_v = {v}; crate::sudo_rt::insert({br}, _sudo_i, _sudo_v) }}"
                )
            }
            Builtin::ListRemoveAt => {
                let i = self.expr(&args[0]);
                let br = self.as_mut_ref(recv);
                format!("{{ let _sudo_i = {i}; crate::sudo_rt::remove_at({br}, _sudo_i) }}")
            }
            Builtin::ListSwap => {
                let i = self.expr(&args[0]);
                let j = self.expr(&args[1]);
                let br = self.as_mut_ref(recv);
                format!(
                    "{{ let _sudo_i = {i}; let _sudo_j = {j}; crate::sudo_rt::swap({br}, _sudo_i, _sudo_j) }}"
                )
            }
            Builtin::ListSort => {
                let r = self.place_path(recv);
                format!("{r}.sort()")
            }
            Builtin::MapDelete => {
                let k = self.expr(&args[0]);
                let r = self.place_path(recv);
                format!("{{ let _sudo_k = {k}; {r}.remove(&_sudo_k).is_some() }}")
            }
            Builtin::SetAdd => {
                let v = self.store(&args[0]);
                let r = self.place_path(recv);
                format!("{{ let _sudo_v = {v}; {r}.insert(_sudo_v) }}")
            }
            Builtin::SetRemove => {
                let v = self.expr(&args[0]);
                let r = self.place_path(recv);
                format!("{{ let _sudo_v = {v}; {r}.remove(&_sudo_v) }}")
            }
            _ => unreachable!("non-mutating builtin in mut position: {b:?}"),
        }
    }

    fn line(&mut self, depth: usize, s: &str) {
        for _ in 0..depth {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) {
        self.out.push('\n');
    }
}

// Need MutBuiltin with recv_ty for sort — re-implement mut_builtin call site.
// Patch: in expr_raw for MutBuiltin, pass recv_ty.

// ---- helpers ----------------------------------------------------------------

fn aliasing(kind: &IrExprKind) -> bool {
    match kind {
        IrExprKind::Local(_)
        | IrExprKind::Const(_)
        | IrExprKind::GetField { .. }
        | IrExprKind::Index { .. } => true,
        IrExprKind::Builtin { builtin, .. } => matches!(
            builtin,
            Builtin::OptUnwrap
                | Builtin::OptGetOr
                | Builtin::ResUnwrap
                | Builtin::ResGetOr
        ),
        _ => false,
    }
}

/// Types that need `.clone()` at owning store points.
/// Enum is included (Rust move semantics) — deliberate departure from JS.
fn needs_dup(ty: &Ty) -> bool {
    match ty {
        Ty::List(_) | Ty::Map(..) | Ty::Set(_) | Ty::Record(_) | Ty::Enum(_) => true,
        Ty::Option_(t) => needs_dup(t),
        Ty::Result_(t, e) => needs_dup(t) || needs_dup(e),
        Ty::Tuple(ts) => ts.iter().any(needs_dup),
        _ => false,
    }
}

fn strip(ty: &Ty) -> &Ty {
    ty
}

/// Cross-module `dep.fn` → `dep::fn`; bare names unchanged.
fn qual_name(name: &str) -> String {
    if name.contains('.') {
        name.replace('.', "::")
    } else {
        name.to_string()
    }
}

/// Box enum-payload fields of these kinds (same rule as backend_c::boxed_in_payload).
fn boxed_in_payload(ty: &Ty) -> bool {
    matches!(
        ty,
        Ty::Record(_) | Ty::Enum(_) | Ty::Option_(_) | Ty::Result_(..) | Ty::Tuple(_)
    )
}

fn ty_str(ty: &Ty) -> String {
    match ty {
        Ty::Int => "i64".into(),
        Ty::Float => "f64".into(),
        Ty::Bool => "bool".into(),
        Ty::List(t) => format!("Vec<{}>", ty_str(t)),
        Ty::Set(t) => format!("std::collections::HashSet<{}>", ty_str(t)),
        Ty::Map(k, v) => format!(
            "std::collections::HashMap<{}, {}>",
            ty_str(k),
            ty_str(v)
        ),
        Ty::Option_(t) => format!("Option<{}>", ty_str(t)),
        Ty::Result_(t, e) => format!("Result<{}, {}>", ty_str(t), ty_str(e)),
        Ty::Tuple(ts) => {
            let parts: Vec<String> = ts.iter().map(ty_str).collect();
            if parts.len() == 1 {
                format!("({},)", parts[0])
            } else {
                format!("({})", parts.join(", "))
            }
        }
        Ty::Func { params, ret } => {
            let ps: Vec<String> = params.iter().map(ty_str).collect();
            match ret {
                Some(r) => format!("fn({}) -> {}", ps.join(", "), ty_str(r)),
                None => format!("fn({})", ps.join(", ")),
            }
        }
        Ty::Record(n) | Ty::Enum(n) => n.clone(),
        Ty::Infer(_) => "()".into(),
    }
}

fn type_is_hashable(ty: &Ty, m: &IrModule, seen: &mut Vec<String>) -> bool {
    match ty {
        Ty::Int | Ty::Bool => true,
        Ty::Float | Ty::Map(..) | Ty::Set(_) | Ty::Func { .. } | Ty::Infer(_) => false,
        Ty::List(t) | Ty::Option_(t) => type_is_hashable(t, m, seen),
        Ty::Result_(t, e) => type_is_hashable(t, m, seen) && type_is_hashable(e, m, seen),
        Ty::Tuple(ts) => ts.iter().all(|t| type_is_hashable(t, m, seen)),
        Ty::Record(name) => {
            if seen.contains(name) {
                return true;
            }
            seen.push(name.clone());
            m.record(name)
                .is_some_and(|r| r.fields.iter().all(|(_, t)| type_is_hashable(t, m, seen)))
        }
        Ty::Enum(name) => {
            if seen.contains(name) {
                return true;
            }
            seen.push(name.clone());
            m.enum_(name).is_some_and(|e| {
                e.variants
                    .iter()
                    .all(|v| v.fields.iter().all(|(_, t)| type_is_hashable(t, m, seen)))
            })
        }
    }
}

/// Escape a string for embedding as a Rust `"..."` literal (no surrounding quotes).
fn escape_rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out
}

fn rust_float_lit(v: f64) -> String {
    if v.is_nan() {
        return "f64::NAN".into();
    }
    if v.is_infinite() {
        return if v.is_sign_positive() {
            "f64::INFINITY".into()
        } else {
            "f64::NEG_INFINITY".into()
        };
    }
    if v == 0.0 && v.is_sign_negative() {
        return "-0.0f64".into();
    }
    let s = format!("{v:?}");
    if !s.contains('.') && !s.contains('e') && !s.contains('E') {
        format!("{s}.0f64")
    } else if s.ends_with("f64") {
        s
    } else {
        format!("{s}f64")
    }
}

// Fix ListSort: need recv_ty. Redefine MutBuiltin handling properly by
// replacing the method. We'll patch mut_builtin to take recv_ty.

impl Emitter<'_> {
    fn mut_builtin_ty(
        &mut self,
        b: Builtin,
        recv: &Place,
        recv_ty: &Ty,
        args: &[IrExpr],
    ) -> String {
        if b == Builtin::ListSort {
            let br = self.as_mut_ref(recv);
            match strip(recv_ty) {
                Ty::List(elem) if matches!(strip(elem), Ty::Float) => {
                    return format!("crate::sudo_rt::sort_floats({br})");
                }
                _ => {
                    // Ord types (i64): stable sort via slice.
                    return format!("({br}).sort()");
                }
            }
        }
        self.mut_builtin(b, recv, args)
    }
}

/// The Rust backend, via the SDK contract.
pub struct RsBackend;

impl sudoc_sdk::Backend for RsBackend {
    fn name(&self) -> &'static str {
        "rs"
    }

    fn emit_program(
        &self,
        modules: &[IrModule],
        with_tests: bool,
    ) -> Result<Vec<sudoc_sdk::GeneratedFile>, String> {
        let (entry, deps) = modules.split_last().expect("entry module");
        let mut out = Vec::new();
        for m in deps {
            out.push(sudoc_sdk::GeneratedFile {
                path: module_file(&m.name),
                contents: emit(m, false, false),
            });
        }
        out.push(sudoc_sdk::GeneratedFile {
            path: module_file(&entry.name),
            contents: emit(entry, with_tests, true),
        });
        Ok(out)
    }

    fn runtime_files(&self) -> Vec<sudoc_sdk::GeneratedFile> {
        vec![sudoc_sdk::GeneratedFile {
            path: RUNTIME_FILE.into(),
            contents: RUNTIME.into(),
        }]
    }

    fn test_recipe(&self, entry: &str) -> sudoc_sdk::TestRecipe {
        sudoc_sdk::TestRecipe {
            build: vec![vec![
                "rustc".into(),
                "--edition".into(),
                "2021".into(),
                "-A".into(),
                "warnings".into(),
                "-o".into(),
                "sudo_tests".into(),
                format!("{entry}.rs"),
            ]],
            run: vec!["./sudo_tests".into()],
        }
    }
}
