load("@rules_rust//rust:defs.bzl", "rust_library")

exports_files(["Cargo.toml"])

rust_library(
    name = "sdk",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    crate_name = "sudoc_sdk",
    rustc_flags = ["-Dunsafe_code"],
    deps = ["//sudoc/crates/ir:ir"],
    visibility = ["//visibility:public"],
)
