"""sudo_complexity_test: an operation-count regression test for stdlib .sudo
modules.

Wall-clock gates were deliberately rejected in this repo (flaky on shared
runners). sudo is pure and deterministic, so *operation counts* at workload
size n and 2n are exactly reproducible. sudo_complexity_test builds the named
module for the py backend -- dogfooding sudocode's own first-party sudoc, like
tools/backends.bzl's dogfood_lockstep_test -- always with SUDO_COUNT_OPS=1 set
(see sudoc/crates/backend_py/src/lib.rs / runtime/_sudo_rt.py), so generated
list-concat (`+`) and list-append route through the runtime's counting
wrappers (_rt.count_add / _rt.count_append) instead of raw Python operators.
This build-time switch is OFF in every other build in this repo (including
all dogfood_lockstep_test targets, which never set it) and is provably inert
on generated output when unset -- see backend_py/src/lib.rs.

A driver that doesn't need op counting (e.g. sorting.sort_by, which counts
*comparator calls* by passing its own counting closure as `less` -- no
codegen hook needed) still gets the SUDO_COUNT_OPS=1 build; the instrumented
runtime calls are simply never exercised by that code path.

This lives in tools/, not rules_sudo/private/: it dogfoods sudocode's own
first-party sudoc binary and its interface is coupled to backend_py's
internal SUDO_COUNT_OPS convention -- not a stable public rules_sudo concern,
same reasoning as tools/backends.bzl's dogfood_lockstep_test.
"""

load("@rules_sudo//:defs.bzl", "SudoInfo")

_SUDOC = "//sudoc/crates/cli:sudoc"

def _stage_command(srcs, stage):
    lines = ['mkdir -p "%s"' % stage]
    for f in srcs:
        lines.append('cp "{src}" "{stage}/$(basename "{src}")"'.format(src = f.path, stage = stage))
    return "\n".join(lines)

def _codegen_impl(ctx):
    """Build the module for py with SUDO_COUNT_OPS=1 (module doc)."""
    sudoc = ctx.executable.sudoc
    src_list = ctx.attr.lib[SudoInfo].transitive_srcs.to_list()
    out_dir = ctx.actions.declare_directory(ctx.label.name)
    stage = "_stage_{}".format(ctx.label.name)
    entry = ctx.attr.entry.split("/")[-1]
    command = """
set -euo pipefail
{stage}
SUDO_COUNT_OPS=1 "{sudoc}" build --target py -o "{out}" "{stagedir}/{entry}"
""".format(
        stage = _stage_command(src_list, stage),
        sudoc = sudoc.path,
        out = out_dir.path,
        stagedir = stage,
        entry = entry,
    )
    ctx.actions.run_shell(
        inputs = src_list,
        outputs = [out_dir],
        tools = [sudoc],
        command = command,
        mnemonic = "SudoComplexityCodegen",
        progress_message = "sudoc codegen (SUDO_COUNT_OPS=1) %{label}",
    )
    return [DefaultInfo(files = depset([out_dir]), runfiles = ctx.runfiles(files = [out_dir]))]

_complexity_codegen = rule(
    implementation = _codegen_impl,
    attrs = {
        "lib": attr.label(providers = [SudoInfo], mandatory = True),
        "entry": attr.string(mandatory = True),
        "sudoc": attr.label(executable = True, cfg = "exec", allow_single_file = True, mandatory = True),
    },
)

_RF_PRELUDE = r"""
if [[ -n "${TEST_SRCDIR:-}" ]]; then
  RUNFILES="${TEST_SRCDIR}"
elif [[ -d "$(dirname "$0").runfiles" ]]; then
  RUNFILES="$(cd "$(dirname "$0").runfiles" && pwd)"
else
  echo "sudo_complexity_test: cannot locate runfiles" >&2; exit 1
fi
WS="${TEST_WORKSPACE:-_main}"
rf() {
  local kind="$1" rel="$2"
  if [[ "$kind" == "external" ]]; then
    echo "${RUNFILES}/${rel}"
  elif [[ -e "${RUNFILES}/${WS}/${rel}" ]]; then
    echo "${RUNFILES}/${WS}/${rel}"
  else
    echo "${RUNFILES}/${rel}"
  fi
}
"""

def _rf_path(f):
    sp = f.short_path
    if sp.startswith("../"):
        return ("external", sp[3:])
    return ("workspace", sp)

def _test_impl(ctx):
    gen_kind, gen_rel = _rf_path(ctx.file.gen)
    driver_kind, driver_rel = _rf_path(ctx.file.driver)
    py3 = ctx.toolchains["@rules_python//python:toolchain_type"].py3_runtime
    py_kind, py_rel = _rf_path(py3.interpreter)

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by sudo_complexity_test -- do not edit.",
        _RF_PRELUDE,
        'GEN="$(rf "%s" "%s")"' % (gen_kind, gen_rel),
        'DRIVER="$(rf "%s" "%s")"' % (driver_kind, driver_rel),
        'PY_BIN="$(dirname "$(rf "%s" "%s")")"' % (py_kind, py_rel),
        'export PATH="$PY_BIN:$PATH"',
        'exec python3 "$DRIVER" "$GEN" %d %d %s' % (ctx.attr.small_n, ctx.attr.large_n, ctx.attr.bound),
    ]
    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = launcher, content = "\n".join(lines) + "\n", is_executable = True)

    runfiles = ctx.runfiles(files = [ctx.file.gen, ctx.file.driver], transitive_files = py3.files)
    return [
        DefaultInfo(executable = launcher, runfiles = runfiles),
        RunEnvironmentInfo(inherited_environment = ["PATH"]),
    ]

_complexity_test = rule(
    implementation = _test_impl,
    test = True,
    attrs = {
        "gen": attr.label(allow_single_file = True, mandatory = True),
        "driver": attr.label(allow_single_file = [".py"], mandatory = True),
        "small_n": attr.int(mandatory = True),
        "large_n": attr.int(mandatory = True),
        "bound": attr.string(mandatory = True),
    },
    toolchains = ["@rules_python//python:toolchain_type"],
)

def sudo_complexity_test(
        name,
        lib,
        entry,
        driver,
        bound,
        small_n = 2000,
        large_n = 4000,
        sudoc = _SUDOC,
        timeout = "long",
        tags = [],
        **kwargs):
    """An operation-count regression test (see module doc).

    Args:
      name: test target name.
      lib: a sudo_library target for the module under test.
      entry: basename of the entry .sudo file within lib.
      driver: a Python driver script, invoked as
        `driver.py <gen_dir> <small_n> <large_n> <bound>`. <gen_dir> is the
        filesystem path to the SUDO_COUNT_OPS=1-built py package (containing
        _<mod>_impl.py + _sudo_rt.py); the driver adds it to sys.path and
        imports directly. It measures its own operation count at small_n and
        large_n (comparator calls, or _sudo_rt.op_counts()), computes
        ratio = ops(large_n)/ops(small_n), asserts ratio <= bound, and exits
        nonzero with a message on failure.
      bound: STRING (Starlark has no attr.float) -- the max allowed ratio,
        e.g. "2.3". Mandatory: each test must declare its own claim.
      small_n / large_n: workload sizes (large_n should be exactly 2x
        small_n).
      sudoc: sudoc binary override (defaults to sudocode's own first-party
        build).
    """
    _complexity_codegen(
        name = name + "_gen",
        lib = lib,
        entry = entry,
        sudoc = sudoc,
    )
    test_tags = list(tags)
    if "local" not in test_tags:
        test_tags.append("local")
    _complexity_test(
        name = name,
        gen = ":" + name + "_gen",
        driver = driver,
        small_n = small_n,
        large_n = large_n,
        bound = bound,
        timeout = timeout,
        tags = test_tags,
        **kwargs
    )
