load("@rules_rust//rust:defs.bzl", "rust_library")

exports_files(["Cargo.toml"])

rust_library(
    name = "backend_c",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    crate_name = "sudoc_backend_c",
    rustc_flags = ["-Dunsafe_code"],
    compile_data = glob(["src/runtime/**"]),
    deps = [
        "//sudoc/crates/ir:ir",
        "//sudoc/crates/sdk:sdk",
        "//sudoc/crates/types:types",
    ],
    visibility = ["//visibility:public"],
)
